### ISSUE TITLE
support java client auto reconnect

### ISSUE THREAD

**Issue by dzj2046** [hazelcast/hazelcast#10135]
can java client  support auto reconnect?

**Comment by sancar** [comment]
This is already came up here https://github.com/hazelcast/hazelcast/issues/9692  and here https://github.com/hazelcast/hazelcast/issues/4363

It is in the plan of next things to do but don't assigned to a release officially yet.

**Comment by simpleusr** [comment]
@sancar  What is the plan for this development. To remedy this, currently we are planning to introduce a sanity thread on the client. This therad will check whether the client is running or not using the below snippet:

 `boolean running = clientInstance.getLifecycleService().isRunning();`

And if it is not running a new instance will be started. 

Is that ok? Would you recommend any other solution?

**Comment by mukul4u2005** [comment]
Hi

 java client auto reconnect is available or not ?

please suggest Hazelcast version where Its released?

Thanks
Mukul

**Comment by sancar** [comment]
@mukul4u2005 

Our clients can not recover when it is shutdown. We advise our users to configure the client so that, it never shuts down(or a long shutdown period ). In that case, client will try to connect back to cluster periodically after disconnect. 

This can be achieved by setting following properties
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#setting-connection-timeout
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#setting-connection-attempt-limit
Note that we have done quite an enchancement around reconnect, you can check new configuration 
https://docs.hazelcast.org/docs/3.11/manual/html-single/index.html#configuring-client-connection-retry 

In 3.9, we have introduced async reconnect mode to give flexible behaviour in disconnected period.
For details you can see this doc.
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#configuring-client-connection-strategy

If you have follow up questions please ask in google group,
You can also describe your use case in more detail in there so that we can advise you a fitting solution.
https://groups.google.com/forum/#!forum/hazelcast
Regards

**Comment by simpleusr** [comment]
Hi, @sancar 

When I am trying to use this new feature in 3.11 client , I am having below error.

  Element 'connection-strategy' must have no character or element information item [children], because the type's content type is empty.

I also asked below question could you please help?
 
[https://groups.google.com/forum/#!topic/hazelcast/B3FqdExek5U](https://groups.google.com/forum/#!topic/hazelcast/B3FqdExek5U)

**Comment by simpleusr** [comment]
Hi @sancar 

This is  due to a silly classpath problem in my application. There is no error. Sorry for the inconvenience
