### ISSUE TITLE
Client oom ClientSmartListenerService,

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10156]
Hz version 3.8.1

https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x/6/console Failed  

/disk1/jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy Failed

http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy

http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/gc.html

http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/gc.html
client GC
![image](https://cloud.githubusercontent.com/assets/5988678/24392156/59797930-139b-11e7-9e71-53760f3452de.png)

hprof
http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/output/HZ/HzClient1HZ/HzClient1HZ.hprof

output/HZ/HzClient3HZ/HzClient3HZ.hprof
output/HZ/HzClient2HZ/HzClient2HZ.hprof
output/HZ/HzClient1HZ/HzClient1HZ.hprof

<img width="635" alt="screen shot 2017-03-28 at 09 48 18" src="https://cloud.githubusercontent.com/assets/5988678/24392251/b54fb364-139b-11e7-96ad-d46fc224170a.png">

**Comment by Danny-Hazelcast** [comment]
structs created used and destroyed http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_27-17_21_51/create-use-destroy/createUseDestroy

**Comment by Danny-Hazelcast** [comment]
explicitly using listeners are 

https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/cqc/CreateUseDestroy.java


but maybe all listeners work the same, if we were to register a listener to a map then destroy it ?

**Comment by jerrinot** [comment]
my first impression from the heapdump: it's somehow related to CQC

**Comment by sancar** [comment]
`ClientQueryCacheContext` is the object that fills most of the memory. 
It seems like it can be singleton but created per map !?!. 
And as far as I understand they are not garbage collected because listeners are not deregistered when map is destroyed. 

Listener registrations actually are the ones that pile up, but since `ClientQueryCacheContext`  is bigger it is the first thing take notice in the heap dump. 

We may reduce the memory usage by converting `ClientQueryCacheContext` per instance rather than per map if possible.
But not sure about deregistering listener when map is destroyed. It looks like users job.

**Comment by ahmetmircik** [comment]
@sancar 👍 

Seems we can do at least 2 things for this issue:
1. `ClientQueryCacheContext` can be 1 instance.
2. Listener needs to be de-registered upon `QueryCache` destroy. It is an internal listener and causes memory leak.

**Comment by ahmetmircik** [comment]
seems still an issue:
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x3/51/console
http://54.82.84.143/~jenkins/workspace/stable-x3/3.9/2017_10_26-14_54_32/create-use-destroy-map/
