### ISSUE TITLE
Client intermediate HeapData litter

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#10312]
When the client `map.get` returns a value (and I'm sure it will be the same thing for many other calls), the client makes an `HeapData` from the content in the client-buffer. And then this heap data is deserialized.

This intermediate HeapData object shoudn't be needed; the serialization service should make use of the `clientmessage.buffer`.

This skips one potentially large object being allocated

Perhaps we should consider introducing a new `HeapData` with an offset.

**Comment by pveentjer** [comment]
This is an optimization that doesn't require an API change or wire level change. So I'm going to move this to 4.1

**Comment by sancar** [comment]
@pveentjer This is fixed in 4.0. HeapData uses the payload available in ClientMessage without copying it. 
While HeapData was a copy of the data in 3.12, it is just a small wrapper in 4.0. 

Further removing HeapData does not seem possible. It means returning byte[] from the protocol instead of Data on decode. But most of the internal API(Operations, DataWriter/Reader classes, Services ) expects Data.  

Since the `large` litter object is removed(it is not large anymore), I would consider this issue is fixed in 4.0.
