### ISSUE TITLE
Mapstore doesn't load data from database after node restart

### ISSUE THREAD

**Issue by tvd12** [hazelcast/hazelcast#10452]
I have two nodes

Node 1: config mapstore
Node 2: not config mapstore

When I start two nodes, everything are ok. But when I restart Node 1, I call ```map.get("key")```, I see that hazelcast only looking for ```"key"``` on Node 2 and mapstore on Node1 doesn't load data from database

**Comment by vbekiaris** [comment]
Hi @tvd12 , the map store needs to be configured on all of your cluster's nodes. Since data is distributed across nodes in the cluster, any node can be the owner for `"key"`. When doing a `map.get("key")`, the partition owner is asked for the data, so it needs to be aware of the map store configuration in order to load the data from the data store.

In general, the same configuration should be deployed on all your cluster's nodes, otherwise behavior may be unpredictable.

I am closing this issue, as this is not a supported configuration. Feel free to ask more questions at the [google group](https://groups.google.com/forum/#!forum/hazelcast) or raise further issues here.

Cheers!
Vassilis
