### ISSUE TITLE
Id like to be able to obtain the keys+values held by a NearCache without triggering any net lookups

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#11017]
Id like to be able to obtain the full set of keys and values stored in a NearCache without triggering any network calls. Perhaps something like `localKeySet()` and `localValues()`.  After looking at this, perhaps `localMap()` would be simpler although I could see use cases where we wouldn't want to incur the deserialization cost for both keys _and_ values.  

Other thoughts after looking at the 3.8.4 code - how would this operation impact near cache stats - would/should this count as +1 on all entries?

**Comment by tkountis** [comment]
cc @Donnerbart

**Comment by Donnerbart** [comment]
Just some thoughts about this.

We have the Near Cache in `IMap`, `ICache` and `ReplicatedMap` (just on clients, which don't have replicated data locally). So we would need to change all three interfaces, without confusing the users with the method naming. This can be quite tricky, since especially with members and clients the term "local" has different meanings (clients never have local data, just cached data). I think an explicit naming with `getNearCacheKeySet()` or `getCachedKeySet()` would be better.

FYI: starting with 3.9 the Near Cache keys won't be serialized for on-heap Near Caches by default. If you also use the in-memory-format `OBJECT`, there should be no serialization costs for such an operation.

Since this requires a public API change, I think we will need a PRD and design document for this. This can also just be introduced in a minor version, so 3.10 or later. Could you create a PRD, please @burakcelebi?

**Comment by vertex-github** [comment]
Method naming - understood and completely agree.  Whatever name you folks come up with :-)

Serialization costs - Fully understood, but the costs of deserialization locally will still be dwarfed by the costs of going to the remote cluster and incurring net+deserialization costs, so even in 3.8.x I think its a win.  Obviously, the less deserialization we can do the better. :-)

**Comment by burakcelebi** [comment]
Closed as internal request
