### ISSUE TITLE
Reliable iteration during partition migration with MapProxyImpl.iterator()

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#11106]
Javadoc for `MapProxyImpl.iterator()` states: 
> Iterating the map should be done only when the IMap is not being mutated and the cluster is stable (there are no migrations or membership changes). In other cases, the iterator may not return some entries or may return an entry twice.

It is easy for the user to satisfy the first condition (non mutation), but not so for the second one (no migration, you can't prevent failure and you want elasticity). 

Changes to internal structures are requested to guarantee that iteration order is preserved:
- among main and backup copies of the partition
- after main copy of partition is moved to another member

**Comment by tombujok** [comment]
MapReplicationStateHolder uses a HashSet for records so it does not preserve the order - this would need to be changed.
https://github.com/tombujok/hazelcast/blob/43132f12e9e7407ca9f68898ebd0e759c8f9b679/hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapReplicationStateHolder.java#L92-L92

Also it would have to be verified that `Storage.values()` and internally `SampleableConcurrentHashMap` provides the iteration order equal to insertion order.

**Comment by mmedenjak** [comment]
An another problem might be that the backing structure - `BinaryElasticHashMap` does not shrink after it has been expanded due to increased key domain. The partition migration operation should then create a `BinaryElasticHashMap` of the same size as on the primary replica even though it may be mostly sparse. The data on the receiving replica will then occupy the same slots as on the primary replica.

**Comment by mmedenjak** [comment]
Instead of relying on the table index, maybe a better way would be starting from the lowest key hash  (`Integer.MIN_VALUE`) and relying on the last-observed key hash. Based on the key hash we can always find the table index and entries and the iterator is no longer affected by migrations and mutation.

**Comment by cangencer** [comment]
That sounds good to me. Missing new items isn't an issue but duplicates and missing old items is. How would it work with pagination? You'd need to restart your search from a specific hash code for example. Is the table index sorted by hash code?

**Comment by mmedenjak** [comment]
I think read performance would suffer as the table index is not sorted by hash code and you need to iterate all entries with the same table index to get the ones that have a specific hash code.
But the upside is that it is then migration and mutation tolerant and uses just a single integer to mark the iterator position, just as the current iterator with the table index.
I currently don't see a third way but there might be one.

**Comment by mmedenjak** [comment]
This is part of a PRD now: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/498663502/Support+IMap+iterations+with+concurrent+mutation
