### ISSUE TITLE
Hazelcast 3.8.4 source code does not match the jar classes

### ISSUE THREAD

**Issue by rruxandra** [hazelcast/hazelcast#11261]
Hello,

We are having a problem with the sources of the Hazelcast 3.8.4 release.
It seems the source code doesn't match the classes in the jar for the same version.

We downloaded both the jar and the sources from the mavel central repository:
http://central.maven.org/maven2/com/hazelcast/hazelcast/3.8.4/hazelcast-3.8.4.jar
http://central.maven.org/maven2/com/hazelcast/hazelcast/3.8.4/hazelcast-3.8.4-sources.jar

An example of such mismatch is the package: com/hazelcast/cache/impl/maxsize/impl.
In the jar there is only EntryCountCacheMaxSizeChecker class but in the sources there is also EntryCountCacheEvictionChecker class.

It seems the issue comes from the shaded hazelcast-client-protocol that contains the Hazelcast sources from a different version.

Would it be possible to check this?

Thank you,
Ruxandra

**Comment by Donnerbart** [comment]
Thanks for reporting this. I don't think we can (or should) change published JARs on Maven central. But we should have a look to prevent this in the future.

**Comment by Donnerbart** [comment]
I can confirm this and I think your analysis is spot on. I just checked our upcoming 3.8.5 release and it suffers from the same issue.

The Hazelcast client protocol JAR contains this (outdated) class:
![screenshot from 2017-08-30 14-27-40](https://user-images.githubusercontent.com/4196298/29872397-be6c7888-8d8f-11e7-9229-222d17066add.png)

The 3.8.5 branch has the actual class:
![screenshot from 2017-08-30 14-30-36](https://user-images.githubusercontent.com/4196298/29872417-dc686914-8d8f-11e7-8f1e-5be274cce0d9.png)

And the final sources JAR contains both classes:
![screenshot from 2017-08-30 14-27-52](https://user-images.githubusercontent.com/4196298/29872431-ebe8262c-8d8f-11e7-8df6-6e6230e4b298.png)

The root cause will be, that the client protocol project relies on some Hazelcast classes. So it fetches a (custom) branch to build the protocol JAR. And that JAR is again needed to build Hazelcast. It's an unfortunate circle dependency.

I'm having a look how to solve this at least for a release situation, so the source code matches.

**Comment by rruxandra** [comment]
Thanks a lot for the quick fix :)
It's not a major problem for us right now but it's good to know it's fixed in upcoming versions.
