### ISSUE TITLE
provide offheap storage option

### ISSUE THREAD

**Issue by cforce** [hazelcast/hazelcast#11328]
EhCache provides this valuable feature since ehCache 3.0.
Being not interuppted by GC and the possibiilty to consume all available memory, is a big advantage.

**Comment by mmedenjak** [comment]
Hi @cforce !

We already provide offheap storage as part of our commercial solution - http://docs.hazelcast.org/docs/3.8.5/manual/html-single/index.html#high-density-memory-store. We do not have any plans for open-sourcing it at this point.

I will close this issue as I don't see it as something we can fix rather than as a business decision.
