### ISSUE TITLE
[near-cache] NearCacheLiteMemberTest.testPut

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11388]
```
java.lang.AssertionError: Near Cache size should be > 0 but was 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.impl.nearcache.NearCacheLiteMemberTest.assertLiteMemberNearCacheNonEmpty(NearCacheLiteMemberTest.java:492)
	at com.hazelcast.map.impl.nearcache.NearCacheLiteMemberTest.testPut(NearCacheLiteMemberTest.java:181)
	at com.hazelcast.map.impl.nearcache.NearCacheLiteMemberTest.testPut(NearCacheLiteMemberTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/696/testReport/junit/com.hazelcast.map.impl.nearcache/NearCacheLiteMemberTest/testPut/

**Comment by Donnerbart** [comment]
Hmm, I think the whole `NearCacheLiteMemberTest` could suffer from the invalidation vs. creation race, we encountered in most of the Near Cache tests.
```java
    public static void testPut(HazelcastInstance instance, HazelcastInstance lite, String mapName) {
        IMap<Object, Object> map = instance.getMap(mapName);

        int count = 100;
        for (int i = 0; i < count; i++) {
            map.put(i, i);
        }

        IMap<Object, Object> liteMap = lite.getMap(mapName);
        for (int i = 0; i < count; i++) {
            liteMap.get(i);
        }

        assertLiteMemberNearCacheNonEmpty(lite, mapName);
    }
```
The map is populated from a member, this creates invalidation messages (they are enabled in this test). Directly after that the Near Cache is populated. If the invalidations events are processed after the Near Cache population, it can be empty when the assert is done.

After https://github.com/hazelcast/hazelcast/pull/11416 is merged, the whole test class should be obsolete, since all tests should be part of the unified Near Cache test framework. The only hurdle is `ClientMapNearCacheLiteMemberTest`, which re-uses the tests from `NearCacheLiteMemberTest`. But I don't know if this is really adding a new scenario, will have to check that.

**Comment by Donnerbart** [comment]
If you change the test to `count = 99` and add `sleepSeconds(15)` before the assert, the test fails regularly, due to the described invalidations on entry creation:
* 99 entries is below the invalidation batch trigger size, so the invalidations are sent with on an interval basis (this helps to enforce the race)
* then the Near Cache population happens before the invalidations are sent/processed
* the sleep waits for the invalidations
* then the assert fails, since the Near Cache is completely empty

A solution would be to create the lite members after the data structure is being created (that's what we do in the unified tests). But I would prefer to get rid of these duplicated tests instead.
