### ISSUE TITLE
ClientRegressionWithRealNetworkTest.testConnectWithDNSHostnames

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#11430]
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testConnectWithDNSHostnames(ClientRegressionWithRealNetworkTest.java:134)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1414/testReport/junit/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testConnectWithDNSHostnames/

**Comment by ihsandemir** [comment]
When analysed the log, I observe that the test d'd not achieve the reconnection as desired but finished earlier than expected. This is due to the test design. Need to make sure that the client disconnects and connects as expected from the test. Here is the related log:

05:22:56,996  INFO |testConnectWithDNSHostnames| - [ClusterService] hz._hzInstance_584_dev.generic-operation.thread-2 - [localhost]:5702 [dev] [3.9-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [localhost]:5701 - 01beaf98-5882-4778-a4a6-26aa52b7052a
	Member [localhost]:5702 - 8f0ba36c-9206-43d6-aba1-2e6b792ccb16 this
]

05:22:56,997  INFO |testConnectWithDNSHostnames| - [AuthenticationMessageTask] hz._hzInstance_584_dev.priority-generic-operation.thread-0 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Received auth from Connection[id=2, /127.0.0.1:5702->/127.0.0.1:45738, endpoint=null, alive=true, type=JAVA_CLIENT], successfully authenticated, principal: ClientPrincipal{uuid='9970a8e3-10b5-4fe2-9abe-4328c530e760', ownerUuid='01beaf98-5882-4778-a4a6-26aa52b7052a'}, owner connection: false, client version: 3.9-SNAPSHOT
05:22:56,997  INFO |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.internal-2 - hz.client_350 [dev] [3.9-SNAPSHOT] Authenticated with server [localhost]:5702, server version:3.9-SNAPSHOT Local address: /127.0.0.1:45738
05:22:57,257  INFO |testConnectWithDNSHostnames| - [MigrationManager] hz._hzInstance_583_dev.migration - [localhost]:5701 [dev] [3.9-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 271
05:22:58,766  INFO |testConnectWithDNSHostnames| - [MigrationThread] hz._hzInstance_583_dev.migration - [localhost]:5701 [dev] [3.9-SNAPSHOT] All migration tasks have been completed, queues are empty.
05:22:58,995  INFO |testConnectWithDNSHostnames| - [LifecycleService] testConnectWithDNSHostnames - [localhost]:5702 [dev] [3.9-SNAPSHOT] [localhost]:5702 is STARTED
05:22:58,995  INFO |testConnectWithDNSHostnames| - [LifecycleService] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] [localhost]:5701 is SHUTTING_DOWN
05:22:58,995  INFO |testConnectWithDNSHostnames| - [MigrationManager] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Shutdown request of [localhost]:5701 is handled
05:22:59,027  INFO |testConnectWithDNSHostnames| - [MigrationManager] hz._hzInstance_583_dev.migration - [localhost]:5701 [dev] [3.9-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 136
05:22:59,284  INFO |testConnectWithDNSHostnames| - [Node] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Shutting down multicast service...
05:22:59,284  INFO |testConnectWithDNSHostnames| - [Node] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Shutting down connection manager...
05:22:59,284  INFO |testConnectWithDNSHostnames| - [TcpIpConnection] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Connection[id=2, /127.0.0.1:5701->/127.0.0.1:36935, endpoint=[localhost]:5702, alive=false, type=MEMBER] closed. Reason: TcpIpConnectionManager is stopping
05:22:59,285  INFO |testConnectWithDNSHostnames| - [TcpIpConnection] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:53924, endpoint=[127.0.0.1]:53924, alive=false, type=JAVA_CLIENT] closed. Reason: TcpIpConnectionManager is stopping
05:22:59,286  INFO |testConnectWithDNSHostnames| - [Node] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Shutting down node engine...
05:22:59,298  INFO |testConnectWithDNSHostnames| - [NodeExtension] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Destroying node NodeExtension.
05:22:59,298  INFO |testConnectWithDNSHostnames| - [Node] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] Hazelcast Shutdown is completed in 303 ms.
05:22:59,298  INFO |testConnectWithDNSHostnames| - [LifecycleService] testConnectWithDNSHostnames - [localhost]:5701 [dev] [3.9-SNAPSHOT] [localhost]:5701 is SHUTDOWN
05:22:59,299  INFO |testConnectWithDNSHostnames| - [TcpIpConnection] hz._hzInstance_584_dev.IO.thread-in-0 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Connection[id=1, /127.0.0.1:36935->localhost/127.0.0.1:5701, endpoint=[localhost]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
05:22:59,409  INFO |testConnectWithDNSHostnames| - [ClientConnection] hz.hz.client_350.IO.thread-in-0 - hz.client_350 [dev] [3.9-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:53924->localhost/127.0.0.1:5701}, remoteEndpoint=[localhost]:5701, lastReadTime=2017-09-23 05:22:59.299, lastWriteTime=2017-09-23 05:22:56.995, closedTime=2017-09-23 05:22:59.299, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT} closed. Reason: Connection closed by the other side
05:22:59,409  INFO |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.hz.client_350.IO.thread-in-0 - hz.client_350 [dev] [3.9-SNAPSHOT] Removed connection to endpoint: [localhost]:5701, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{0.0.0.0/0.0.0.0:53924->localhost/127.0.0.1:5701}, remoteEndpoint=[localhost]:5701, lastReadTime=2017-09-23 05:22:59.299, lastWriteTime=2017-09-23 05:22:59.409, closedTime=2017-09-23 05:22:59.299, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.9-SNAPSHOT}
05:22:59,410  INFO |testConnectWithDNSHostnames| - [LifecycleService] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170923 - d57f098) is CLIENT_DISCONNECTED
05:22:59,410  INFO |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Trying to connect to [localhost]:5701 as owner member
05:22:59,411  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-2 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Connecting to localhost/127.0.0.1:5701, timeout: 0, bind-any: true
05:22:59,411  WARN |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Exception during initial connection to [localhost]:5701, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
05:22:59,411  INFO |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Trying to connect to [localhost]:5703 as owner member
05:22:59,411  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-2 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Could not connect to: localhost/127.0.0.1:5701. Reason: SocketException[Connection refused to address localhost/127.0.0.1:5701]
05:22:59,411  WARN |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Exception during initial connection to [localhost]:5703, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
05:22:59,411  INFO |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Trying to connect to [localhost]:5701 as owner member
05:22:59,411  WARN |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Exception during initial connection to [localhost]:5701, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
05:22:59,411  INFO |testConnectWithDNSHostnames| - [ClientConnectionManager] hz.client_350.cluster- - hz.client_350 [dev] [3.9-SNAPSHOT] Trying to connect to [localhost]:5702 as owner member
05:22:59,412  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-2 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Connecting to localhost/127.0.0.1:5701, timeout: 0, bind-any: true
05:22:59,412  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-2 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Could not connect to: localhost/127.0.0.1:5701. Reason: SocketException[Connection refused to address localhost/127.0.0.1:5701]
05:22:59,413  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-3 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Connecting to localhost/127.0.0.1:5701, timeout: 0, bind-any: true
05:22:59,413  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-3 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Could not connect to: localhost/127.0.0.1:5701. Reason: SocketException[Connection refused to address localhost/127.0.0.1:5701]
05:22:59,415  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-3 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Connecting to localhost/127.0.0.1:5701, timeout: 0, bind-any: true
05:22:59,415  INFO |testConnectWithDNSHostnames| - [TcpIpConnector] hz._hzInstance_584_dev.cached.thread-3 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Could not connect to: localhost/127.0.0.1:5701. Reason: SocketException[Connection refused to address localhost/127.0.0.1:5701]
05:22:59,417  INFO |testConnectWithDNSHostnames| - [LifecycleService] main - hz.client_350 [dev] [3.9-SNAPSHOT] HazelcastClient 3.9-SNAPSHOT (20170923 - d57f098) is SHUTTING_DOWN
05:22:59,417  INFO |testConnectWithDNSHostnames| - [TcpIpConnection] hz._hzInstance_584_dev.IO.thread-in-1 - [localhost]:5702 [dev] [3.9-SNAPSHOT] Connection[id=2, /127.0.0.1:5702->/127.0.0.1:45738, endpoint=[127.0.0.1]:45738, alive=false, type=JAVA_CLIENT] closed. Reason: Connection closed by the other side

Client shutdown started before client reconnects.
