### ISSUE TITLE
IPv6 support on EC2

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11821]
AWS EC2 [supports](https://aws.amazon.com/blogs/aws/new-ipv6-support-for-ec2-instances-in-virtual-private-clouds/) IPv6, but the Hazelcast explicitly [forces using IPv4](https://github.com/hazelcast/hazelcast/blob/v3.9/hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java#L367-L375) when AWS join is configured.

```java
private boolean preferIPv4Stack() {
    boolean preferIPv4Stack = Boolean.getBoolean("java.net.preferIPv4Stack")
            || hazelcastProperties.getBoolean(GroupProperty.PREFER_IPv4_STACK);
    // AWS does not support IPv6
    JoinConfig join = config.getNetworkConfig().getJoin();
    AwsConfig awsConfig = join.getAwsConfig();
    boolean awsEnabled = awsConfig != null && awsConfig.isEnabled();
    return preferIPv4Stack || awsEnabled;
}
```

**Suggested fix:**
Don't provide the configuration based artificial intelligence (e.g. cloud-provider based). Use just the system (and/or Hazelcast) properties to control the IPv6 support. Users should know themselves if their environment supports the IPv6.

**Comment by mdogan** [comment]
This is historical. AWS started to support IPv6 on [01 DEC 2016](https://aws.amazon.com/blogs/aws/new-ipv6-support-for-ec2-instances-in-virtual-private-clouds/) but Hazelcast supports IPv6 since [2012](https://github.com/hazelcast/hazelcast/commit/496d21753155a0e45fc15c4c413bdc1cdcc8170c). This was to save users explicitly disabling IPv6 while using Hazelcast. Now it's obsolete.
