### ISSUE TITLE
start.sh errors

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#11834]
The `start.sh` script displays warnings on Java 9,

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/Users/neil/Downloads/hazelcast-3.9/lib/hazelcast-all-3.9.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
for OSX 10.13, Java 9.0.1

Also, it would be useful to list the PID in the *.pid file when giving the message
"_Another hazelcast instance is already started in this folder. To start a new instance, please unzip hazelcast-3.9.zip/tar.gz in a new folder._"
as it complains if it finds the file, which isn't exactly the same as whether the process is running.

**Comment by Donnerbart** [comment]
I think the warning is expected, since we use internal JVM classes (`sun.misc.Unsafe` or in this case `sun.nio.ch.SelectorImpl`). In this case it's an attempt to use faster, internal code from the JVM. If we can't find or access those classes, we have a slower fallback. So even if the Jigsaw killswitch is disabled, the code should work (so this is no defect, but there maybe others).

Those warnings have been introduced in Java 9, so it's expected that we see them. I'm also not sure if we can avoid those warnings, since it's already triggered by the try to access the JVM internal classes. But we have a PRD to make HZ compatible Java 9, this will be evaluated when it's implemented.

Adding the PID is a completely different issue. @mesutcelik could you have a look, please?

**Comment by mesutcelik** [comment]
@emre-aydin can we add PID to scripts?
