### ISSUE TITLE
Submit a task to a node without involving thread pools

### ISSUE THREAD

**Issue by AndRossi** [hazelcast/hazelcast#11855]
Hi Hazelcast Team, 
First of all thank you for your amazing job. I am using Hazelcast and it is spectacular.

I need one of my cluster nodes to submit Callable objects to other cluster nodes.
This would very easy (i.e. with an IHazelcastExecutor), but I have a big constraint: I should not use thread pools in the target node. What I'd like is to make the target node just spawn a thread, run the Callable in it, get the Future result and finally send it to the original node.

I assume that when I use a IHazelcastExecutor, and it assigns a task to a target node, the target node runs it in a local ExecutorService, so I guess I can not use it.
 
I looked for a request - response protocol between nodes and I found [this useful closed issue](#15). It seems that it is really easy to request an operation using SPI, so I am considering using an Operation instead of a Callable.
However, looking more closely at the code, it seems that Operations are run in an OperationService, so I guess another thread pool is involved, isn't it?

What do you suggest me to do?

Thank you for your support and thanks again for your wonderful product.

Andrea

**Comment by pveentjer** [comment]
Why do you not want to use a threadpool?

And if you want to have full control and threading, then you can use your own solution if you would make use of an IQueue. Either you make a global IQueue shared by all nodes, or a IQueue per node (use the hz.cluster.localMember.uuid as name of the queue). And then you can use your own thread(s) for processing these messages.

**Comment by AndRossi** [comment]
Hi @pveentjer, 

Thanks for your answer :)

I have actually several reasons why I did not want to use thread pool:
- my tasks have a priority value so they should be executed in the proper order (Priority was implemented separately from the Hazelcast tasks priority system). The IExecutorService can not handle my tasks taking into account *their* priority, of course.
- I also need to have a limit in the amount of tasks I can accept, to avoid overloading my system. 
The queue of the IExecutorService can not be given a limit (can it?).
- my tasks could take a long time to finish (even though they are not very heavy on the computational side), so I risk to have all my IExecutorService threads (well, the threads of the local ExecutorServices beneath) stuck on computationally light activities.

However I have these problems by implementing my own Hazelcast Service and Operation.
What I do is basically this:
- my Service has a reference to a local Executor (that I have implemented myself) with all the specs I need (priority, queue limit etc). 
- the Operation contains a Callable; during the Operation `run()` method, the Callable is submitted to the local Executor of the Service
- the `run()` method of the Operation immediately returns: it does not wait for the Callable result, so the operation thread is immediately freed;
- the Callable keeps a reference to the Operation and when the task is over it sends the response back using sendResponse();

This way the operation threads just submit their tasks to a local Executor, so they are not stuck executing the tasks themselves. 
Since the local Executor is not depending on the , so I can have the queue size and the task dequeuing policy.

Since I have solved this problem I think I can close this issue.
Thank you again for your great product, it is a really good tool!

Andrea

**Comment by pveentjer** [comment]
The ExecutorConfig has a queueCapacity setting.

How are you going to make sure that your invocation will receive heartbeats for the operation? If an offloaded operation doesn't get heartbeats (and an invocation is used), it will timeout and an OperationTimeoutException is thrown.

**Comment by mmedenjak** [comment]
Glad to hear it worked out and congratulations on implementing your own service and operations! Here are some tips:
- when you offload operation processing, you should register that the operation is still alive but being processed on an another thread. This is done by calling [`OperationServiceImpl#onStartAsyncOperation`](https://github.com/hazelcast/hazelcast/blob/fd97a77216e33b5c65a6374ce57a281d9ff5a717/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationServiceImpl.java#L344-L346) (in the executor thread) and calling [`OperationServiceImpl#onCompletionAsyncOperation`](https://github.com/hazelcast/hazelcast/blob/fd97a77216e33b5c65a6374ce57a281d9ff5a717/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationServiceImpl.java#L348-L350) in a finally block to mark the operation as complete. Without this, the operation heartbeats are not sent (since the operation service does not know that the response is yet to be sent) and if enough operation heartbeats are not sent, the caller may declare the operation timed out
- there is an improvement coming out in 3.10 which will allow you to write operations which offload to a different thread much easily, without all the hassle of registering/deregistering the operation. The SPI is still being worked on so we can't guarantee anything as of yet
As for your use case, hazelcast 3.9 has a very similar use case - some single-key entry processor methods can offload the entry processing if you provide a processor implementing the [Offloadable](https://github.com/hazelcast/hazelcast/blob/ed53d94c62fbd7732f08b1c75cb92444b36ba7ed/hazelcast/src/main/java/com/hazelcast/core/Offloadable.java) interface. You can then take a look at how exactly the processing is offloaded in [EntryOperation#runOffloadedModifyingEntryProcessor](https://github.com/hazelcast/hazelcast/blob/71f0e7bc996a57142b5d4b4bbbfd1975d0c15198/hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperation.java#L223-L269) (ignore the locking since it's not relevant for you and assume the `offloaded` boolean is `true`). Other places that you need to keep in mind are the [`EntryOperation#onExecutionFailure` and `EntryOperation#returnsResponse` methods](https://github.com/hazelcast/hazelcast/blob/71f0e7bc996a57142b5d4b4bbbfd1975d0c15198/hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperation.java#L370-L391) and [`EntryOperation#getResponse`](https://github.com/hazelcast/hazelcast/blob/71f0e7bc996a57142b5d4b4bbbfd1975d0c15198/hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperation.java#L438-L444). Also if your operation does not mutate any hazelcast state, you don't need to implement the `BackupAwareOperation` (`EntryOperation` does).

Again, congratulations for writing your own service and if you are ever thinking of working on open source software, feel free to send us an email at `jobs@hazelcast.com` :)

**Comment by pveentjer** [comment]
The onStartAsyncOperation/onCompletionAsyncOperation will be ripped out in 3.10.

**Comment by AndRossi** [comment]
Hi @pveentjer and @mmedenjak, 

Thanks for these tips!
I actually did not use `OperationServiceImpl#onStartAsyncOperation` and `OperationServiceImpl#onCompletionAsyncOperation`. 
I am definitely going to add them in my implementation!


To make MyService run MyOperation on a specific cluster node, in my MyServiceProxy (implementing AbstractDistributedObject<MyService>) I use a syntax like this:

```java
public Future serve(Callable myCallableTask, Address target) {
    OperationService operationService = getNodeEngine().getOperationService();
    MyOperation myOperation = new MyOperation(myCallableTask);
    return operationService.invokeOnTarget(getServiceName(), myOperation, target);
}
```

and in MyOperation.run() method I do pretty much this:

```java
@Override
public void run() throws Exception {
    MyService myLocalService = getService();
    ExecutorService myLocalExecutor = myLocalService.getExecutor();
    try {
        myLocalExecutor.submit(this.myLocalCallable));
    } catch(Throwable e) {
        submitException = e;
    }
}
```

(and I use the potentially caught `submitException` in my implementations of `returnsResponse()` and `getResponse()`).


Now, if I get it well, in the run() method of MyOperation I need to:
- get a reference to the OperationServiceImpl of the local node
- execute the operationServiceImpl.onStartAsyncOperation() method
- execute the rest of my operation just as it is now
- make myCallableObject call operationServiceImpl.onCompletionAsyncOperation() when it finishes its execution (in a finally clause in the call() method).

Did I get it right?
If I did, how do I obtain a reference to the OperationServiceImpl from inside the body of MyOperation,run()?

Anyway, what do mean that the onStartAsyncOperation/onCompletionAsyncOperation will be ripped out in next release? 
Will it just become deprecated but still be usable, or will I need to change my code to adapt it to the new `Offloadable` interface?

Thank you for your support!

Andrea

**Comment by AndRossi** [comment]
Hi again @pveentjer and @mmedenjak,

I think I managed to understand by myself how to get a reference to a local `OperationServiceImpl`.  

When an Operation performs `getNodeEngine().getOperationService()`, it actually gets a local proxy to the OperationService, which is an OperationServiceImpl: so all I need to do is:

```java
OperationServiceImpl localOSI = (OperationServiceImpl)  getNodeEngine().getOperationService();
```

SIlly me, I was a bit misled by the fact that `getOperationService()` does not return an `OperationServiceImpl`, but an `OperationService`. 
In all the examples of Services I studied, an `XServiceImpl` (or `XServiceProxy`) does not implement `XService`, so I took a while to think that `getOperationService()` could actually return an `OperationServiceImpl` object.

However everything seems to work fine now (I actually did not get any timeout without using `onStartAsyncOperation` and `onCompletionAsyncOperation` either, but I guess i was just lucky).

Thank you again for your support and advices.
Have a nice day!

Andrea

**Comment by mmedenjak** [comment]
Glad to hear it worked out. As for the `onStartAsyncOperation`/`onCompletionAsyncOperation`, we are still working on finalising the design and the implementation isn't done yet. From the current standpoint, those methods will be removed from the `OperationServiceImpl` and operations will be able to offload processing more seamlessly, without invoking any methods on the operation service. This means that you will need to change your code with hazelcast 3.10.
