### ISSUE TITLE
Better support of ConcurrentMap.computeIfPresent

### ISSUE THREAD

**Issue by taburet** [hazelcast/hazelcast#11958]
The support may be enhanced in at least two aspects:

1. We may try to minimize the number client-server round trips, since the default implementation of `ConcurrentMap.computeIfPresent` executes at least two remote operations, one `get` and one `replace`. We may try to combine them into a single one.

2. Support in-place modification of the value passed to and returned from `remappingFunction`. `BasicMapTest#testComputeIfPresent` must be extended to cover this scenario. See #11816 for more details.

**Comment by ahmetmircik** [comment]
similar issue: https://github.com/hazelcast/hazelcast/issues/12557

**Comment by mmedenjak** [comment]
As much as the in-place behaviour is bad (infinite loop) and the double-roundtrip behaviour performs poorly, I'm thinking of moving this into 4.1 because:
- this can be considered a defect and fixed as a bug
- fixing it does not require breaking compatibility as the behaviour would stay the same or would start conforming to the guarantees
- I would like to constraint the 4.0 scope
- I would like us to address all default methods as a whole and not address methods one-by-one

Alternatively, if time shows that we might squeeze it into 4.0 after all, we can move it back.

**Comment by devozerov** [comment]
Guys, do we have a decision on moving this one to 4.1?

**Comment by mmedenjak** [comment]
Yes, forgot to move it (or was hoping it would spontaneously get solved without anyone spending much time on it :) ). Moving to 4.1.

**Comment by webashutosh** [comment]
Handling this one as part of #14913

**Comment by Holmistr** [comment]
Hi @webashutosh , ok, it makes perfect sense to get them together. Therefore, I'm assigning you this issue :) I will ask somebody to provide you more details on possible solutions if you want.

**Comment by Holmistr** [comment]
@webashutosh I see that this comment https://github.com/hazelcast/hazelcast/issues/14913#issuecomment-582404644 probably covers enough details that you would need. Leaving it to you then :) Feel free to ask any questions (preferably on Gitter). Good luck!

**Comment by mmedenjak** [comment]
Closing as fixed.
