### ISSUE TITLE
Performance regression on predicate queries 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#12018]
Performace of predicate queries are still ~2x slower on (3.9.1 and 3.8.7) than 3.7.x. 
#11705 resolved **most** of the performance degradation. When setting `hazelcast.index.copy.behavior=NEVER`, we expect to get the same performance as 3.7.x. However, it is ~2x slower. I am sharing the screenshot of test results: 

<img width="480" alt="screen shot 2017-12-18 at 13 25 28" src="https://user-images.githubusercontent.com/621261/34102834-9b96ce22-e3fb-11e7-9061-5e3556790716.png">

The tested query includes an `AND` query with 7 indexed fields of a map. 
I can share the code if you need.

**Comment by tombujok** [comment]
Related work: https://github.com/hazelcast/hazelcast/pull/11705

**Comment by taburet** [comment]
@yozank could you please share the code.

**Comment by yozank** [comment]
@taburet shared on Slack

**Comment by mmedenjak** [comment]
@yozank I can't seem to find the code. Can you paste a link to the slack message?

**Comment by yozank** [comment]
@mmedenjak shared on #core as hz_benchmark.zip

**Comment by mmedenjak** [comment]
https://hazelcast.slack.com/files/U6ME08KUY/F8G14GG3A/hz_benchmark.zip

**Comment by taburet** [comment]
After profiling it's clear that on recent Hazelcast versions we are just unable to saturate the CPU fully. On 3.7.2 queries are executed on a common client thread pool, by default thread count is calculated as number of cores multiplied by 20. On more recent versions queries are executed on separate thread pool, by default thread count is calculated as number of cores multiplied by 1.  See `ClientEngineImpl#newClientExecutor` and `ClientEngineImpl#newClientQueryExecutor` for more details.

The workaround is to set `hazelcast.clientengine.query.thread.count` manually to some reasonable number. A possible fix is raising `ClientEngineImpl#QUERY_THREADS_PER_CORE` multiplier while calculating default thread count.

**Comment by mmedenjak** [comment]
@yozank can you confirm this fixes the issue?

**Comment by yozank** [comment]
@mmedenjak yes I confirm that suggested workaround fixes the issue.

**Comment by mmedenjak** [comment]
Discussion on slack: https://hazelcast.slack.com/archives/C8MGBBY3U/p1514987744000166
The regression was introduced because of this: https://github.com/hazelcast/hazelcast/pull/9581
Basically the PR that introduced it avoids OOME and full GCs by lowering the thread count - https://github.com/hazelcast/hazelcast/issues/9568

From the looks of it, it’s preferable to keep the lowered thread count by default to avoid OOME and full GCs and have a configuration to increase the thread count or use a different thread pool in case a client is heavy on the queries and can sustain a high thread count.

As the client can increase the thread count by setting [hazelcast.clientengine.thread.count](https://github.com/hazelcast/hazelcast/blob/44e762839df0e653b72ced89c097501fde70c201/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L97-L104) and [hazelcast.clientengine.query.thread.count](https://github.com/hazelcast/hazelcast/blob/44e762839df0e653b72ced89c097501fde70c201/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L106-L107), I think we don't need to apply any fix.

**Comment by Holmistr** [comment]
@mmedenjak So if I understand it correctly, we don't want to apply any fix, but this should be clearly documented, right?

**Comment by mmedenjak** [comment]
This is how I see it. @sertugkaya @yozank WDYT?

**Comment by sertugkaya** [comment]
Yes, as long as it's clearly documented, all good.

**Comment by Holmistr** [comment]
@Serdaro Can you please take it from here? I will be very happy to assist you if you needed anything.

**Comment by Serdaro** [comment]
@Holmistr, I checked all the mentioned issues/PRs, I'd be glad to get a hand on how to convey the resulting information. It shouldn't be just like "for the 3.8.x and higher releases you should increase thread.count and query.thread.count to a "reasonable" number to not face some decreased performance"

**Comment by mmedenjak** [comment]
I guess it should be something along the lines of:
- changed default thread count to avoid OOME : https://github.com/hazelcast/hazelcast/pull/9581
- if you are experiencing performance regression and can tolerate a higher thread count, increase them by using the 2 properties

**Comment by Serdaro** [comment]
thank you @mmedenjak
