### ISSUE TITLE
HazelcastClient with microservice

### ISSUE THREAD

**Issue by renatojava** [hazelcast/hazelcast#12060]
Hello Guys,

I'm having a problem using the hazelcast in an architecture based on microservice and springboot.
I keep one of the applications with being the application that will be the server of hazelcast and the others are clients of this.
However if I have to update the application that is the hazelcast server, the clients applications of the cache overturn the connection to the server and when I up the new version of the server these client applications do not reconnect.
Is there any off setting the hazelcastclient to be doing pooling on the server to try to reconnect as soon as it comes back?
My client is like below:

 @Bean
    open fun hazelcastInstance(): HazelcastInstance? {
        return try {
            val clientConfig = ClientConfig()
            HazelcastClient.newHazelcastClient(clientConfig)
        } catch (e: Exception) {
            log.error("Could not connect to hazelcast server, server up without cache")
            null
        }
    }
 
and I receive "com.hazelcast.client.HazelcastClientNotActiveException: Client is shutdown" if my server goes down.

I'm grateful if you could help me

**Comment by vbekiaris** [comment]
Since Hazelcast 3.9, [Hazelcast client reconnection strategy](http://docs.hazelcast.org/docs/3.9.1/manual/html-single/index.html#configuring-client-connection-strategy) can be configured to suit your needs.

Please use the [the google group](https://groups.google.com/forum/#!forum/hazelcast) for questions and troubleshooting help, github issues should be used to track bugs or feature requests.
