### ISSUE TITLE
Make sure that none of the MergeOperations implement MutatingOperation

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#12088]
David, please make sure that none of the MergeOperations in the codebase implement `MutatingOperation` after you finish the MergePolicies PRD. Thx a lot!

**Comment by Donnerbart** [comment]
Hmm, maybe that could be an issue on the ones, which extend existing base operations. I have to check that.

What about backup merge operations? Here I'm re-using existing backup operations where possible, have to check if those have the same issue.

A short explanation after the next standup would be nice, so I can see how a proper solution might have to look in terms of inheritance.

**Comment by mmedenjak** [comment]
The idea that we should try and achieve is that internal operations (synchronization operations, merge operations, migrations, backup operations, ...) should be allowed while user-initiated operations should be checked for quorum. Otherwise we could lead the system in a inconsistent state (e.g. change was applied to primary but not to backup replica, you cannot add a new member because migration operations are rejected, ...).
I grant you this might be easier said than done but this is the general idea.

**Comment by tombujok** [comment]
I already fixed IMap and ICache. Backup operations, even-though they implement MutatingOperations, are fine since they bypass quorum in the OperationBackupHandler, so it's just a syntactic sugar in their case. But it would be ideal if they didn't implement MutatingOperation either. It ads to the confusion...
