### ISSUE TITLE
Consider split brain merging keyless data structures

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#12194]
When merging keyless data structures which are also containers for items (list, set, ringbuffer, queue), currently the entries which are equal by value are merged:
https://github.com/hazelcast/hazelcast/blob/73b8a3bf56579641554ba975bbc8224cb056ede7/hazelcast/src/main/java/com/hazelcast/collection/impl/collection/CollectionContainer.java#L351-L358

An another approach could be merging entries with the same index or with the same identifier, regardless of their value. See discussion: https://github.com/hazelcast/hazelcast/pull/11677#discussion_r162938952

The final approach should be decided and if we decide to go with merging entries with the same id/sequence, the code should be updated.

Affects:
https://github.com/hazelcast/hazelcast/pull/11677
https://github.com/hazelcast/hazelcast/pull/11752
https://github.com/hazelcast/hazelcast/pull/11749

**Comment by Donnerbart** [comment]
I am in favor of merging via value for the following reasons:
* The Ringbuffer index and item ID of the collections are used for a correlation between primary and backups. This assumes that no duplicate indexes or IDs exist for a data structure in the cluster. During a split-brain this assumption is easily violated, when two sub-clusters add a different value to the same collection. Then the same identifier is used, but the values have no correlation. This is a difference to a user chosen key in a map or cache. Here the user defines the correlation. In a collection it's an internal constraint to deal with backups.
* Even the exactly same changes on two sub-clusters could be processed in different orders (just a single operation needs to be delayed due to a GC collection). An index based merging would lead to an unexpected results in this case, since even the order correlation is broken.
* The index or item ID are implementation details, unknown to most users. The public API of those data structures don't have any index based methods, also Set has no ordering guarantees. So it feels unnatural to use them for merging. It implies that the order is important for the merging, not the content of a data structure. But all methods known to the user are about the content, e.g. `contains(Object)`. So it seems logical that a `PutIfAbsentMergePolicy` searches for the same value, not for something which is stored at the same position in the underlying data structure.

So from my understanding the purpose of the index and item ID doesn't fit to a split-brain scenario at all. The duplication of those unique identifiers during a split-brain makes them unusable to resolve merge conflicts.

**Comment by mmedenjak** [comment]
Decided to keep the value-based merge functionality. This can also be changed at a later point.
