### ISSUE TITLE
Data structures dynamic configuration feature is supported in 3.9, but there is no way to re-configure data structures at runtime.

### ISSUE THREAD

**Issue by Mak-Sym** [hazelcast/hazelcast#12218]
This discussion was started on https://github.com/hazelcast/hazelcast/pull/12073, but it is out of scope for initial pull request, so I decided to create separate issue for that.

In Hazelcast 3.9, [dynamic map configuration](http://docs.hazelcast.org/docs/latest/manual/html-single/#dynamically-adding-data-structure-configuration-on-a-cluster) feature was introduced. It allows dynamically add configuration for certain data structures, like maps and caches, at runtime. However, once data structure is configured, its re-configuration is not allowed at runtime.

At the same time, (despite it's not supported officially), Hazelcast implementation prior v. 3.9 actually allows to create and change map configs dynamically and distribute them among cluster nodes (please have a look at [this example](https://github.com/Mak-Sym/hazelcast/commit/ffe7a96f05638b9aed944390841ae697ff382ced), which I created in my 3.8.6. branch - I added bunch of comments, which explain how it works).

From original conversation with @mmedenjak :
 > Regarding map reconfiguration, there are no plans of adding it any time soon. This may work for the simplest cases but is wildly complex for non-trivial cases such as (but not limited to):
 > 
 >  - if the object format changes
 >  - if the cluster is performing rolling upgrade and some members don't support the new configuration
 >  - if the map store configuration changes from write-behind to write-through and to a different store
 > and so on...

I may be wrong, but all cases from list above should be taken into account for existent dynamic configuration, so from implementation point of view, dynamic re-configuration is not very different from dynamic configuration.
It would be great if dynamic re-configuration of data structures is implemented in future releases, as it can be extremely useful for the cache clients.

Thank you in advance,
-Maks.

**Comment by Donnerbart** [comment]
If I remember correctly it was one of the main constraints for the dynamic configuration feature, that it doesn't touch existing configurations. As Matko already explained, runtime changes of most configuration parameters are not possible at the moment.

If I read your example code correctly, it may change the `MapConfig` in the `Config` instance successfully. But that may just have no effect or might break things, depending on when the map container is created on a node. The configuration of a data structure is normally read once, when the container is created, e.g. for the map:
```java
    public MapContainer(final String name, final Config config, final MapServiceContext mapServiceContext) {
        this.name = name;
        this.mapConfig = config.findMapConfig(name);
        (...)
```
If you swap the configuration in the `Config` instance after that, it should have no effect. And if you manage to get the containers created with a different configuration, Hazelcast may just crash (e.g. different in-memory format on different nodes).

The dynamic configuration checks very carefully, that no existing configurations are changed and that the dynamic configurations are the same everywhere. I don't see any easy solution for your request, since there are very limited possibilities to generally change configuration parameters, once a container has been created.

Of course the map has an exception to this rule. You can change a very limited number of configuration parameters during runtime via the Management Center: http://docs.hazelcast.org/docs/management-center/3.9.1/manual/html/Managing_Maps.html#page_Map+Config
But this is explicitly implemented for exactly those parameters, nothing else. Other changes might just be ignored (since they are not read from the map config all the time) or might crash Hazelcast, since there would be an inconsistent configuration within the node or the cluster.

So I think this will always be a specialized solution for a very limited use case. A generalized approach would be a huge implementation effort.

**Comment by mmedenjak** [comment]
I agree with @Donnerbart . You may still approach dynamic reconfiguration the way you did (e.g. running a task on each member which will use private API and go through all of the `MapContainer`s and update it's configuration). There is a key difference between dynamic configuration and dynamic reconfiguration - in dynamic configuration the config is not yet being used.
For dynamic reconfiguration we would need to implement logic for each separate changed property:
- if the in memory format is changed -> create new record stores and migrate all of the data to new record stores
- if the backup count is changed -> send a operation to create or destroy a map replica
- if the map store is changed -> flush data in the map store and recreate a new map store

And all of this concurrently while the map is being updated by the user, new members are joining, possibly with an older version that does not support this feature and the map data is being migrated because of repartitioning.

It is possible though but I would approach this by implementing dynamic reconfiguration for a specific property, one by one, as the need arises. Please open a new issue specific to the property you would like to reconfigure at runtime and we will take it from there.

**Comment by Mak-Sym** [comment]
Thank you for detailed and clear explanation.

@Donnerbart you mentioned in your comment, that some parameters of ```IMap```s (like max size etc.) [can be already changed at runtime](http://docs.hazelcast.org/docs/management-center/3.9.1/manual/html/Managing_Maps.html#page_Map+Config). Is if available in open source edition, or is this an enterprise offering only?

**Comment by Donnerbart** [comment]
The code should all be available in HZ OS. The MC just has the limitation of 2 nodes in the free version. But of course you can have a look at the HZ code to see how it's implemented.

**Comment by Mak-Sym** [comment]
Thank you
