### ISSUE TITLE
map max size per node not enforced under member loss via kill -9 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12414]
after one of the members is killed we see that the map is bigger than the max allowed size permitted by the xml configuration.

max size bigger that configured maximum after member kill -9

job
https://hazelcast-l337.ci.cloudbees.com/view/kill/job/kill-All/33/console

disk local
/disk1/jenkins/workspace/kill-All/3.10-SNAPSHOT/2018_02_21-15_05_39/stable/map/max Failed

error
```
fail HzClient3HZ _map-max_mapValidate hzcmd.map.SizePerMember threadId=0 global.AssertionException: map mapBak1_MaxSize_PER_NODE_1000_map-max size 3794 > 3300(size 1100 * memberCount 3) 
```

web
http://54.82.84.143/~jenkins/workspace/kill-All/3.10-SNAPSHOT/2018_02_21-15_05_39/stable/map/max

config
```
   <map name="mapBak1_MaxSize_PER_NODE_1000*">
        <max-size policy="PER_NODE">1000</max-size>
        <eviction-policy>LFU</eviction-policy>
        <in-memory-format>BINARY</in-memory-format>
        <backup-count>1</backup-count>
        <hot-restart enabled="false">
            <fsync>false</fsync>
        </hot-restart>
    </map>
```

**Comment by ahmetmircik** [comment]
@Danny-Hazelcast i believe the reason is promoted backups. During promotion we are not doing any eviction. Since promoted backup data is already on the same node, no OOME can be seen. And eventually map will go down to the desired size with later puts. This explanation is for tests by killing members.

But if we test with graceful shutdown instead of kill, OOME can be seen due to the transferred data to remaining nodes. Because replication operations don't do eviction and this can be a reason for OOME. This can be seen with all max size policies not specific to PER_NODE.

**Comment by Danny-Hazelcast** [comment]
@ahmetmircik, yes ther is no OOME,  
the issue is that the max size policy is not enforced when a member is killed.
as a fix,  during back promotion we could enforce the max size policy so that we do not violate the max size policy that the user wishes to enforce on the configured map

**Comment by Danny-Hazelcast** [comment]
@ahmetmircik 

we have the same issue in the member shutdown version of the test

https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-x/52/console

/disk1/jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_02_22-19_00_14/max Failed

`fail HzClient1HZ _map-max_mapValidate hzcmd.map.SizePerMember threadId=0 global.AssertionException: map mapBak1_MaxSize_PER_NODE_1000_map-max size 3794 > 3300(size 1100 * memberCount 3)`

http://54.82.84.143/~jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_02_22-19_00_14/max


```
/disk1/jenkins/hzCmd-bench/lab/hz/functions/shutDown Done
fail HzClient1HZ _map-max_mapValidate hzcmd.map.SizePerMember threadId=0 global.AssertionException: map mapBak1_MaxSize_PER_NODE_1000_map-max size 3794 > 3300(size 1100 * memberCount 3) 
```

the data 
http://54.82.84.143/~jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_02_22-19_00_14/max/output/HZ/

**Comment by ahmetmircik** [comment]
we'r using this equation when translating per-node-size to partition-size:
 `max-record-store-size = per-node-max-size * member-count / partition-count`

According to this, if only one member stays alive after shut-down of other nodes, that member should have enough space to have `max-record-store-size * partition-count` entries. Assertion should check whether current map-size exceeds the result of `max-record-store-size * partition-count` or not.

For the test above,  `max-record-store-size = 14.7` which is the result of  (`1000 * 4 / 271`). This means a node should have enough space for `271 * 14.7 = 3983.7` entries. Seems tests' finding is expected and only assertion part needs a fix.

But you are right that this is counter-intuitive(because you set 1000 per-node but it became 3983) but given that we [documented](http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#map-eviction) it before, for now, this unmatched expectation is ok. Maybe adding some further documentation can be enough as a fix now.

**Comment by Danny-Hazelcast** [comment]
ok a bigger max size check worked
