### ISSUE TITLE
PartitionLostListener behaviour is incorrect

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#12541]
Hi,

according to PartitionLostEvent#getLostBackupCount's JavaDoc:

>  If all replicas of a partition is lost, {@link InternalPartition#MAX_BACKUP_COUNT} is returned.

Consider following code:
```
import java.io.Serializable;

import com.hazelcast.config.*;
import com.hazelcast.core.*;
import com.hazelcast.nio.*;
import com.hazelcast.nio.serialization.DataSerializable;
import com.hazelcast.partition.*;
import org.slf4j.*;

public final class PartitionLostListenerReproduction {

	private static final String MAP_NAME = "Integers";
	private static final Logger log = LoggerFactory.getLogger(PartitionLostListenerReproduction.class);

	private PartitionLostListenerReproduction() {}

	private static class CustomPartitionLostListener implements PartitionLostListener, Serializable, DataSerializable {
		Logger internalLog = LoggerFactory.getLogger(CustomPartitionLostListener.class);
		@Override
		public void partitionLost(PartitionLostEvent event) {
			internalLog.error("partition lost {}, lost backup count: {}", event.getPartitionId(), event.getLostBackupCount());
		}
		@Override
		public void writeData(ObjectDataOutput out) {}
		@Override
		public void readData(ObjectDataInput in) {}
	}

	public static void main(String[] args) throws InterruptedException {
		Config conf = new Config();
		conf.setProperty("hazelcast.logging.type", "slf4j");
		conf.setProperty("hazelcast.partition.count", "3");
		conf.addMapConfig(new MapConfig(MAP_NAME).setBackupCount(1).setReadBackupData(true));
		boolean liteMember = args.length != 0;
		conf.setLiteMember(liteMember);
		HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance(conf);
		hazelcast.getPartitionService().addPartitionLostListener(new CustomPartitionLostListener());

		if (liteMember) {
			IMap<String, Integer> map = hazelcast.getMap(MAP_NAME);
			for (int i = 0; i < 700000; i++) {
				map.put(String.valueOf(i), i);
			}

			while(true) {
				Thread.sleep(3000L);
				log.info("map size: {}", map.size());
			}
		}
		
	}
}
```

I've launched 4 nodes, the last one has an argument, so it's a lite member that inserts data and checks size of the map.

When I shutdown 2 nodes in   short period of time, expected behaviour is that 6 will be logged as the lostBackupCount. However, I see in logs:

> 14:14:07,210 ERROR [_hzInstance_1_dev.event-3] PartitionLostListenerReproduction$CustomPartitionLostListener - partition lost 2, lost backup count: 0
> 14:14:07,211 ERROR [_hzInstance_1_dev.event-1] PartitionLostListenerReproduction$CustomPartitionLostListener - partition lost 0, lost backup count: 1
> 14:14:07,350 INFO  [main] PartitionLostListenerReproduction - map size: 466572

So data was lost, but partition lost listener shows that only backup was lost. Is that an expected behaviour? Probably docs should be changed if this is ok, because now it confuses users.

**Comment by tkountis** [comment]
@TomaszGaweda you are right. Documentation is not 100% correct here, and will improve it. Behavior however is correct. When you get partition lost event, the `lostBackupCount` represents a zero-based index of how many partitions you lost. (0 = Master, 1 = Master + 1st Backup, etc). So if your bacup-count is set to 1, then a `lostBackupCount == 1` means data is lost. However, there is one more type of event, which is triggered from a different failure flow, which due to the unknown of the backup-count (for each service), it returns `MAX_BACKUP_COUNT`. So if you ever wont to know if a partition was totally lost, then your evaluation expression should be with a greater-than operator. eg. `lostBackupCount >= configuredBackupCount`. Hope that makes it a bit more digestible, and will make sure to follow up with this in the docs.

**Comment by mmedenjak** [comment]
Moving to 3.10.1
