### ISSUE TITLE
Intermittently failing MapIndexLifecycleTest

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#12597]
com.hazelcast.map.MapIndexLifecycleTest.whenIndexConfigured_existsOnAllMembers

**Stacktrace**
```
java.lang.AssertionError: Year index should contain records
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.MapIndexLifecycleTest.assertGlobalIndexesAreInitialized(MapIndexLifecycleTest.java:181)
	at com.hazelcast.map.MapIndexLifecycleTest.whenIndexConfigured_existsOnAllMembers(MapIndexLifecycleTest.java:116)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14376/testReport/junit/com.hazelcast.map/MapIndexLifecycleTest/whenIndexConfigured_existsOnAllMembers/

**Standard Output** 
[test.log](https://github.com/hazelcast/hazelcast/files/1811535/test.log)

**Comment by vbekiaris** [comment]
The failure is due to the assertion being applied before migrations have been completed -> index was not yet populated with data:
- log indicates `12:19:16,744  INFO ...Re-partitioning cluster data... Migration queue size: 4` but migration queues are only logged to be empty after members have been terminated (=test has already failed): 
```
12:19:17,764  WARN |whenIndexConfigured_existsOnAllMembers| ...Terminating forcefully...
12:19:17,771  INFO ... All migration tasks have been completed, queues are empty.
```
- Running locally the test in isolation thousands of times didn't fail -> the failure manifests as an artifact of migrations being slowed down due to parallel execution
- Running the test 1000 times on the PR builder with `assertTrueEventually` on the `year` index (like we do for the `author` index) instead of `assertTrue` didn't fail

Fixed in #12604
