### ISSUE TITLE
MapStore.LoadAll doesn't load all keys at same time

### ISSUE THREAD

**Issue by ozaydinb** [hazelcast/hazelcast#12712]
Hi,
MapStore.LoadAllKeys returns all key that I wanted to load from database (it returns about 500 key) but LoadAll method doesn't invoke for all key at same time and this approach causes too many db calls. May I force LoadAll method to load all keys at same time?

**Comment by blazember** [comment]
Hi @ozaydinb,
The keys for which the values to be loaded are distributed between the partitions. Each partition loads the values that belong to them via dedicated DB calls. This can be seen as too many DB calls with such small keysets, and currently, there is no option to reduce the number of DB calls to 1 - apart from changing the partition size to 1. Please consult [Data Partitioning](http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#data-partitioning) and [Initializing Map on Startup](http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#initializing-map-on-startup) sections in the docs that describe this in detail.

[Batch loading per partition instead of per member](https://github.com/hazelcast/hazelcast/issues/12716) would decrease the number of the DB calls in your case. That issue is not scheduled yet though.

If you have a bigger keyset, you can influence the number of the DB calls by tuning `hazelcast.map.load.chunk.size` (default is 1000, see the [docs](http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#system-properties)). 

Closing this issue with the answer above.
