### ISSUE TITLE
Can I access cluster 3.10 using java client 3.9?

### ISSUE THREAD

**Issue by smartbruce** [hazelcast/hazelcast#13015]
Hazelcast cluster version is 3.10, can I access the cluster with java client 3.9?  The java client seems  to be dependent on the 3.9 version.

**Comment by vbekiaris** [comment]
@smartbruce Hazelcast client 3.9 can connect to and operate with a Hazelcast cluster of version 3.10. Since Hazelcast 3.6, Hazelcast clients communicate with the cluster over a binary protocol that ensures compatibility (see also https://hazelcast.org/clients-languages/compatibility-matrix/). You are welcome to ask further questions on [gitter](https://gitter.im/hazelcast/hazelcast) or the [Hazelcast google group](https://groups.google.com/forum/#!forum/hazelcast), github issues should be used for reporting issues or enhancement requests. If you feel you did identify an issue with Hazelcast, please feel free to reopen this issue and post your findings.
