### ISSUE TITLE
How to set up hazelcast cluster in openshift such that external clients can connect to it.

### ISSUE THREAD

**Issue by rimogitz** [hazelcast/hazelcast#13045]
How to set up hazelcast cluster in openshift such that external clients can connect to it.

**Comment by mmedenjak** [comment]
@mesutcelik @leszko any comments on this?

**Comment by leszko** [comment]
@rimogitz Please read [1] and [2]. In general, you need to create a Load Balancer service with externalIP and use Dumb Client (Smart Client is not supported). Depending on your use case, the other option is to expose each POD separately with an external IP (though I haven't tried it, since it's not a generic solution). 

[1] https://github.com/hazelcast/hazelcast-openshift#hazelcast-client
[2] https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift#external-hazelcast-client

**Comment by mesutcelik** [comment]
Hi @rimogitz ,
I hope what @leszko recommended worked for you. 
please follow-up smart client related issue here: https://github.com/hazelcast/hazelcast-kubernetes/issues/77
