### ISSUE TITLE
Intermittent failure ClientReplicatedMapQuorumReadTest

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#13097]
The `com.hazelcast.client.quorum.replicatedmap.ClientReplicatedMapQuorumReadTest` tests fail intermittently on PR builder:
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15598/testReport/junit/com.hazelcast.client.quorum.replicatedmap/ClientReplicatedMapQuorumReadTest/

**Stacktrace**
```
java.lang.AssertionError: CountDownLatch failed to complete within 30 seconds, count left: 6
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1131)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:1116)
	at com.hazelcast.quorum.PartitionedCluster.splitFiveMembersThreeAndTwo(PartitionedCluster.java:95)
	at com.hazelcast.quorum.AbstractQuorumTest.initCluster(AbstractQuorumTest.java:267)
	at com.hazelcast.quorum.AbstractQuorumTest.initTestEnvironment(AbstractQuorumTest.java:104)
	at com.hazelcast.client.quorum.replicatedmap.ClientReplicatedMapQuorumReadTest.setUp(ClientReplicatedMapQuorumReadTest.java:44)
```

**Comment by sancar** [comment]
I have added core label because test failure seem to occur on  preparation phase. Members do not split expectedly and client side never really started working.

**Comment by Donnerbart** [comment]
I have at least one optimization for this, since Jenkins just shows the NPE from the `@AfterClass` phase, because the `clients` are still `null`. We should also shutdown the clients before the cluster.

**Comment by Holmistr** [comment]
@Donnerbart Should we consider your NPE protect PR as a fix?

**Comment by kwart** [comment]
AFAIK, David's PR doesn't solve the original problem. It should avoid problem multiplication.

The `@AfterClass` is (also) executed when `@BeforeClass` fails. The PR avoids additional failures in the `@AfterClass`, but it doesn't resolve the root cause in the `@BeforeClass`.

**Comment by Donnerbart** [comment]
Exactly, it's just to prevent the follow up NPE and in general shutdown client before members (to not spam logs with reconnect attempts).

**Comment by taburet** [comment]
I have found the root cause:

1. 5-member cluster is created in the test: [1, 2, 3, 4, 5].

2. Then the attempt to split the cluster is made, the expected configuration after the split should look like this: [1, 2, 3] + [4, 5].

3. The splitting is achieved by blocking the communication between the future sub-clusters and by making the members from the first one to suspect the members from the second one, and wise versa.

4. At some point member 4 notices that all the members to the left of it are suspected, starts the mastership claim procedure and sends the mastership acquisition request to member 5.

5. In theory, member 5 should immediately accept the mastership of member 4 since all the members to the left of the new master (member 4) should be also suspected by member 5.

6. But blocking the communication between member 3 and member 5 doesn't imply that all the operations associated with member 3  and enqueued on the thread pools of member 5 are finished. So member 5 processes a phantom heartbeat from member 3 and stops suspecting it just before member 4 starts claiming its mastership.

7. Member 5 thinks that member 4 is trying to play some dirty tricks and declines the mastership request from member 4.

8. Member 4 tries to repeat its mastership requests until member 5 starts suspecting member 3 again because of the heartbeat timeout, but the test timeout hits first.

I see 3 possible solutions here:

1. Just increase the timeout to some multiple of the heartbeat timeout, but, in theory, the test still may fail.

2. Ensure that all the operations are done after blocking the connection by issuing some kind of a barrier operation for all of threads on each member thread pool, but looks like this will be tricky to implement.

3. Another option is to just ignore the heartbeats from the blocked members, but this also looks tricky since only `FirewallingConnectionManager` knows about the blocked addresses.
