### ISSUE TITLE
ClassCastException operationservice ErrorResponse cannot be cast to Integer

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13566]
https://hazelcast-l337.ci.cloudbees.com/view/wan/job/wan-rollup-val/9/console

http://54.82.84.143/~jenkins/workspace/wan-rollup-val/3.11-SNAPSHOT/2018_08_13-10_32_19/rollup-val

/disk1/jenkins/workspace/wan-rollup-val/3.11-SNAPSHOT/2018_08_13-10_32_19/rollup-val

```
java.lang.ClassCastException: com.hazelcast.spi.impl.operationservice.impl.responses.ErrorResponse cannot be cast to java.lang.Integer
	at com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:695)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:105)
	at hzcmd.map.validate.Size.timeStep(Size.java:12)
```

only found "ClassCastException" in logs of B cluster.  after it rolled up to 3.10.4, 

```
HzMember3B Started on 10.0.0.37 2996@ip-10-0-0-37 /home/ec2-user/hz-root/hz-lib/3.10 
17:43:38 HzMember2B Started on 10.0.0.216 3037@ip-10-0-0-216 /home/ec2-user/hz-root/hz-lib/3.10 
17:43:39 HzMember1B Started on 10.0.0.207 3035@ip-10-0-0-207 /home/ec2-user/hz-root/hz-lib/3.10 
```

**Comment by blazember** [comment]
The actual error was caused by the linked #2306. The map could not be created due to that, leading to responding with an `ErrorResponse` that doesn't not cast to `Integer` in the map proxy. 

The issue here is that the `ErrorResponse` is not handled properly by `MapProxySupport`. This should not be closed together with the linked one despite that the two error disappeared the same time.

**Comment by Danny-Hazelcast** [comment]
have not seen this issue over past year
