### ISSUE TITLE
Unneeded iterations and object creation in bulk response decoders of client-side proxies

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#13590]
This causes lots of garbage object creation and latency.

As an example from `MapEntrySetCodec.decodeResponse(response)`:

```
public static MapEntrySetCodec.ResponseParameters decodeResponse(ClientMessage clientMessage) {
        MapEntrySetCodec.ResponseParameters parameters = new MapEntrySetCodec.ResponseParameters();
        List<Entry<Data, Data>> response = null;
        int response_size = clientMessage.getInt();
        response = new ArrayList(response_size);

        for(int response_index = 0; response_index < response_size; ++response_index) {
            Data response_item_key = clientMessage.getData();
            Data response_item_val = clientMessage.getData();
            Entry<Data, Data> response_item = new SimpleEntry(response_item_key, response_item_val);
            response.add(response_item);
        }

        parameters.response = response;
        return parameters;
    }
```

Above for loop and `SimpleEntry` creation can be removed. Because, mostly, code in the following lines after decode-response step is also iterating over the decoded-response again in order to prepare an object to return the user.

see [ClientMapProxy#entrySet](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java#L1134), [ClientMapProxy#values](https://github.com/hazelcast/hazelcast/blob/c0331ede2c5d832e2b16e5cb7c60e5ae45f0c7fc/hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java#L1126), [ClientMapProxy#keySet](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java#L1150)

**Comment by pveentjer** [comment]
If we create litter for no good reason, we should optimize the code. So good work @ahmetmircik spotting this.

**Comment by sancar** [comment]
Fixing this with the same idea as https://github.com/hazelcast/hazelcast/pull/13784 breaks extendibility of the protocol. 
When we return lists sets lazily, adding new fields are not possible. 
This is discussed and one solution is to add size information for the structures that can be created lazily. That way whole structure can be skipped and remaining extended fields can be read without iteration penalty. And the lazy key set/value list/entry set can keep a client message that shares the internal byte array to read whenever necessary lazily. 
Adding size means breaking protocol so this issue is postponed to 4.0 

When an alternative solution is to make the optimization today. The idea is here to rely on the fact that these responses will not be extended anytime soon. Because when they need to be extended, we have to remove the optimization. We are not pursuing this method now. Depending on plans of 4.0, we may revisit this idea.

**Comment by mdumandag** [comment]
Most of these methods are made lazy in #16188 and #16304. There are a few remaining ones that cannot be made lazy by nature like `map#getAll`, `queue#drainTo` and `queue#toArray`. After some discussion within the team, we decided not to introduce the solution in #16138 for the remaining ones since 
- making it requires changes also in the parts that are made lazy
- this could introduce a performance penalty for the already lazy methods(calling a consumer to add data objects to a list vs adding data object directly to a list) . 

So, I am closing this issue.
