### ISSUE TITLE
Do not collect stats if statistics are disabled by config

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#13693]
Affected:
- `com.hazelcast.config.PNCounterConfig#isStatisticsEnabled`
- `com.hazelcast.config.ReliableTopicConfig#isStatisticsEnabled`

Stats are collected regardless of the config and the config only affects if they are sent to mancenter (in `com.hazelcast.internal.management.TimedMemberStateFactory`). If the stats are disabled, they should probably not be collected at all.

**Comment by galibey** [comment]
It seems like we should remain this as is. Currently, the statistic's collection cost only 1-2 volatile writes per operation. But if we want to check if the statistic is enabled we will have to lookup the configuration by name every time for every operation. The lookup is much more expensive for CPU than a few volatile writes. And we can't get the config once and hold it because it can be dynamically overrideden.
So, from my point of view, we will win nothing functionally but will lose in performance.

**Comment by mmedenjak** [comment]
> And we can't get the config once and hold it because it can be dynamically overridden.
Not sure what you mean by this. Existing config can't be changed. You can only add new configs. Maybe we're talking about different things, though. 

Overall, you're right. The added complexity is not worth the fix. Closing. Feel free to ping me about the dynamic config.
