### ISSUE TITLE
REST API requires that the URL always end with a slash

### ISSUE THREAD

**Issue by arun-shankar** [hazelcast/hazelcast#13938]
To reproduce this issue, run an application that uses Hazelcast and run the following curl command (change the hostname, port and map name as needed):
`curl -v -X GET http://localhost:5701/hazelcast/rest/maps/spring:session:sessions`

and see the following:
```
com.hazelcast.nio.tcp.TcpIpAcceptor      --- [999.999.999.999]:5701 [dev] [3.10.5] Accepting socket connection from /0:0:0:0:0:0:0:1:55057
c.h.nio.tcp.TcpIpConnectionManager       --- [999.999.999.999]:5701 [dev] [3.10.5] Established socket connection between /0:0:0:0:0:0:0:1:5701 and /0:0:0:0:0:0:0:1:55057
c.h.i.ascii.TextCommandServiceImpl       --- [999.999.999.999]:5701 [dev] [3.10.5] String index out of range: -22

java.lang.StringIndexOutOfBoundsException: String index out of range: -22
	at java.lang.String.substring(String.java:1955)
	at com.hazelcast.internal.ascii.rest.HttpGetCommandProcessor.handleMap(HttpGetCommandProcessor.java:163)
	at com.hazelcast.internal.ascii.rest.HttpGetCommandProcessor.handle(HttpGetCommandProcessor.java:52)
	at com.hazelcast.internal.ascii.rest.HttpGetCommandProcessor.handle(HttpGetCommandProcessor.java:34)
	at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:372)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

If you append a slash at the end of the URL in the curl command this Exception does not happen. Hazelcast version is 3.10.5 Java 8. One member in Hazelcast cluster.

**Comment by SaitTalhaNisanci** [comment]
As explained in https://docs.hazelcast.org/docs/latest-development/manual/html/Other_Client_and_Language_Implementations/REST_Client.html, your request URL should be in the form `http://member IP address:port/hazelcast/rest/maps/mapName/key`.  Since this form is expected `mapName`  will be until the last `/`. As you dont have the last `/`  map name cannot be extracted from the url which results in exception. Probably a bad request should be returned in this case instead of the exception.

As for the REST API, it actually requires that it doesnt end with `/`. For example to do an HTTP POST request:
```
curl -v -X POST -H "Content-Type: text/plain" -d "bar" http://localhost:5701/hazelcast/rest/maps/mapName/foo
```

This will put value `bar` to key `foo`. 

```
curl -v -X GET -H "Content-Type: text/plain" http://localhost:5701/hazelcast/rest/maps/mapName/foo
```

And this will return HTTP OK as `foo` exists.

However I just realized that the following request:
```
curl -v -X POST -H "Content-Type: text/plain" -d "bar" http://localhost:5701/hazelcast/rest/maps/mapName/foo/
```

puts value `bar` to key `foo/` instead of `foo` and I think this is not the expected behavior.

**Comment by Holmistr** [comment]
Hey @arun-shankar , thanks for reporting this and sorry for quite outdated comment. This actually looks quite easy to fix. Just a question, would you be interested in implementing it yourself and contributing it to Hazelcast? I would be happy to point you to the specific places and guide with the fix. WDYT?

**Comment by mmedenjak** [comment]
As @SaitTalhaNisanci mentioned, the issue is that you are missing the key in the URL. The only enhancement I can see here then is removing the trailing slash in case both map name and key are specified.

**Comment by ryanlindeborg** [comment]
I'd love to take this issue.

**Comment by ryanlindeborg** [comment]
I'd love to take this issue.

**Comment by Holmistr** [comment]
@ryanlindeborg Glad to hear that! And it's yours! :) As we discussed, I have already provided you several pointers to start with. Feel free to ask more questions if needed, preferably through Gitter. Looking forward to your contribution!

**Comment by Holmistr** [comment]
Hi @ryanlindeborg , just checking in - is there anything we can help you out with? I see that you're actually making progress in your fork. I just want to make sure that you're not stuck on something and just afraid to ask :)

**Comment by ryanlindeborg** [comment]
Hi @Holmistr , I submitted a PR, but looking back it now, I wonder whether I should also be updating HttpGetCommandProcessor.java and HttpDeleteCommandProcessor.java similarly to strip the trailing slash following the key from the handleMap method uri. Do you think I should add that to the PR?

**Comment by mmedenjak** [comment]
Hi @ryanlindeborg ! Thank you for your effort! I've linked the PR to this issue.

Yes, it would be good if you could do a quick check to make sure that no other URI has this issue, not only those related to map.
It may be the case that only some URI's and handlers have this problem, in which case it would be best to fix them all, otherwise we'll get another issue opened at some point.

**Comment by ryanlindeborg** [comment]
@mmedenjak I made a couple updates to the PR, but otherwise, most of the URIs looked okay!
