### ISSUE TITLE
docs: FlakeIdGenerator example

### ISSUE THREAD

**Issue by nlwillia** [hazelcast/hazelcast#14064]
The [doc example](https://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/FlakeIdGenerator.html) for FlakeIdGenerator doesn't compile.

It needs to be `ClientFlakeIdGeneratorConfig` instead of `FlakeIdGeneratorConfig`.

````
        ClientConfig clientConfig = new ClientConfig()
                .addFlakeIdGeneratorConfig(new FlakeIdGeneratorConfig("idGenerator")
                        .setPrefetchCount(10));
````

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/485f9c8980738e89945a201a1d83d5625fb80118

Thank you @nlwillia . By the way, that's an old format of Hazelcast IMDG reference manual with old content. It should have directed you to the new one (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/). Let me check that.

**Comment by nlwillia** [comment]
Thanks.  That's the first Google result for `FlakeIdGenerator`.
