### ISSUE TITLE
DefaultQueryCache unnecessary Extractors creation

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#14191]
Hi,

during DefaultQueryCache.addIndex (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java#L481) we pass Extractors.empty(). That means, each entry has it's own Extractors instance, which leads to higher memory consumption and performance regression, as GettersCache is not reused.

As far as I understand Extractors class, reusing one Extractors per DefaultQueryCache instance should be sufficient

**Comment by gdela** [comment]
Here's a test case that reproduced the issue, it puts 100000 objects into an `IMap` which has a `QueryCache` for all entries, and the query cache has an index. As you can see on the heap dump, there are 100000 instances of the `Extractors` objects, and they are responsible for 90% of memory consumption.

Actually besides the fact that there are unnecerarily large number of extractors, each extrators creates an `EvictableGetterCache`, passing the `Extractors.MAX_CLASSES_IN_CACHE` and `Extractors.MAX_GETTERS_PER_CLASS_IN_CACHE` as the arguments to the `EvictableGetterCache`, which in turn uses them as *initial capacity* values when creating `SampleableConcurrentHashMap` objects.

Is it intentional or not, that the initial capacity is not set to some low value, but instead to those `MAX_..`. values?

[QueryCacheMemoryConsumptionTest.java.txt](https://github.com/hazelcast/hazelcast/files/2625847/QueryCacheMemoryConsumptionTest.java.txt)

![too-many-extractors-heap-dump](https://user-images.githubusercontent.com/4157004/49168397-add57b00-f337-11e8-8fc1-67a1863e3de3.png)

**Comment by gdela** [comment]
Oh, actually it's not the [DefaultQueryCache.addIndex()](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCache.java#L481) method which is responsible for creating the `Extractors` that live long on the heap. It's the [DefaultQueryCacheRecordStore.saveIndex()](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/DefaultQueryCacheRecordStore.java#L101), as can be seen on the following allocation traces:

![extractors-allocation-traces](https://user-images.githubusercontent.com/4157004/49173756-d9ab2d80-f344-11e8-9b2d-f4aaaf503919.png)
