### ISSUE TITLE
`hazelcast-spring` does not cover all options of `hazelcast.xml`

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#14423]
In https://hazelcast.com/schema/spring/hazelcast-spring-3.11.xsd it is not possible to specify config replacers, but this is possible in non-Spring `hazelcast.xml`.

**Comment by burakcelebi** [comment]
We need to update the documentation for feature gaps for server-side and client-side that cannot or will not be addressed. 

For example: 
HZ Config replacer is not available which was not added intentionally. Because Spring has its own - and very powerful - property replacement mechanism. It makes little sense to have another one on top of it.

**Comment by burakcelebi** [comment]
Closing as internal request. Already in the roadmap.
