### ISSUE TITLE
Provide asynchronous, future-based, MapStore / MapLoader [HZ-1179]

### ISSUE THREAD

**Issue by valdo404** [hazelcast/hazelcast#14483]
As MapStore / MapLoader user, I would like to be able to create CompletableFuture-based MapStore andMapLoaders, so that my IO threads are not blocked.

Expected:
```
public interface AsyncMapLoader<K, V> {
    CompletableFuture<V> load(K key);
    Observable<Entry<K, V>> loadAll(Collection<K> keys);
    Observable <K> loadAllKeys();
}
```

That way, we will be waiting for underlying storage instead of blocking on the current thread.

Do you have some questions ?
Thanks ;)

**Comment by ahmetmircik** [comment]
Hi @valdo404, 
How are you using the MapStore/MapLoader api? Target user of this api is Hazelcast itself. Even you have futures returned from the methods, some Hazelcast threads will still block on these futures. Can you please clarify further, maybe i'm missing something?

**Comment by valdo404** [comment]
> Hi @valdo404,
> How are you using the MapStore/MapLoader api? Target user of this api is Hazelcast itself. Even you have futures returned from the methods, some Hazelcast threads will still block on these futures. Can you please clarify further, maybe i'm missing something?

1/ I'm using it to fetch data from some SQL store.
2/ This is documented has a public feature: 
https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#loading-and-storing-persistent-data

That's an hazelcast public feature. Other people are naming it `Read-Through`
https://dzone.com/articles/using-read-through-amp-write-through-in-distribute

Many thanks for your work.

**Comment by ahmetmircik** [comment]
Right it is public api, i was trying to tell the target user of MapStore/MapLoader implementation is Hazelcast itself. You implement it and Hazelcast uses it. 
At which thread you want to do these async calls? Where are your IO threads?

**Comment by valdo404** [comment]
> Right it is public api, i was trying to tell the target user of MapStore/MapLoader implementation is Hazelcast itself. You implement it and Hazelcast uses it.
> At which thread you want to do these async calls? Where are your IO threads?

Kind of. It should be launched inside the IO threads of hazelcast or it should be working on its own, provided, thread pool.
I think it would be more interesting to use a different thread pool for map loader.
Apart from that, I can try to provide an implementation if you are interested.
I would be glad to improve hazelcast internals.

**Comment by burakcelebi** [comment]
@valdo404 This is great :)

**Comment by burakcelebi** [comment]
@valdo404 This is great :) Looking forward to your contribution! We have a concept for community contributions called HEP (Hazelcast Enhancement Proposals):

https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals

It is a simple and a proven procedure for community contribution. If you have any questions, we are always here to help you. cc: @dbrimley

**Comment by avgustinmm** [comment]
Is  there any development here? 

I think such feature for MapLoader would be very useful. The  javadoc for MapLoader says that the load of an entry/entries shall take very short time. It is highly restrictive and you could never ensure that call for DB layer will have no big latency - nevertheless the request is over WAN or not. Basically such synchronous API is not usable unless in very limited cases
It would be much more useful if you really have async MapLoader and provide result (got from DB, rest service, from local or remote sources).
The flow as I imagine it (sorry if it doesn't comply with Hazelcast architecture and concepts, I'm not much into it) is:

1. client queries asynchronously a value from a map (using getAsync)
2. If the value is not available it is requested (asynchronously) from its partition owner 
3. the partition owner request it (asynchronously)  from the AsyncMapLoader

I imaging that there shall be got some locks for the key (in order to prevent concurrent loading) but there will be no need of blocking of thread. 
What do you think?

**Comment by Holmistr** [comment]
Hi @valdo404 @avgustinmm , thanks for your comments!

In 5.2, we have actually reserved time for this and we will finally implement the offloading of the MapLoader operations off the partition thread, so it doesn't block. Hopefully we'll be able to finish this in time for 5.2 release.

Stay tuned!

**Comment by AyberkSorgun** [comment]
Done via https://github.com/hazelcast/hazelcast/pull/21651
