### ISSUE TITLE
Connection with AdvancedNetworkConfig is not denied correctly for some inappropriate endpoint

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14532]
When HZ Member has configured `AdvancedNetworkConfig` and some services try to connect with protocols to inappropriate endpoint then that connection is not denied correctly / gets stuck for some combinations. It happens for:
* Member tries to join (with Member protocol) to WAN endpoint.
* REST client tries to connect to Memcache endpoint.
* HZ Client tries to connect to REST or Memcache endpoint.

It is similar type of issue as was reported in https://github.com/hazelcast/hazelcast/issues/14509

**Comment by olukas** [comment]
FYI, tests in https://github.com/hazelcast/hazelcast/pull/14533 covers this scenarios

**Comment by tkountis** [comment]
@olukas 
- both protocols are the same. they were designed to be the same, so the only difference is that they have separate connection management subsystem. the handshake is however the same. 

Now, for the other two, there might be some improvements we could do. 
- REST & Memcache are also the same from a handling perspective. They are both treated as text, there is no additional effort upon inspecting the bytes to detect one or the other.
- Now, REST & Memcach are text handlers, so they just consume your bytes till a newline and then translate them to a matching command. I am guessing you virtually see this stuck connection because you never send a newline, so each side waits for the other to respond.

**Comment by olukas** [comment]
@tkountis Am I understand it correctly that both mentioned scenarios are basically expected behavior? Whether it it right then this issue can be closed. 

I'm thinking about covering it a little bit it documentation - but they seem quite as a corner cases (all of them are based on inappropriate configuration) and documented them can make documentation confusing and unclear, WDYT?

**Comment by tkountis** [comment]
To fix the 1st scenario we will need to introduce some protocol bytes for the WAN connections. This sounds doable since we know when we run in this advanced setup and it shouldn't break backwards compatibility. I will let @vbekiaris comment on that since he was the mastermind behind WAN.

Regarding the last two points, we could check the 4 first bytes to match them against HTTP, which will help a bit towards validation, but there is not much we can do with Memcached because as a protocol it defines no identifier. Maybe a hack like, check if its another known hz protocol? 

I think documentation is the wrong path here, we will end up confusing users more. There is some more space for input validation so lets keep this open and we can experiment a bit on best approaches.

**Comment by mmedenjak** [comment]
There is no fixing WAN in 3.12 most probably. This is  because right now we are trying to stay compatible and any cluster from 3.8 onwards should be able to connect and send events to any cluster from 3.8 onwards. So right now we're stuck with it being identical to the member protocol. The first time we might be able to change is in 4.0 or maybe when implementing the [WAN protocol](https://hazelcast.atlassian.net/wiki/spaces/PM/pages/184975753/+WAN+Protocol+Implementation) (not 100% sure there).

So the only thing we might do in 3.12 is the "hack" that Thomas was mentioning.

**Comment by mmedenjak** [comment]
Moving to next release as the PR for text protocol was merged and the rest requires breaking changes.

**Comment by tkountis** [comment]
@mmedenjak & @olukas moving back to 3.12.
The fix addresses the majority of the requirements of this issue, apart from the Member <-> WAN scenario, which is a deeper issue that can be solved in the protocol change in 4.0
There is nothing we can do about it in 3.13.

**Comment by tkountis** [comment]
Considering this as closed. Please re-open if you disagree
