### ISSUE TITLE
Fail-fast if max-idle-seconds is set below 2 seconds 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#14697]
As part of hazelcast/pull/13320,  any access to entries within a second will be rounded to 0. 
So, if the entry has 1 second of `max-idle-seconds`, any access will not be counted and it will expire after 1 second. 
It should fail-fast with an explanation if there is a 1-sec `max-idle-seconds` setting.

**Comment by burakcelebi** [comment]
cc: @tkountis

**Comment by tkountis** [comment]
Let me clarify this one a bit more.
Due to the loss of millisecond resolution on the `Record` timestamps (LUT, LAT, LST etc) when you create a record at time=**1s** (no MS info), and access it at wall-clock time **1.1** (includes 100ms) and then at wall-clock time **1.4** (includes 400ms) the timestamps get updated only with the second part of the wall-clock time, i.e., **1s** (no MS info, again). In other words, it behaves as if the record was not touched. 
Therefore, setting a max-idle to 1second will expire the record after 1 second, regardless of operations done on that same record in-between.

A max-idle of 1 second, is fairly unreasonable to have, but nevertheless, we should fail-fast as per @yozank  suggestion, to avoid surprises.

**Comment by mmedenjak** [comment]
Moving to 3.13 as it is not critical to the release. We may fix this once other more important issues are addressed.
