### ISSUE TITLE
[QUESTION] Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [hazelcast/hazelcast#14729]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by Holmistr** [comment]
Hi @gustavosizilio ,

we migrated our Jenkins behind a VPN recently, since we were switching vendors. Currently, you cannot access it from outside. However, we have a plan to create a public instance, which would publish the results for PR builders. But TBH, it's a low priority.

Any particular reason why you ask? :)

**Comment by gustavosizilio** [comment]
Hello @Holmistr, thank you for the answer! The reason for the question is because we are studying open source projects in the university and your project was selected to analysis. One step of the process is separating projects WITH and WITHOUT CI. Thank for your answer,  Im closing this issue.

I appreciate your time!

**Comment by Holmistr** [comment]
@gustavosizilio I see :) In that case, the answer is definitely yes, we relay on it heavily. BTW I would be very much interested in the result of your analysis. Please, drop us a link here afterwards :)
