### ISSUE TITLE
python client fail to create cluster node using hazhalcast service

### ISSUE THREAD

**Issue by vaibhavpatil123** [hazelcast/hazelcast#15023]
Refering example :
https://hazelcast.com/blog/hazelcast-python-client-3-9-introducing-the-python-3-support/

```
config = hazelcast.ClientConfig()
config.network_config.addresses.append('localhost:5701')
client = hazelcast.HazelcastClient(config)
```

Getting below exception

```
  File "C:\Users\vapa1115\AppData\Local\Programs\Python\Python37\lib\site-packages\hazelcast\cluster.py", line 142, in _connect_to_cluster
    raise HazelcastError(error_msg)
hazelcast.exception.HazelcastError: Could not connect to any of {Address(host=localhost, port=5701)} after 2 tries

Process finished with exit code 1
```

Requirement txt file:
hazelcast-python-client

**Comment by vaibhavpatil123** [comment]
_connect_to_cluster failing 
Please provide one running example. we want to run one cluster using python client

**Comment by mmedenjak** [comment]
cc @mdumandag @asimarslan

**Comment by mdumandag** [comment]
Hi @vaibhavpatil123, sorry for the late response. Do you have running Hazelcast cluster before executing the Python script ? I suspect the root of the issue is there is no cluster running to connect to. 

You can start the Hazelcast cluster as described in this link https://github.com/hazelcast/hazelcast-python-client#1211-running-standalone-jars.  After running the Hazelcast cluster, the code snippet you have posted should be able to connect to the cluster. If you have still have problems connecting to the cluster, please fill an issue on the https://github.com/hazelcast/hazelcast-python-client repo with the member and client logs.
