### ISSUE TITLE
Some updates to entries get lost from write behind queue

### ISSUE THREAD

**Issue by gkrs** [hazelcast/hazelcast#15060]
There's a batch of entries, let say in number of 2000.
Big picture is to put initial versions of them the cache (with status field value 'N') and then put updated versions with status set to 'U'.

Coalesced write behind is being used here. The entries have custom ``equals`` and ``hashCode``.

The story is as follows:

- put all entries in the cache
- they are registered in write behind queue with store times 1558097498625 - 1558097498766
- they are stored by write behind, because they all fit in ``StoreWorker``'s ``lastHighestStoreTime``: 1558097499038
- after selecting entries to store, finished store operations are removed from queues
- putting updated versions can be split into two parts:

   - updated entries with store times 1558097498634 - 1558097498650, which are eventually not written to DB
   - updated entries with store times 1558097500278 - 1558097501941, which are stored to DB

What happens in between is additional ``removeFinishedStoreOperationsFromQueues`` invocation which apparently removes the first part of updated entries from being stored. I think that happens because the entries got "old" store times, from the initial batch, which were not timely removed from queue and are now removed during updated batch, because of the custom ``equals``, since using the generic one would indicate different objects.

Could you please take a look? This problem appears in our production code and some entries stored in DB are not current ones. We were unable to write test case which reproduces this issue.

We switched the write-coalescing off, as a workaround. It solved the issue, but affected the overall performance.

**Comment by ahmetmircik** [comment]
Write behind queue compares values by relying on `equals` method. Does updated value equal to previous value after status update?

**Comment by gkrs** [comment]
In short: yes. It is equal.

**Comment by gkrs** [comment]
Similar topis was created on google groups https://groups.google.com/d/topic/hazelcast/arCXp_6j6lw/discussion
The question is if this is an expected behavior and where is it described.

**Comment by mmedenjak** [comment]
Hi @gkrs ! Thank you for the update. We'll take a look if we can clarify the behaviour or if there is some issue that needs to be fixed.

**Comment by vojtechtoman** [comment]
It looks like a concurrency issue when there are updates to `CoalescedWriteBehindQueue` while `StoreWorker` is running. It only occurs if the original and updated versions of entries are `equal()`.
A short summary of what happened in the reported scenario:

```
USER                                     | StoreWorker
----------------------------------------------------------------------------------
add E (store time T) to writeBehindQueue |
                                         | select E from writeBehindQueue
                                         | process E
update E' (coalesced writeBehindQueue    |
           replaces E, keeps time T)     |
                                         | remove E from writeBehindQueue
                                         |          (removes E' which is equal()) 
```
If there are updates to entries in `CoalescedWriteBehindQueue` after `StoreWorker` selects entries to process and before it removes the (processed) entries from the queue, these updates will get lost (because they are `equal()`).

**Comment by vojtechtoman** [comment]
Hi @gkrs, the scenario that I outlined above works only if `E` and its updated version `E'` are stored in the write behind queue as plain objects (that is, not serialized), so that `E.equals()` is used and not byte array comparison (which is the case for serialized representations). The latter would never see `E` and `E'` as equal (unless the version field is transient or you use custom serialization).

Are you, by any chance, using the `MapInterceptor` API? One of the side-effects of applying `MapInterceptor.interceptPut()` is that the objects will be added to the write behind queue in deserialized form (which would make the above scenario work).

**Comment by vojtechtoman** [comment]
Hi @gkrs, can you please confirm if you are using the `MapInterceptor` API? We have a fix for the scenario that I described, but we would like to be sure it works for you, too.

**Comment by gkrs** [comment]
Hi @vojtechtoman,
Yes, we are using `MapInterceptor` and `interceptPut()` specifically. Is there any hope to have it fixed?
