### ISSUE TITLE
SQL: Research how to handle partition migrations

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#15317]
In the simplest implementation, we do not support migrations. If migration is detected, the query fails. We need to understand whether this could be improved somehow:
- When query execution starts, we may try to "reserve" and prevent its eviction until the query is finished.
- It is not clear what consistency guarantees we have for record stores and indexes during migration (e.g. why this "migration stamp" is implemented for indexes?)

**Comment by mmedenjak** [comment]
There might be some hidden or obscure details but the overall consistency during migrations should be the same as in a stable cluster - linearizability. A partition is marked as "migrating" (`InternalPartitionImpl#isMigrating`) before migrations actually start and the partition owner then starts throwing `PartitionMigratingException`. After the migration completes, some clients may still send operations to the old partition owner, in which case they will receive `WrongTargetException` until they receive the new partition table. After the partition table has propagated to all members and clients, they will send operations to the new partition owner.

Since query operations do not necessarily run on the partition thread (e.g. global index), they can circumvent these checks. This is why we have a "migration stamp" which is basically a logical clock. The query fetches the value of the stamp, runs the query and validates that the stamp hasn't changed. If the stamp changed, a concurrent migration has happened and it needs to fall back to a partition operation.

I'm not sure what should be the approach for the new query engine. Intuitively, I don't think the query operations should block migrations. To achieve this, we may borrow the same approach with the migration stamp or try to come up with some better approach.

**Comment by devozerov** [comment]
We will use migration stamps.
