### ISSUE TITLE
IMap lock map is not shared between members

### ISSUE THREAD

**Issue by jorell13** [hazelcast/hazelcast#15513]
Greetings Hazelcast Development team,
The below code worked in Hazelcast version 3.8.9.  After the upgrade to 3.12.1, a server that should not have the lock proceeds through the if statement.  We have a dump servlet that confirms that the members are seeing each other.

```java
hazelLocks = HazelcastFactory.getInstance().getMapLock();
InetSocketAddress hostMachine =  hazelcastInstance1.getCluster().getLocalMember().getInetSocketAddress();
String hostName = context.getEnvironmentName() + hostMachine.getAddress().toString();
File file1 = new File(fileString);
if (hazelLocks.tryLock(envName+ "-" + dirName)) { // we got the lock
      try {
        //Do stuff
        }
       catch(...){
       //Do more stuff
        }
```

Thank you,
James.

**Comment by mmedenjak** [comment]
Hi @jorell13 !

The only way I can think of that happening is if temporarily there was a split in the cluster and there were different members, each on one side of the split, that were responsible for maintaining the lock information. The logs should prove this but I'm assuming you don't have logs at this moment.

On this note, with Hazelcast 4.0, we have replaced the entire implementation of ILock with the unsafe mode of CP subsystem (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations). If you don't require strong consistency guarantees, that mode might fit your use case and solve the issue. If you do require strong consistency guarantees, you definitely might want to try out using the CP subsystem by turning off unsafe mode and running the appropriate number of members. Can you try it out?

**Comment by mmedenjak** [comment]
Also, I don't see the code for this method: `HazelcastFactory.getInstance().getMapLock()`. What kind of lock is it obtaining?

**Comment by jorell13** [comment]
Here is the requested code
public IMap<Object, Object> getIMapLock() {
  return iMapLocks;
}

I’ve looked your email over with our lead architect.  We tested this in a prior version and it worked properly in 3.8.9.  I will double check this, just  in case.  Until then, has anything changed with 3.12.1 that would prevent this from working in 3.12.1 as it’s written?


Best Regards,
James L. O'Rell
Software Developer

iWorks Corporation
SBA 8(a) | CMMI Level 3 | ISO 9001:2008
GSA STARS II GS06F0972Z
GSA 70 GS35F031CA | FAA e-FAST
Phone: 571.424.1065 | www.iworkscorp.com<http://www.iworkscorp.com/>
McLean, VA | Reston, VA
jorell@iworkscorp.com<mailto:jorell@iworkscorp.com>

FOUO:  This communication and the information contained in it is For Official Use Only (FOUO) and is only intended for the recipient to which it is addressed.  If you have received this communication in error, please notify the sender at the reply e-mail address and delete it from your system without copying or forwarding it. If you are not the intended recipient, you are hereby notified that any retention, distribution, or dissemination of this information is strictly prohibited.

**Comment by mmedenjak** [comment]
Sorry for the long wait. I don't think there were any changes relevant to your use case. If you want to go through all of the changes involving something doing with locking, here's the best list I could come up with: https://github.com/hazelcast/hazelcast/pulls?utf8=%E2%9C%93&q=lock+is%3Apr+is%3Aclosed+label%3A%22Team%3A+Core%22+merged%3A2018-01-03..2019-06-11+-milestone%3A4.0

I assume the issue was, as mentioned, there was a cluster split causing some members to believe the lock was unlocked while in reality the lock information was simply unreachable. These issues are inherent to our old lock implementation favouring availability.

Seems to me that you would prefer correctness for your use case. In this case, please switch over to using the [CP subsystem](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#cp-subsystem), specifically the [FencedLock](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#fencedlock).

Closing this issue as non-reproducible. Please reopen if you have more information, for instance logs from members during which this issue happened and please try out the CP subsystem as I believe you need it for your use case.
