### ISSUE TITLE
Permanent issue - check public/private API before minor release

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#16023]
A reminder to check public API/private API for packages before each minor release. This issue should be kept in the relevant milestone until there is no risk of leaking private API in a release.

**Comment by burakcelebi** [comment]
@mmedenjak, would it be possible to provide some details about this one?

**Comment by mmedenjak** [comment]
Someone should go through all of the newly introduced code and check that all of the classes we have introduced in 4.1 are appropriately exposed. That means - private classes in private packages and public classes in public packages. The problem isn't really with public classes in public packages, the problem is about the other one - sometimes, people unintentionally put some internal class in a public package (maybe it's simpler to do, maybe they just didn't notice it).
Then, as releases accumulate, we get more and more classes in public packages. We can't move them to private API anymore because someone might be using it and we can't say anymore that:
> everything in `impl` or `internal` packages is private API, otherwise it's public API
Because it's not true. 

So, we did a big cleanup in 4.0 and now it's just a reminder that before every next release, someone should go over all of the classes and check we didn't expose private classes somewhere.

**Comment by burakcelebi** [comment]
Makes sense, thank you very much!

**Comment by mmedenjak** [comment]
Looks good so far, I'll assume we'll not leak private API in the stabilisation phase :) Moving to 4.2 to check then again.

**Comment by blazember** [comment]
I think this is a useful command making the check easier: `git diff $(git log --format=%h %SOURCE_RELEASE_BRANCH% | head -n 1)..HEAD --diff-filter=ACT --text --stat -S"public" -- . ':!*src/test/*' ':!*\/impl\/*' ':!*\/internal\/*'`

This command lists the added, copied, modified (`--diff-filter=ACT`) files that include `public` (`-S"public"`) in the changes done since a source branch's `HEAD` (`%SOURCE_RELEASE_BRANCH%`, this is to be substituted with `4.1` for example) and current branch's `HEAD`, excluding the changes done in `impl` and `internal` packages and in tests.

Checked 4.1 -> 4.2 in OS and EE, I think we're good to go.

**Comment by mmedenjak** [comment]
Thanks @blazember for the tip and the check :)

**Comment by mmedenjak** [comment]
Closing as the issue just seems to be confusing people as an unfixable issue :) We should pay attention during PR reviews, and maybe introduce some tool/library to do automated checks in the future, I think @vbekiaris mentioned some.
