### ISSUE TITLE
Overwriting cache manager when context is refreshed

### ISSUE THREAD

**Issue by pazvanti** [hazelcast/hazelcast#16212]
The following setup exists: Hazelcast 3.12.4, Spring 4.3.24
```java
@Configuration
@Import({ HazelcastConfig.class})
public class AppConfig {
   @Bean
   public CacheAwareStore cacheAwareStore(CacheManager manager) {
       return new CacheAwareStore(manager);
   }
}

public class HazelcastConfig {
    private static final HazelcastInstance HAZELCAST_INSTANCE = Hazelcast.newHazelcastInstance();
    @Bean
    public HazelcastInstance hazelcastInstance() {
         return HAZELCAST_INSTANCE;
    }

   @Bean
    public CacheManager cacheManager() {
        HazelcastServerCachingProvider provider =
                HazelcastServerCachingProvider.createCachingProvider(HAZELCAST_INSTANCE);
        return new HazelcastServerCacheManager(provider, HAZELCAST_INSTANCE, null, null, null);
    }
}

public class CacheAwareStore implements TokenStore {
    public CacheAwareStore(CacheManager cacheManager) {
          this.manager = cacheManager;
          initCache("testCache1");
          initCache("testCache2");
     }

    private initCache(String name) {
          Cache<String.class, String.class> cache = manager.getCache(name, String.class, String.class);
          if (cache != null) {
               return cache;
          }
         // create a configuration
        cache = manager.createCache(cacheName, config);
        return cache;
    }
}
```

Next, two test classes exist that use the Spring context:
```java
@WebAppConfiguration
@ContextConfiguration(classes = {AppConfig.class})
public class TestClass1 extends AbstractTestNGSpringContextTests {
    @Autowired
    protected WebApplicationContext webApplicationContext;
    // a few tests here
}

@WebAppConfiguration
@ContextConfiguration(classes = {AppConfig.class})
public class TestClass2 extends AbstractTestNGSpringContextTests {
    @Autowired
    protected WebApplicationContext webApplicationContext;
    // a few tests here
}
```

When ran individually, the tests from both classes work as intended. However, when ran together, only the tests from the first test class pass, the others fail. I assume that this is due to the refreshing of the context, which causes problems.

```java
GenericWebApplicationContext: Refreshing org.springframework.web.context.support.GenericWebApplicationContext@6170989a: startup date [Mon Dec 09 10:47:28 EET 2019]; root of context hierarchy
WARN GenericWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name <name>
....
nested exception is java.lang.IllegalStateException: Cannot overwrite a Cache's CacheManager.
```
The exception occurs at `manager.getCache()`.
Problem does not occur on Hazelcast V3.8 and older. The check that does not allow setting a different manager has been added in V3.9. This is not the problem though.

Under further inspection, I believe that there is no check to see if the new manager that is being set is actually different than the existing one. However, I tried a workaround. Changed the `CacheAwareStore`:
```java
    public CacheAwareStore(CacheManager cacheManager) {
          this.manager = cacheManager;
          destroyCaches();
          initCache("testCache1");
          initCache("testCache2");
     }
    public void destroyCaches() {
         manager.destroyCache("testCache1");
         manager.destroyCache("testCache2");
    }
```

After this change, the same exception happens further down, at `manager.createCache(cacheName, config);`. Using `manager.getCacheNames()` to display the existing cache returns no values, as expected, still, a new cache can't be created. Using `manager.destroyCache(cacheName);` prior to creating the cache has no effect. 
Further digging in the code it seems that there is already a cacheProxy for the cache name, despite not actually existing a cache yet. Code entry point for investigation `HazelcastServerCacheManager::creteCacheProxy()`.

There might not be a problem when the application is actually running (further investigation is needed), however when the context is refreshed during tests the problem is reproducible.

**Comment by vbekiaris** [comment]
@pazvanti on first look, it seems that the issue is related with the way you obtain your `CachingProvider` and `CacheManager`. As per JSR107 API, you would do something like `Caching.getCachingProvider()` (or `Caching.getCachingProvider(HazelcastServerCachingProvider.class.getName())` to disambiguate in case there are several caching providers in your classpath). This is a static method and will return the same instance of a given caching provider after the first invocation.

On the other hand, you are explicitly creating a new caching provider and a new cache manager each time `cacheManager()` is invoked therefore each `CachingProvider` instance is oblivious to the `CacheManager`s already created by other instances. Also your `HAZELCAST_INSTANCE` is constructed in a static context: this means that all `Cache`s already created by test classes will live on until either explicitly destroyed or the JVM that executes the tests is terminated.

I would suggest to try the following:
1. Rewrite your `cacheManager()` creation method using JCache API instead of internal Hazelcast APIs as follows:
```
@Bean
public CacheManager cacheManager() {
    HazelcastServerCachingProvider provider = Caching.getCachingProvider(); // or add class name of Hazelcast server caching provider to disambiguate
    return provider.getCacheManager(null, null, HazelcastCachingProvider.propertiesByInstanceItself(HAZELCAST_INSTANCE));
}
```
This way you ensure coherent `CachingProvider`/`CacheManager` lifecycle.

2. Ensure all of your tests destroy the caches (or other Hazelcast data structures) they used in their `@After` method.

3. Make sure your tests are executed serially. If executed concurrently, as long as there is a single static `HazelcastInstance` shared across all tests, you will observe random failures due to races like having a test destroying a cache while another one is still executing.

**Comment by pazvanti** [comment]
Thanks @vbekiaris 
Using the JCache API as you suggested solved the problem.
