### ISSUE TITLE
Automatically detect the classloader of type for UserCodeDeployment

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#16421]
For the UserCodeDeployment feature, we need to provide a classLoader definition if the required classes are loaded via a different classloader than Hazelcast's. (`clientConfig.setClassLoader(..)`)

This is a limitation if we need to load via multiple classLoaders. 

The classLoader of a type can be detected via `ClazzImpl.class.getClassLoader()` method. 

So, instead of requiring a custom class loader definition, we can infer the classLoader from the type and use it.

**Comment by burakcelebi** [comment]
Related: https://stackoverflow.com/questions/59832471/noclassdeffounderror-after-uploading-jars-to-hazelcast-cloud-via-client-user-cod/59837513

**Comment by sancar** [comment]
We have investigated and found out that inferring the class loader from user's class is not necessary. The users problem on tomcat caused by user code deployment using wrong `class loader` by default. When it is switched to `current thread context class loader` from `system class loader` , the problem disappeared. 
@yozank Can you also confirm that we no longer need to use ` ClazzImpl.class.getClassLoader()` and issue is resolved.
