### ISSUE TITLE
Member OOME hprof, clients connect put get disconnect

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16429]
http://jenkins.hazelcast.com/view/stable/job/stable-client-connection/49/console

/disk1/jenkins/workspace/stable-client-connection/4.0-SNAPSHOT/2020_01_08-01_28_06/client-connection 

Failed

HzClient14HZ client-ConnectGetShutdown hzcmd.client.ConnectGetPutShutdown threadId=6 com.hazelcast.spi.exception.TargetDisconnectedException: The client has closed the connection to this member, after receiving a member left event from the cluster. ClientConnection{alive=true, connectionId=3, channel=NioChannel{/10.0.0.216:43985->/10.0.0.216:5701}, remoteEndpoint=[10.0.0.216]:5701, lastReadTime=2020-01-08 02:23:54.193, lastWriteTime=2020-01-08 02:24:22.203, closedTime=never, connected server version=4.0-SNAPSHOT}

Hazelcast Enterprise 4.0-SNAPSHOT (20200106 - 04d69c5, 33fc094)

./client-connection/output/HZ/HzMember2HZ/HzMember2HZ.hprof

http://54.147.27.51/~jenkins/workspace/stable-client-connection/4.0-SNAPSHOT/2020_01_08-01_28_06/client-connection/gc.html

http://54.147.27.51/~jenkins/workspace/stable-client-connection/4.0-SNAPSHOT/2020_01_08-01_28_06/client-connection/output/HZ/HzMember2HZ/

<img width="944" alt="Screen Shot 2020-01-08 at 10 54 57" src="https://user-images.githubusercontent.com/5988678/71946647-60e3f980-3205-11ea-9657-ed86cd2d281a.png">

**Comment by Danny-Hazelcast** [comment]
2nd fail http://jenkins.hazelcast.com/view/stable/job/stable-client-connection/50/console

**Comment by pveentjer** [comment]
If I understand it correctly, this test connects, does a put and then disconnects with a loop around.

So it seems that the endpoints aren't removed from the clusterListeningEndpoints.

**Comment by sancar** [comment]
From my analysis, an endpoint is removed from  `clusterListeningEndpoints` when it is disconnected. 
At first, it looks like there is no leak. The leak appears in a race situation. And the leak is not just about cluster listener. Any listener could be leaked in this situation. 
Background:
- When a listener is added from an endpoint, we also register a destroyAction. 
- A destroyAction is a function to deregister the listener. It is used when endpoint is removed. 
- When endpoint is removed we call all the registered destroy actions.

Race:
- A listener is added, but not registered the destroy action.
- Endpoint is removed because the client is disconnected. All the destroy actions currently registered are called. 
- DestroyAction is registered to endpoint after it is destroyed. 
- After this point, there is no one to call the last destroyAction, hence the leak. 

I am working on the fix.
