### ISSUE TITLE
Consider using consistent versioning scheme for all releases / artifacts

### ISSUE THREAD

**Issue by kedar-joshi** [hazelcast/hazelcast#16661]
Currently Hazelcast follows two versioning schemes, one without bugfix version and another with bugfix version i.e. `4.0` and `4.0.1`. 

For consistency, consider including bugfix version for all releases e.g. `4.0.0` and `4.1.0` instead of `4.0` and `4.1` respectively.

**Comment by mmedenjak** [comment]
Hi @kedar-joshi . True, we'll consider it. @Holmistr WDYT?

**Comment by Holmistr** [comment]
In general, I also didn't like the current scheme when I joined. I got used to it. However, I don't really see any practical benefit in changing it to `x.y.z` other than "formal consistency". @kedar-joshi Any example where this prevent you from doing something?

Don't get me wrong, I have nothing against your suggestion. However, I see the non-trivial effort behind it (update out release automation, docs update etc.) and I don't see any real benefit behind this effort. That's why I'm a bit reluctant to spend time on this.

**Comment by kedar-joshi** [comment]
> Any example where this prevent you from doing something?
No. This doesn't affect / prevent any functionality whatsoever.

> I don't really see any practical benefit in changing it to x.y.z other than "formal consistency"
You are right, it's mostly for formal consistency only. The reason I raised this because I was upgrading Hazelcast and habitually wrote `4.0.0` as version as most of the Maven dependencies follow the same scheme.

Thank you for your consideration. I would completely understand if this can't be implemented if the benefit for community doesn't justify the effort.

**Comment by Holmistr** [comment]
> I would completely understand if this can't be implemented if the benefit for community doesn't justify the effort.

That's not what I'm saying right now. Right now I'm asking "What's the benefit for community?". I don't really see one. Trust me, I would move the Earth for community :)
If we can come up with a good reason, I will be happy to implement it.

**Comment by nfrankel** [comment]
As for me, I'd prefer a consistent scheme. Like, I'm writing my POM, and I would put version 4.0.0 and Maven would complain it's not found.

So now I need to go on Maven repository, and check there's a 4.0. Time wasted...

@Holmistr I understand your point. Now you can decide if it's worth it

**Comment by kedar-joshi** [comment]
I think this suggestion was adopted since v5.2.0, so closing.
