### ISSUE TITLE
Cluster is locking when node is down

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#1688]
I'm testing Hazelcast to prove I can use it for following scenario:
- 2 nodes with Near Cache Enabled.
- One node goes down.
- Second node is trying to call containsKey on the map but the call hangs:
  Map<String, Integer> myMap=hz.getHazelcastInstance().getMap("MyMap");
  boolean contKey=myMap.containsKey("someKey");
  and after some time it throws exception:

Jan 31, 2014 9:59:22 PM com.hazelcast.spi.Invocation
WARNING: [10.128.33.190]:5700 [4c3yrb0xdv7k3c11c47aguom] While asking 'is-executing': InvocationImpl{ serviceName='hz:impl:mapService', op=ContainsKeyOperation{}, partitionId=65, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.128.33.122]:5700}
java.util.concurrent.TimeoutException
 at com.hazelcast.spi.impl.InvocationImpl$InvocationFuture.resolveResponse(InvocationImpl.java:450)
 at com.hazelcast.spi.impl.InvocationImpl$InvocationFuture.get(InvocationImpl.java:298)
 at com.hazelcast.spi.impl.InvocationImpl.isOperationExecuting(InvocationImpl.java:494)
 at com.hazelcast.spi.impl.InvocationImpl.access$1300(InvocationImpl.java:36)
 at com.hazelcast.spi.impl.InvocationImpl$InvocationFuture.waitForResponse(InvocationImpl.java:394)
 at com.hazelcast.spi.impl.InvocationImpl$InvocationFuture.get(InvocationImpl.java:297)
 at com.hazelcast.spi.impl.InvocationImpl$InvocationFuture.get(InvocationImpl.java:288)
 at com.hazelcast.map.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:293)
 at com.hazelcast.map.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:204)
 at ccio.img.MyServlet.proxyRequest(MyServlet.java:216)
and continue hanging for several minutes throwing the same exception.

My expectation was, if a node goes down, and the data is cached on all nodes, the command would just check a local node, and returns a true/false if the key is found or not, and it wouldn't wait for connection to the dead node.

What am I doing wrong? How can I achieve my goal?

Thank you,

Eugene

**Comment by ssozonoff** [comment]
Anychance this issue is back. We are running HZ 3.5.4 and are experiencing the same problem when we take down a node from the cluster. Everything freeze's.

**Comment by spifd** [comment]
Yes, this would be to interesting to know if this issue is back. We are also experiencing the same freeze when cutting network on one of our nodes.

**Comment by strokine** [comment]
I still see similar behavior, and I'm on HZ 3.6.2 now. I found some work around which at least let our cluster running after one node's connection fails:
```
hzConfig.setProperty("hazelcast.max.no.heartbeat.seconds", "10");
```
the default value is 5 minutes.
After I've set the property to 10 seconds, I see following:
- a node is loosing connection because of some network issues.
- the node is in FROZEN state, it thinks it is only node in the cluster.
- the cluster is loosing the node, but continue working
- even though the connection is restored, the node is still FROZEN and doesn't rejoin the cluster. We usually just reboot the node.

BTW: to reproduce the problem you could use IPTables if you cannot just unplug the network cable from the machine.

**Comment by michaeljs1990** [comment]
I saw the exact same issue today and the only way to recover was a reboot of the node. Having build in health check endpoints for hazelcast would be nice.

**Comment by chernser** [comment]
I've found same issue on 3.7.2
It is possible to isolate node or remove it from cluster until it is operable?

**Comment by psychotropic** [comment]
I tried the test code uploaded in "https://gist.github.com/cazacugmihai/9249123" with version 3.5.5 and 3.6.4 with TCP IP configuration and I can confirm that the bug is NOT present. The same versions have been running in production for some time now and the only lockdown we observer are related to some nodes throwing OoM exceptions - because of that they fail to release some of the locks they've acquired. The solution can be found here: https://blog.hazelcast.com/out-of-memory. 
The situation would be similar if you close the app without calling hazelcastInstance.shutdown().

@chernser I also tried the test code with 3.7.2 and also I bumped the version in one of our applications - everything seems to work as expected.

Hope this can help other dig their lockdown issues.

Hope this can

**Comment by memnoth** [comment]
This problem is ongoing in 3.9.

# TEST CASE
2 nodes, one of them is on Host, other is on a container of Docker.
An application I made runs on both environment and all code lines and hazelcast version are same.
## Environment information
Docker
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Host
```
Ubuntu 16.04.3
Kernel : 4.4.0-98
Java 8
```
## What I did
While the application is running on both, I let the container stop, not the application. (like a unexpected situation.)
Since the situation has happened, other node still lived gets into locking and a heartbeat timeout raised.
The log is as following,
```
Members {size:2, ver:6} [
	Member [172.17.0.1]:5701 - ded69740-c1a2-4051-b3f8-43c407cbebe7 this
	Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
]

11월 02, 2017 10:31:40 오후 com.hazelcast.internal.partition.impl.MigrationManager
정보: [172.17.0.1]:5701 [dev] [3.9] Re-partitioning cluster data... Migration queue size: 271
11월 02, 2017 10:31:42 오후 com.hazelcast.internal.partition.impl.MigrationThread
정보: [172.17.0.1]:5701 [dev] [3.9] All migration tasks have been completed, queues are empty.
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnection
정보: [172.17.0.1]:5701 [dev] [3.9] Connection[id=3, /172.17.0.1:5701->/172.17.0.2:55822, endpoint=[172.17.0.2]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Connecting to /172.17.0.2:5701, timeout: 0, bind-any: true
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Could not connect to: /172.17.0.2:5701. Reason: SocketException[Connection refused to address /172.17.0.2:5701]
11월 02, 2017 10:31:50 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Connecting to /172.17.0.2:5701, timeout: 0, bind-any: true
11월 02, 2017 10:32:39 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] This node does not have a connection to Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:44 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] This node does not have a connection to Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] This node does not have a connection to Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
경고: [172.17.0.1]:5701 [dev] [3.9] Suspecting Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc because it has not sent any heartbeats since 2017-11-02 22:31:49.265. Now: 2017-11-02 22:32:49.285, heartbeat timeout: 60000 ms, suspicion level: 1.00
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.impl.MembershipManager
정보: [172.17.0.1]:5701 [dev] [3.9] Removing Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.transaction.TransactionManagerService
정보: [172.17.0.1]:5701 [dev] [3.9] Committing/rolling-back alive transactions of Member [172.17.0.2]:5701 - a1330d2f-998f-46e4-b8ad-ca5a76f514cc, UUID: a1330d2f-998f-46e4-b8ad-ca5a76f514cc
11월 02, 2017 10:32:49 오후 com.hazelcast.internal.cluster.ClusterService
정보: [172.17.0.1]:5701 [dev] [3.9] 

Members {size:1, ver:7} [
	Member [172.17.0.1]:5701 - ded69740-c1a2-4051-b3f8-43c407cbebe7 this
]

11월 02, 2017 10:32:49 오후 com.hazelcast.internal.partition.impl.MigrationManager
정보: [172.17.0.1]:5701 [dev] [3.9] Partition balance is ok, no need to re-partition cluster data... 
11월 02, 2017 10:32:56 오후 com.hazelcast.nio.tcp.TcpIpConnector
정보: [172.17.0.1]:5701 [dev] [3.9] Could not connect to: /172.17.0.2:5701. Reason: SocketException[호스트로 갈 루트가 없음 to address /172.17.0.2:5701]
```
But this doesn't happen when I run the same application in different jvm on the same **Host**.
Open 2 terminal, then run it on each terminal.
## What I am going to do
1. Make another container with ``--net=host`` option, I have heard that there was a network issue from a Hazelcast Engineer.
2. Test this problem in wired network environment with a few physical nodes as Raspberry Pi 3.

I run Hazelcast in local wireless network environment for my experiment and I need to solve the problem for next step.
I hope this logs can be helped for it and will be fixed it as soon as possible.
Thank you!
