### ISSUE TITLE
Unhandled Hz (C/S) exception when shutting down instance

### ISSUE THREAD

**Issue by shashanka981** [hazelcast/hazelcast#17070]
When  Hazelcast is run  in Client/Server mode, an exception is reported on the hazelcast client instance that is being shut down. The message shown is:
```
(proxy.ClientReliableTopicProxy) WARN    - hz.client_0 [PegaCluster] [3.11.5] Terminating MessageListener com.org.platform.cluster.internal.HazelcastClientClusterProvider$MembershipEventListener@3aa798ff on topic: test/member/membership/event/topic. Reason: Unhandled exception, message: Client is shutting down
com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:215) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]
	at com.hazelcast.client.spi.impl.AbstractClientInvocationService.shutdown(AbstractClientInvocationService.java:197) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:962) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:152) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.shutdown(HazelcastClientProxy.java:297) ~[hazelcast-enterprise-client-3.11.5.jar:3.11.5]
	at 

Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	... 34 more
```
Version of hazelcast used for both client and server is hazelcast enterprise 3.11.5
Listener referred in the issue is actually registered during client intialization as below

**instance.getReliableTopic("test/member/membership/event/topic").addMessageListener();**

Wanted to know if this is an issue or expected behaviour ? If it is an issue, what is the impact of this exception and how can we fix it

**Comment by sancar** [comment]
@shashanka981 This is an expected behaviour. Any method can throw `HazelcastClientNotActiveException` , if the client is being shutdown or it was already shutdown. 
If you don't expect your client to shutdown quickly, you can configure so via connectionAttemptLimit. see https://docs.hazelcast.org/docs/3.11.5/manual/html-single/index.html#handling-failures

**Comment by shashanka981** [comment]
@sancar  to clarify, this exception occurs not because client is not able to connect to cluster members, but when client is undergoing shutdown (via explicit call to  HazelcastInstance.shutdown() invocation as part of applcation server shutdown hook. 

  Why does Hazelcast explicitly logs the message as a warning during shutdown ? What does the below message mean to a developer working with hazelcast ?

**"Terminating MessageListener com.org.platform.cluster.internal.HazelcastClientClusterProvider$MembershipEventListener@3aa798ff on topic: test/member/membership/event/topic. Reason: Unhandled exception, message: Client is shutting down
com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down"**

**Comment by sancar** [comment]
>  Why does Hazelcast explicitly logs the message as a warning during shutdown ? What does the below message mean to a developer working with hazelcast ?

ReliableTopic MessageListener supposed to handle the internal exceptions where it can and log them as `finest` if it can not handle. For example `HazelcastInstanceNotActiveException` and `DistributedObjectDestroyedException` are the ones that it can not handle and logged as `finest` . It seems that `HazelcastClientNotActiveException` should be in that list and skipped. 

So to our users, it should be hidden. Since the client is shutting down, there is nothing user can do anymore, it does not make sense to`WARN` the user. As a workaround, you can safely ignore the log. 

I am marking this issue as defect. We are maintaining 3.12.x and 4.x series at the moment. We will provide the fix for these versions.
