### ISSUE TITLE
WrongTargetException after restarting nodes with cp subsytem

### ISSUE THREAD

**Issue by mariusz2108** [hazelcast/hazelcast#17251]
**Describe the bug**
Test environmet:
Enabled cp subsytem on all hazelcast instances
2 java processes:
- first with 3 hazelcast instances
- second with 2 hazelcast instances

**Expected behavior**
Currently WrongTargetException is raised on hazelcastInstance1.getCPSubsystem().getLock("Lock")
WrongTarget! local: Member [10.0.2.4]:5000 - 18970da8-de78-48fc-9a0f-8a307c202168 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.cp.internal.operation.RaftQueryOp, service: hz:core:raft
This exception should not be raised.

**To Reproduce**

1. Start first java process with 3 hazelcast instances
2. Start second java process with 2 hazelcast instances
3. Restart first process
4. WrongTargetException is raised

**Additional context**
Sample java code to reproduce issue:
```
public class Main1 {
    public static void main(String[] args) {
        HazelcastInstance hazelcastInstance1 = Hazelcast.newHazelcastInstance();
        HazelcastInstance hazelcastInstance2 = Hazelcast.newHazelcastInstance();
        HazelcastInstance hazelcastInstance3 = Hazelcast.newHazelcastInstance();
        FencedLock lock = hazelcastInstance1.getCPSubsystem().getLock("Lock");
        System.out.println("Lock acquired");
    }
}
public class Main2 {
    public static void main(String[] args) {
        HazelcastInstance hazelcastInstance1 = Hazelcast.newHazelcastInstance();
        HazelcastInstance hazelcastInstance2 = Hazelcast.newHazelcastInstance();
        FencedLock lock = hazelcastInstance1.getCPSubsystem().getLock("Lock");
        System.out.println("Lock acquired");
    }
}
```

Config:
```
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd">
    <cluster-name>cp</cluster-name>
    <properties>
        <property name="hazelcast.prefer.ipv4.stack">false</property>
    </properties>
    <network>
        <port auto-increment="true">5000</port>
        <join>
            <multicast enabled="true"/>
        </join>
    </network>
    <cp-subsystem>
        <cp-member-count>3</cp-member-count>
    </cp-subsystem>
</hazelcast>
```

**Comment by mmedenjak** [comment]
Thank you for the report @mariusz2108 ! @mdogan @petrpleshachkov can you take a look if it's simple to fix?

**Comment by mdogan** [comment]
Problem here is, when you restart the first process, you lose the whole CP subsystem. Because CP member count is 3 and you are terminating the first 3 servers. Without CP persistence, they cannot recover the CP state and CP subsystem becomes nonfunctional. You have to reset the CP subsystem to re-initialize it. 

Btw; I see you're printing `"Lock acquired"` after calling  `getCPSubsystem().getLock("Lock")`. But calling `getLock("lock")` doesn't mean lock is acquired. It just returns a lock object instance.

**Comment by mariusz2108** [comment]
I know that I lose my CP subsystem when first process is down. But why it is not restored when first process is up? And instead of restoring CP exception is thrown. 

I know that lock isn’t acquired. Wrong message. I just wanted to point out that lock is crated in hazelcast.

**Comment by mdogan** [comment]
Without persistence, CP cannot be restored. Because all in-memory state is lost, but restarting servers don't know whether existing members has CP state or not. CP subsystem is formed only during initial cluster membership discovery process at the very first time. After that point, if you lose the CP majority and persistence is disabled then you have to `reset` CP state to initiate a new CP discovery.

Also if you shutdown first three members gracefully, via `hazelcastInstance.shutdown()`, then servers in the second process will be promoted to CP members automatically.

**Comment by mariusz2108** [comment]
Thank you for explanation
