### ISSUE TITLE
JCache support requires users to rely on classes from the impl.* package

### ISSUE THREAD

**Issue by pivovarit** [hazelcast/hazelcast#17312]
When trying to use JCache, users need to provide a `CachingProvider` implementation of their choice and it turns out it's one of the below internal classes residing in the `com.hazelcast.cache.impl` package:
- `com.hazelcast.cache.impl.HazelcastServerCachingProvider`
-  `com.hazelcast.cache.impl.HazelcastClientCachingProvider`

And we should not be encouraging users to use internal classes.

What's more, it looks like it's standard practice - check [this link](https://github.com/search?q=spring.cache.jcache.provider%3Dcom.hazelcast.cache.impl.HazelcastServerCachingProvider+extension%3Aproperties&type=Code&ref=advsearch&l=&l=).

Some more details:

> Starting with 4.x, when you call Caching.getCachingProvider("com.hazelcast.cache.HazelcastCachingProvider"), it returns the client provider by default since now the client classes are included within the Hazelcast package.
> 
> I guess that is why we need to specify com.hazelcast.cache.impl.HazelcastServerCachingProvider as the provider explicitly.

[source](https://github.com/hazelcast-guides/caching-springboot-jcache/issues/4#issuecomment-667885350)

----

Related: https://github.com/hazelcast-guides/caching-springboot-jcache/issues/4#issuecomment-668061838

**Comment by vbekiaris** [comment]
For programmatic JCache API config, user can define the server or client-side provider either by system property or by using one of the public `String` constants in `HazelcastCachingProvider` with `Caching.getCachingProvider(className)` method variant as described in [`HazelcastCachingProvider` javadoc](https://github.com/hazelcast/hazelcast/blob/b0a8a6656b3d58b7ef17b2afb62c353dc34b127b/hazelcast/src/main/java/com/hazelcast/cache/HazelcastCachingProvider.java#L48-L70).

However with declarative configuration style (eg when using system property `javax.cache.spi.CachingProvider` [specified by JSR107](https://javadoc.io/doc/javax.cache/cache-api/latest/javax/cache/Caching.html) or the application properties in the linked spring-boot sample) users have to specify an implementation class name for the provider of their choice. I don't see this as encouraging users to _use_ internal classes. User code only deals with the public JCache API (`CachingProvider`/`CacheManager`/`Cache`), nothing internal.

The only way to resolve this for all kinds of declarative config (ie `-Djavax.cache.spi.CachingProvider=<className>`, spring boot `application.properties` and any other kind of declarative config that expects a class name) is to duplicate the server & client side caching provider implementation classes to public packages (for the 4.x version in order to maintain backwards compatibility and remove the `impl` ones in the next major version). Alternatively, we could maybe look into improving the spring-boot situation specifically (eg silly idea: I have little experience with spring, is there a way for our provider to pickup a property defined in `application.properties`?). @jerrinot @pivovarit wdyt?

**Comment by jerrinot** [comment]
Thank you @vbekiaris. From your links I understood the "official" way is to set the `hazelcast.jcache.provider.type` system property to either `client` or `server`. 
I believe `application.properties` cannot set system properties at all. @pivovarit can you please confirm? 

If that's the case then we have to come-up with some other way. 
We cannot keep showing `.impl.` classes in our examples and also we do not want to diverge from Spring configuration standards. I feel pretty strongly about it. Spring is the most popular integration and we have to a top-notch support. 

Can you think of some other way then duplicating classes? could we delegate to them somehow from a public class? or as the last resort: subclass then in a public package?

**Comment by pivovarit** [comment]
No, you cannot set that using  `application.properties`. Making it work would require some hackery to set required system property before the context gets wired up. Our provider could also read `*.properties` files but that would be extremely fragile. Such configs can come, for example, from a config server and not a file so I don't think it's an option.

Having two separate providers is pretty handy, it's just the _impl_ part that could be improved.

I think it'd be fine to introduce two new _public_ classes that simply delegate the work to our internal classes. We'd be in a position where we would not need to reference internal classes anymore, but internal classes would still be there for the sake of backward compatibility.

> I don't see this as encouraging users to use internal classes.

If users need to be aware of the existence of an internal class, we can't simply do whatever we want with it which means it's no longer _internal_

**Comment by vbekiaris** [comment]
A delegate sounds like a good approach to me, resolves the name issue for all kinds of declarative config.

Another thought that *might* help with spring setup specifically: currently the `HazelcastCachingProvider` determines the kind of delegate caching provider eagerly in the constructor. Instead, we could defer this decision until the delegate actually has to be instantiated (essentially any `CachingProvider` method call). If at that point there is no additional contextual information (eg the default `CacheManager` is requested with `cachingProvider.getCacheManager()`), then we instantiate the delegate with the client/server decision logic as-is.

If however we get a call to `cachingProvider.getCacheManager(URI, ClassLoader, Properties)` (Spring passes the value of application property `spring.cache.jcache.config` as `URI` argument and also adds it in hazelcast-specific property `hazelcast.config.location` in the properties argument), then we have a chance to check what kind of configuration that is and instantiate lazily the appropriate delegate. So when your `application.properties` specifies:
```
spring.cache.type=jcache
spring.cache.jcache.config=classpath:hazelcast.xml
```
then `HazelcastCachingProvider` should be able to identify the kind of delegate to instantiate.

Such a change should not break existing applications, it will only enable use cases that were previously failing. Do you think it is worth pursuing this?

**Comment by vbekiaris** [comment]
side-note: I created related issue #17319 . Since YAML config was introduced it should be also supported for `HazelcastInstance`s started in the context of a JCache caching provider.

**Comment by jerrinot** [comment]
I think `spring.cache.jcache.config=classpath:hazelcast.xml` is rather similar to the already existing auto-detections in Spring Boot. 
Perhaps it belong into Spring Boot rather than a pure Spring integrations. I see it as a possible (ux) optimization, but not as a primary mechanism.
