### ISSUE TITLE
Use of non-UTF8 characters in field breaks query on a different field for HazelcastJsonValue

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#17418]
See [Stack Overflow question 63607692](https://stackoverflow.com/questions/63607692/why-hazelcast-not-query-incorrect-result-with-imap-and-hazelcastjsonvalue-includ)

**Describe the bug**
A query on a field in a JSON value does not find that value if there is an index on another field in that JSON, where that field contains UTF-16.

**Expected behavior**
What is in one field should not affect a query on another field

**To Reproduce**

```
HazelcastInstance instance = Hazelcast.newHazelcastInstance(new Config());
IMap<String, HazelcastJsonValue> map = instance.getMap("so63607692");

String json1 = "{\"a\":\"1\",\"b\":\"13国债15\",\"c\":\"1\"}";
String json2 = "{\"a\":\"2\",\"c\":\"1\"}";

map.put("1", new HazelcastJsonValue(json1));
map.put("2", new HazelcastJsonValue(json2));

Predicate predicate = Predicates.sql("c='1'");

System.out.println(map.entrySet(predicate));
map.addIndex(new IndexConfig(IndexType.HASH,"a"));
System.out.println(map.entrySet(predicate));

instance.shutdown();
```

First and second run of the query should print the same results, but don't.

**Additional context**

Output I get
```
[2={"a":"2","c":"1"}, 1={"a":"1","b":"13国债15","c":"1"}]
[2={"a":"2","c":"1"}]
```

Tried on 4.0.2 and 4.1-SNAPSHOT

**Comment by Holmistr** [comment]
CC @devozerov - something to watch for with the new SQL engine - to make it work even with non-standard characters.

**Comment by devozerov** [comment]
Might be related to https://github.com/hazelcast/hazelcast/issues/17477

**Comment by taburet** [comment]
Have found the root cause: if `cache-deserialized-values` set to `ALWAYS` or `INDEX_ONLY` when, for `BINARY` storage, during insertion JSON metadata offsets are calculated as indexes into UTF-8 JSON byte array. While evaluating queries the same metadata offsets are interpreted as indexes into UTF-16 JSON char array. Basically, if the storage format is `BINARY` and deserialized map entries are cached (the default is `INDEX_ONLY`) and there are any non-ASCII characters in the JSON, then the querying is broken. Not sure about the fix yet.

**Comment by sancar** [comment]
@taburet note that @mdumandag  working on a fix for this. 
https://github.com/hazelcast/hazelcast/pull/18183
