### ISSUE TITLE
Does  client server support  rolling uprade of client, if there are changes in  classes that are loaded dynamically

### ISSUE THREAD

**Issue by thesreyas** [hazelcast/hazelcast#17652]
Given:
A long running HZ servers - HZ Clients(Version: V1)
When:
HZ Client is upgraded from v1 to v2 and there are changes in classes configured in clientUserCodeDeploymentConfig
Then:
HZ Client V2 should successfully connect to cluster and perform it's HZ related functionality
Result:
Failed 

Questions1: *Is there way to mitigate this?*

Question2: Currently we need to configure Key-value classes as part of clientUserCodeDeploymentConfig. Can we skip these?

**Comment by thesreyas** [comment]
We see that above observation is inline with documentation. But want to double check as this looks like a common usecase which can block rolling upgrade of applicatoins connecting to Hazelcase server and using dynamic class loading.


https://docs.hazelcast.org/docs/latest/manual/html-single/#two-versions-of-a-class

Two Versions of a Class
If the client uploads a class and the member already has that class, an exception is thrown if the byte code is different. If byte code is same, it is ignored. Therefore classes uploaded from the client can’t be updated with a new version.

**Comment by sancar** [comment]
Hi @thesreyas 
What is the reason for deploying your key-value classes? 
Is your map in-memory format is Object? 
Are you accessing the entries on the cluster via Entry Processor? 
These are some of the use cases where a byte-array content needs to be deserialized. If you don't have similar use-cases you might not need to deploy your classes. 
If you have a similar use-case, yes a client can not redeploy a class with a different version of it. 
In 4.1, we have introduced a new feature to mitigate this. 
You will not need to upload your key-value classes to the cluster anymore to access them on the cluster. See the following:
https://docs.hazelcast.org/docs/4.1-BETA-1/manual/html-single/index.html#accessing-domain-objects-without-domain-classes

Note that this new feature is related to only your key-value classes. If you have, you still need to deploy your functional classes like (EntryPRocessor, or Runnable for IExecutorService). And they can not be redeployed if they are updated from the client. This is something we plan to solve in the near future as well.

**Comment by thesreyas** [comment]
Thanks for your response @sancar 

Response to your questions:
Is your map in-memory format is Object?
NO

Are you accessing the entries on the cluster via Entry Processor?
NO

We are using HZ 3.11 

We create hazelcast caches and maps.  
Can you please confirm that server will never need class definitions?

**Comment by sancar** [comment]
We are trying to make sure that deploying a class is not necessary as much as possible. Having said that there are still some edge cases that you need to be careful. It will not be feasible to list all of them(depending on the feature set that you are interested in, you may not worry about these anyway), but let me give a couple of examples to give you an idea. 

If you are running a query, you need to use Portable. If you don't, the class is needed on the server-side to be able to deserialize and access the fields. 

Again in the query, if you try to make a comparison (like equal/greater than etc) on a Portable Object rather than its fields since it will require access to the `compareTo` method of the class, then again it will require the class on the server-side. You can write the query in terms of fields so that this is not required.

I would suggest preparing a test suite for your use-cases without user-code-deployment and validate that  `user-code-deployment` is not required(Don't forget to put members and clients in separate JVMs). You can always ask if you came across a use-case where you think can be handled without deploying classes, and we can clarify it further.

**Comment by mmedenjak** [comment]
@thesreyas have you tried out the suggestions?

**Comment by sancar** [comment]
@thesreyas I am merging this issue to https://github.com/hazelcast/hazelcast/issues/16813 as a duplicate. 
If you have further questions feel free to ask.
