### ISSUE TITLE
Loggers cannot be deregistered from LoggingServiceImpl and LoggerFactorySupport

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#17894]
`ILogger` in `ConcurrentMap<String, ILogger>` of following class cannot be deregistered:
- in `LoggingServiceImpl` (https://github.com/hazelcast/hazelcast/blob/6c71ca36332f08c15935bbf1af4f1b2f73c10cac/hazelcast/src/main/java/com/hazelcast/logging/impl/LoggingServiceImpl.java#L46)
- in `LoggerFactorySupport` (https://github.com/hazelcast/hazelcast/blob/6c71ca36332f08c15935bbf1af4f1b2f73c10cac/hazelcast/src/main/java/com/hazelcast/logging/LoggerFactorySupport.java#L27) - here is at least `clearLoadedLoggers()`.

Deregistration can be needed for fix of Jet OOM - https://github.com/hazelcast/hazelcast-jet/issues/2703

**Comment by mmedenjak** [comment]
@olukas is this still needed? I see the PRs were merged, and I guess we later reverted them.

**Comment by gurbuzali** [comment]
I can say this is not needed any more. for some logger factories (log4j2 for example) you cannot deregister the logger, so even if we add this ability on our side (which we did with the merged PRs) there will be still leak. 

Our solution was to change how we create loggers. Instead of creating a logger for each job (using job specific identity) we create loggers for once (using static names) and reuse them for each job. We've added job specific identity to the message using a wrapper loggger.
