### ISSUE TITLE
Some questions about FlakeIdGenerator

### ISSUE THREAD

**Issue by CobraStarLE** [hazelcast/hazelcast#17975]
hello,

Will the FlakeIdGenerator duplicate the generated Id due to clock redirection?

thanks.

**Comment by mmedenjak** [comment]
Hi @CobraStarLE !

What do you mean by clock redirection? Also, please direct questions to our community slack - slack.hazelcast.com

**Comment by mmedenjak** [comment]
@CobraStarLE any clarification on the above question?

**Comment by CobraStarLE** [comment]
I'm sorry it took so long to get back to you. Since FlakeIdGenerator generates Id's based on time, would it be possible to generate the same Id again if the server's time is called back? Thanks.

**Comment by viliam-durina** [comment]
It's not possible during normal operation, because we do `time = max(System.currentTimeMillis(), lastTime + 1)`.

**Comment by viliam-durina** [comment]
It's not possible during normal operation, because we do `time = max(System.currentTimeMillis(), lastTime + 1)`. But it can happen if the time goes back while the member is shut down. Of course, it would have to go back by an amount larger than was the duration of the shut down. We assume that servers use some kind of time synchronization, and these are typically less than one second off, and a restart typically takes much longer, therefore we consider this acceptable. But in theory, it is possible.

**Comment by viliam-durina** [comment]
Closing - please continue discussion in the community slack.
