### ISSUE TITLE
 Get Leader CPMember API ?

### ISSUE THREAD

**Issue by coolbeevip** [hazelcast/hazelcast#17981]
I can use the following API to get CPMember of CPSystem. How to get a leader member?

```
hazelcastInstance.getCPSubsystem().getCPSubsystemManagementService().getCPMembers().toCompletableFuture().join()
```

**Comment by mmedenjak** [comment]
@sancar @petrpleshachkov any ideas? Do we have such an API?

**Comment by sancar** [comment]
@mmedenjak Nope, it is not exposed via public API. 
@coolbeevip What is your use case? Maybe we can suggest an alternative.
Exposing this kind of information usually is not helpful because it can change at any moment.

**Comment by coolbeevip** [comment]
> @mmedenjak Nope, it is not exposed via public API.
> @coolbeevip What is your use case? Maybe we can suggest an alternative.
> Exposing this kind of information usually is not helpful because it can change at any moment.

case 1:

I hope to be able to obtain a conceptual master node from the cluster to execute some special business codes.
 Later I noticed that Lock can be used to achieve similar functions. So this case passed.

case 2:

I hope to show the RAFT status of the CPSystem cluster to provide some information for operation and maintenance.  
Is it possible to expose the EventListener interface when CPSystem initialization is complete and Leader changes

**Comment by sancar** [comment]
For maintenance, I would suggest keeping track of all cp members, not just the leader. When the leader changes, there is nothing to be done from outside. But when the majority is lost /when a cp member crashes, 
1. You may need to manually remove a CP Member from the CP group. 
2. You may need to promote some AP members manually to CP members. 

And for this, we have two listeners:
CPSubsystem.addGroupAvailabilityListener
CPSubsystem.addMembershipListener
see https://docs.hazelcast.org/docs/4.1.1/manual/html-single/index.html#cp-subsystem-listeners for details. 

Also, I heavily recommend reading the following doc when using CP with Hazelcast. Because of strong safety guarantees, it requires manual intervention from time to time unlike other parts of Hazelcast. https://docs.hazelcast.org/docs/4.1.1/manual/html-single/index.html#cp-subsystem-management 

Your suggestion will be noted as a feature request, but I would not count on it to be implemented anytime soon.

**Comment by coolbeevip** [comment]
> For maintenance, I would suggest keeping track of all cp members, not just the leader. When the leader changes, there is nothing to be done from outside. But when the majority is lost /when a cp member crashes,
> 
> 1. You may need to manually remove a CP Member from the CP group.
> 2. You may need to promote some AP members manually to CP members.
> 
> And for this, we have two listeners:
> CPSubsystem.addGroupAvailabilityListener
> CPSubsystem.addMembershipListener
> see https://docs.hazelcast.org/docs/4.1.1/manual/html-single/index.html#cp-subsystem-listeners for details.
> 

Yes, I have noticed this part. 
All my members are CP members and will be automatically promoted to CP member after the startup. 

> Also, I heavily recommend reading the following doc when using CP with Hazelcast. Because of strong safety guarantees, it requires manual intervention from time to time unlike other parts of Hazelcast. https://docs.hazelcast.org/docs/4.1.1/manual/html-single/index.html#cp-subsystem-management
> 
> Your suggestion will be noted as a feature request, but I would not count on it to be implemented anytime soon.

Thank you for your feedback, I will close the issue.
