### ISSUE TITLE
Inconsistent behavior with float infinity

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#18023]
Converting a VARCHAR `'1e100'` to REAL succeeds with `Float.POSITIVE_INFINITY` as the result, but converting a similar DOUBLE to REAL doesn't. It fails with `Numeric overflow while converting DOUBLE to REAL`. I think it should succeed, inexact floating point types don't overflow. Infinity doesn't mean only an actual infinity, it also means that the operation resulted in a an out-of-range value. For example, `Float.MAX_VALUE * 2` results in `+Inf`, even though it clearly isn't an infinity as in the case of `1f/0`.

**Comment by mmedenjak** [comment]
@devozerov can you take a look?

**Comment by devozerov** [comment]
We are aware of inconsistent behavior with special values of floating-point types, see https://github.com/hazelcast/hazelcast/issues/17314. The fix is planned after 4.2 release. 
If you feel that the priority should be higher, please discuss it with @Holmistr to decide whether to include it in the 4.2 scope.

**Comment by devozerov** [comment]
Closing as a duplicate to #17314.
