### ISSUE TITLE
Combined use of local (non-distributed) and distributed data structures

### ISSUE THREAD

**Issue by hostalp** [hazelcast/hazelcast#18072]
**Please describe the problem you are trying to solve**
We use Hazelcast mostly for caching certain data (via Spring). We have cases where we want to have some of these data distributed across the cluster, but at the same time other data to exist only at each node locally (there could be even different values for the same entries and that's perfectly fine in these cases).

Hazelcast doesn't seem to allow it straight away unless we configure and create at least 2 instances (1 distributed, 1 standalone). Other solutions such as Ehcache allow this.

**Please describe the desired behavior**
We'd like to be able to configure certain data structures (mostly maps) as non-distributed/standalone/local or how you'd call it.
It could be ideally a configuration option of the data structure that would ensure that it wouldn't be propagated to the cluster, but only used locally. That would make it possible to combine such data structures with the usual distributed ones using single Hazelcast config and instance (at each node).

**Describe alternatives you've considered**
Current alternative is to use 2 Hazelcast configs and instances, that's however a little cumbersome (need to take care of additional configs etc).
Another option is to use something else for these local caches, but that's neither optimal.

**Comment by mmedenjak** [comment]
Hi @hostalp ! Thank you for the suggestion. If I understand you're looking for something like the ReplicatedMap, with the exception that the values might be different on different nodes (not sure if you're ok with them being different temporarily or permanently).

We will not add this capability for now as we assess it as low priority. I suggest closing this issue until we get more community interest cc @Holmistr @nfrankel

**Comment by Holmistr** [comment]
Hi @hostalp ! Thanks a lot for opening the issue.

We have discussed this internally and unfortunately we have decided that this is not a feature that fits into our long-term vision. It's an essential change of the internals and since there weren't any other users so far requesting this, it seems like it's not worth this massive effort. Sorry.

I'm going to close this issue. We'll monitor it for activity from other users, so if there will be growing demand for this, we can re-evaluate in the future. Thanks a lot for using Hazelcast! :)
