### ISSUE TITLE
Classpath Reporting

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#18262]
In order to better understand the eco-systems that Hazelcast is operating in, it would be desirable to learn of JVM Classpaths.  This will really help us to know how we should invest in the Open Source Roadmap.  For example, what other libraries is Hazelcast used with?

It should be part of the Phone Home system and the user will have the ability to opt-out.

**Comment by dbrimley** [comment]
FYI, we need this in for the IMDG 4.2 release, please.

**Comment by Holmistr** [comment]
Ok, we'll include it.

**Comment by emre-aydin** [comment]
@dbrimley @Holmistr There are some important limitations to how much info you can gather from the classpath. First and foremost is the fact that many Java applications are deployed as fat jars nowadays (for example Spring boot applications), which will hide the used libraries in our current solution. The second one is that application servers/servlet containers don't have useful info in their classpath. The third one is this only applies to the server side and gives us no clues as to where the clients are used.

If our intention is to better understand where Hazelcast is used, I suggest we formulate a set of questions that we want the answer of so that we can develop a better solution next time.
