### ISSUE TITLE
hazelcastInstance.getDistributedObjects() returns the incomplete list of objects

### ISSUE THREAD

**Issue by mokaymakci** [hazelcast/hazelcast#18440]
**Describe the bug**

hazelcastInstance.getDistributedObjects() returns the wrong number of objects. I need to clear all maps in the cache so I called getDistributedObjects() method, but it didn't return the complete list of objects. 

**Expected behavior**

getDistributedObjects() should return all IDistributedObject's such as; queue, map, set, list, topic, lock, multimap.

**To Reproduce**

You can find the sample console application at [this repo.](https://github.com/mokaymakci/hazelcast.poc)

**Additional context**
I'm using:
- I 've 3 nodes cluster setup
- Hazelcast 3.12.12 client & server
- Java 11

**Comment by ramizdundar** [comment]
Hello Murat. I looked at this problem and I'm unable to reproduce the issue. I couldn't use your reproducer since I don't have access to your members or IDistributedObject's in your member. Hence I made a few modifications to your code as you can find [here](https://github.com/ramizdundar/hazelcast.poc). As you can try I have added one DistributedObject of each type and the printed result is 7 as expected. Let me know if I can help.

**Comment by mokaymakci** [comment]
Hello Ramiz, thank for your interest. I've created a new cluster using your Docker image with the same version. (I had Hz nodes without the container before) Now, it works and everything is fine :) I guess I had a platform specific problem but I couldn't figure out.
