### ISSUE TITLE
HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18469]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4420

```
java.lang.AssertionError: output continues after shutdown expected:<6> but was:<16>
	at com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.lambda$when_iListWrittenAndMemberShutdown_then_jobRestarts$3(HazelcastConnector_RestartTest.java:106)
	at com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts(HazelcastConnector_RestartTest.java:106)
```

**Comment by mmedenjak** [comment]
@viliam-durina can you take a look?

**Comment by viliam-durina** [comment]
It's Jet issue @gurbuzali :)

**Comment by ufukyilmaz** [comment]
I looked at the logs of the two separate builds that this test failed, and they both fail for the same reason. 
My findings are:
- In both tests, the graceful shutdown is failed and this causes the job to restart earlier than expected and made the assertion fail (Normally a synchronization was made in the test, assuming this graceful shutdown won't fail). Because we have migration blocking CountdownLatch and it blocks graceful shutdown until `countdown()` of this countdown latch is called. In this test, it appears that the `countdown()` method of this countdown latch was not called, the program did not reach [this line](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnector_RestartTest.java#L109) for the graceful shutdown timeout (120 seconds). The program normally reaches this mention line very quickly, but in these failing builds, the execution is blocked before this line, at somewhere in [this code block](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnector_RestartTest.java#L101-L106). When I look at the logs, I see that the program can only be blocked in one of the `waitExecutionDoneOnMember()` calls. This means that the job execution future in one of these instances was not completed (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/jet/impl/connector/HazelcastConnector_RestartTest.java#L124), but I could not fully understand why it could not be completed.

**Comment by mmedenjak** [comment]
Hm. Don't have any bright ideas as I don't have experience with jet tests. Can you add more logging to the job execution to determine the root cause? Have you tried rerunning the test many times in a separate build like we do with IMDG tests?

**Comment by mmedenjak** [comment]
Closing until next failure as we've added additional logging to find out the root cause.

**Comment by mmedenjak** [comment]
Failed again:
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4590

**Comment by viliam-durina** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4635/testReport/junit/com.hazelcast.jet.impl.connector/HazelcastConnector_RestartTest/when_iListWrittenAndMemberShutdown_then_jobRestarts/

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4650
