### ISSUE TITLE
Job cleanup time increases during running Jet soak tests [HZ-4822]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19113]
Jet soak tests periodically start batch jobs. There are not more than dozens of jobs running at the same time. 

During the execution job cleanup takes more and more time, for example this is after 2hours:
```
16:26:40,289 DEBUG || - [JobRepository] hz.xenodochial_swanson.cached.thread-37 - [10.0.0.37]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 907ms
16:26:45,816 DEBUG || - [JobRepository] hz.xenodochial_swanson.cached.thread-17 - [10.0.0.37]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 475ms
16:26:51,722 DEBUG || - [JobRepository] hz.xenodochial_swanson.cached.thread-14 - [10.0.0.37]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 864ms
```
this is after 16 hours:
```
05:54:47,461 DEBUG || - [JobRepository] hz.xenodochial_swanson.cached.thread-56 - [10.0.0.37]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 6099ms
05:54:58,793 DEBUG || - [JobRepository] hz.xenodochial_swanson.cached.thread-15 - [10.0.0.37]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 6162ms
05:55:09,061 DEBUG || - [JobRepository] hz.xenodochial_swanson.cached.thread-49 - [10.0.0.37]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 5086ms
```
and this is after 1.5day (ignore cluster name, the log is taken from different soak test run):
```
09:57:48,966 DEBUG || - [JobRepository] hz.agitated_keldysh.cached.thread-45 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 1501616ms
10:37:28,477 DEBUG || - [JobRepository] hz.agitated_keldysh.cached.thread-53 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 2368938ms
12:30:09,645 DEBUG || - [JobRepository] hz.agitated_keldysh.cached.thread-34 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Job cleanup took 6748548ms
```

`PartitionContainer` holds maps with resources for every job (maps with name like `__jet.resources.0663-20d6-5001-0003`). At the end of the soak tests (when job cleanup is high) there are data for ~10000 jobs.

![Screenshot from 2021-06-25 10-26-16](https://user-images.githubusercontent.com/2005025/125921155-62f2f8c2-ee26-4db6-bf67-f8a82579ae08.png)

The log contains a lot of messages like:
```
12:59:57,970 DEBUG || - [JobRepository] hz.agitated_keldysh.cached.thread-22 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Deleting job resource map __jet.resources.0663-20d6-5001-0003 because the map was created long ago and job record or result still doesn't exist
```
it holds the data for given job for ~12hours. It was started 12 hours before:
```
01:00:53,252  INFO || - [EnterpriseJobCoordinationService] hz.agitated_keldysh.cached.thread-22 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Starting job 0663-20d6-5001-0003 based on submit request
01:01:00,429 DEBUG || - [InitExecutionOperation] hz.agitated_keldysh.cached.thread-22 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Initializing execution plan for job 0663-20d6-5001-0003, execution 0663-1ecb-817b-0001 from [10.0.0.28]:5701
01:01:11,239  INFO || - [JobExecutionService] hz.agitated_keldysh.cached.thread-22 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Execution plan for jobId=0663-20d6-5001-0003, jobName='AttachMLModelTest_100mbDirectory2110', executionId=0663-1ecb-817b-0001 initialized
```
and completed in that time (soak tests are running on cluster with 4 nodes):
```
$ grep "AttachMLModelTest_100mbDirectory2110" -R . | grep  "completed"
./54.146.110.64/hazelcast-jet.log:01:02:07,489 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-3 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Execution of job 'AttachMLModelTest_100mbDirectory2110', execution 0663-1ecb-817b-0001 completed
./54.146.110.64/hazelcast-jet.log:01:02:18,512  INFO || - [MasterJobContext] hz.agitated_keldysh.cached.thread-19 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] Execution of job 'AttachMLModelTest_100mbDirectory2110', execution 0663-1ecb-817b-0001 completed successfully
./54.146.110.64/hazelcast-jet.log:01:02:18,512 DEBUG || - [EnterpriseJobCoordinationService] hz.agitated_keldysh.cached.thread-19 - [10.0.0.28]:5701 [jet] [5.0-SNAPSHOT] job 'AttachMLModelTest_100mbDirectory2110', execution 0663-1ecb-817b-0001 is completed
./34.230.3.56/hazelcast-jet.log:01:02:07,484 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-8 - [10.0.0.54]:5701 [jet] [5.0-SNAPSHOT] Execution of job 'AttachMLModelTest_100mbDirectory2110', execution 0663-1ecb-817b-0001 completed
./54.198.248.118/hazelcast-jet.log:01:02:07,485 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-6 - [10.0.0.101]:5701 [jet] [5.0-SNAPSHOT] Execution of job 'AttachMLModelTest_100mbDirectory2110', execution 0663-1ecb-817b-0001 completed
./18.232.102.19/hazelcast-jet.log:01:02:07,815 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-10 - [10.0.0.110]:5701 [jet] [5.0-SNAPSHOT] Execution of job 'AttachMLModelTest_100mbDirectory2110', execution 0663-1ecb-817b-0001 completed
```

We haven't seen this increasing cleanup time in Jet 4.5. Executed soak tests are the same as in Jet 4.5 (just migrated to Hazelcast 5.0).

**Comment by gurbuzali** [comment]
we periodically (5 seconds) scan the maps to clear the ones belonging to the finished jobs. this scanning does not take too much time and it is not the one keep increasing. around 80-100 maps are found at each scan, at the beginning the cleaning part takes around 600ms, each map#destroy around 3-8ms. after couple of hours (15-20) in the test, each map#destroy increases to 200-300ms thus whole clean process to 20-25 seconds.

map#destroy is a costly operation, it sends an operation to each partition and waits for the results, not async. These individual operations contend with other update operations on the partition. This still does not explain why the time it takes to destroy a map increases gradually. The update rate of the partitions does not (should not) increase during the tests, we expect it to stay flat after couple of minutes to the testing.

**Comment by frant-hartm** [comment]
I have couple more observations:

- after some time most map#destroy operations take ~ hundredths ms to complete, however, some take much longer even more than 2 seconds, there is no full GC in any member that could be correlated with that
- we have a roughly constant number of jobs submitted, it fluctuates between 20 - 40 / s - some jobs are faster to complete, some take longer, once the cluster slows down this slows down as well, but not significantly
- once the scan time reaches over some threshold it flips over and starts to grow faster - the reason is that within the cleanup time + 5 s (interval between end of a scan and stat of next scan) we are still submitting and finishing more jobs (-> creating more __jet.results*` maps) than we are able to cleanup
- partitions and data are evenly distributed, each member owns 16 partitions, roughly same amount of data - each member has 16 vCPUs
- CPU usage is ~ 70 % on master node, ~ 40 % on other nodes
- memory consumption slowly increases on all nodes, which can be explained by a growing number of `__jet.results*` maps
- the message `Deleting job resource map " + map.getName() + " because the map was created long ago and job record or result still doesn't exist` is not relevant, I have seen the increase of cleanup to 10s+ without this message occurring

**Comment by frant-hartm** [comment]
It seems we have an issue with the design of the cleanup job.

We run clean up when there are more than 1050 results and then schedule another cleanup in 5 seconds.

The cleanup itself takes some time, more jobs are finished in that time, they are not cleaned up immediately but in the next run. So in the next run, there are more jobs to clean up, which takes more time -> more jobs are finished during the job cleanup and it goes into a cycle where the time of the cleanup grows. This is not a new issue but it is more visible because we submit a lot more jobs with introduction of light jobs.

The solution might be to schedule at a fixed rate of 5 s from the previous start of the cleanup, not from cleanup end. However if more jobs are completed during cleanup than we can clean it doesn't resolve the issue.

**Comment by viliam-durina** [comment]
Light jobs have nothing to clean up. Nothing is stored in any IMap for a light job.

**Comment by frant-hartm** [comment]
Yes.

By 

> we submit a lot more jobs with introduction of light jobs.

I mean that with the changes for light jobs the job submission is now faster, some tests were limited by submission time with very little sleep between job submissions and the jobs themselves took almost no time (few ms).

So this issue existed for a long time, but is now more visible.

**Comment by k-jamroz** [comment]
In https://github.com/hazelcast/hazelcast-jet/pull/1493/ eager deletion of job resource map on job completion was removed from `deleteJob` but the description mentions only optimization (not create unneeded IMap) and not any problems due to premature (if that is possible?) deletion of the IMap. As normal jobs are coordinated quite strictly, after `deleteJob` no stray execution should ever need the resources.

**Comment by k-jamroz** [comment]
Additional observation, which might help is that `JobResults` are by default kept for 7 days and only 1000 most recent. They  are all fetched during cleanup. It might help to adjust `hazelcast.jet.job.results.max.size` and `hazelcast.jet.job.results.ttl.seconds` but on the other hand the defaults should be safe.
