### ISSUE TITLE
Make serializable classes less fragile to small build and implementation changes

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#19320]
The file - https://github.com/hazelcast/hazelcast/blob/master/extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/AwsConfig.java#L30 

is only marked as `Serializable `without any UUID so it requires a precise build match to be compatible between client/server. It doesn't even work against the distribution if you use `jar-with-dependencies` vs the normal jar.

**Comment by mmedenjak** [comment]
Moving to 5.0.1. The issue was introduced with https://github.com/hazelcast/hazelcast-jet/pull/2656 and was part of jet since 4.4. Even more-so, this is not just an issue about `AWSConfig`, but opens up the question - how many more classes are there that are java `Serializable` and also need to be fixed. I can see at least one and anecdotally I know that jet has been heavy on java serialisation. 

So proposing this be addressed after 5.0 systematically. cc @gurbuzali @frant-hartm any thoughts?
