### ISSUE TITLE
Consider removal of implicit SQL mappings

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#19387]
In the current version, one can query _non-empty_ IMaps without explicitly creating a mapping. From the feedback we see it causes some confusion, mainly:
- doesn't work for empty maps - this is as specified, but it's how you always start off when experimenting.
- it randomly might not work even for non-empty maps, because by _non-empty_ we actually mean that the map must have an entry on each cluster member (primary or a backup), which the users might not understand. In clusters larger than the number of replicas one entry isn't enough.
- doesn't work for JSON-typed keys or values (this could be improved by assuming all entries have the same fields though)

The only plausible use case for the feature is querying of maps in existing production clusters.

Couple more arguments in favor of removal of this feature: 
- your first command is typically a `CREATE` command, not `INSERT` or `SELECT`
- the feature can be re-added in the future, but cannot be removed if we release it now due to b-w compatibility

This issue serves for the discussion of the topic. (cc @Holmistr).

**Comment by Holmistr** [comment]
Related Slack discussion: https://hazelcast.slack.com/archives/CJZ745RRT/p1629795049076700

**Outcomes:**

* Using implicit mappings (querying maps without previously executing `CREATE MAPPING`) will be prohibited. In short, the reasons are confusing UX (most common feedback from the Hackathon, issue with "empty" maps) and possibility to add it back if we receive the feedback it's needed. Just FYI - I looked at how Ignite does it and you also always have to define the "schema" before you can query.

* Using implicit columns when doing `CREATE MAPPING` without column list will be allowed. This will work nicely when you use serialization type such as Portable as you have basically defined the column by the fields in the class definition.

We need to brainstorm about the error messages and how to make them really guiding the user. The general rule should be if a user has to open up the documentation, that's already bad.

**Comment by Holmistr** [comment]
This topic appears to be a bit controversial and a lot of people is asking why we did. Therefore, let me summarize the reasoning here once more for the future reference.

**What is implicit mappings?**
Implicit mapping is a "feature" where Hazelcast itself tries to deduce the schema automatically of your already existing pre-populated map. 

**Decision made**
Remove implicit mappings in 5.0.

**Reasoning for removal**
* Implicit mappings "deduced" the schema by sampling the map. That caused a nasty error during getting started experience - if not every member contains at least one entry in the map (which happens easily when e.g. you have a cluster of 3 members and you put an entry and try the SELECT statement right away), the query can end up on a member that doesn't have an entry (it's chosen randomly) and the query fails. Even worse, it might happen that if you retry the same exact query right after it, all of a sudden it can succeed (or vice versa) as it landed on a "lucky" member. This creates terrible UX and was the most common feedback during the internal hackathon (and on a few other occassions like in HZ Cloud). Forcing the user to create the mapping explicitly eliminates the problem.
* Future backward compatibility - right now, we don't support features such as nested types. The objects are resolved as `OBJECT` type currently but when we officially support it, it will have to resolve to a special type (e.g. `INNER_OBJECT`, making it up). When running e.g. `SELECT * FROM person` with implicit mappings, we have two options for a nested object:
    * Map it and return it - the problem is backwards compatibility. When we introduce nested type in the future, all of a sudden the same query will return a different type of field, which can lead to breaking the user code without any notice -> breaking backwards compatibility which is not acceptable for a production ready feature.
    * Not map it (= ignore it) for now - that means that the field is not returned. So even if you know you have e.g. `Address address` field in your `Person` class and you do `SELECT address FROM person`, the address column will not be returned unless you create an explicit mapping (using `CREATE MAPPING`) -> confusing user experience: "Hey, but the field is there!"
* You could `SELECT` the existing map without `CREATE MAPPING` explicitly called (if you don't hit the issues above), but if you wanted to start with an empty map with `INSERT INTO`, you have to issue `CREATE MAPPING` first -> again, confusing UX.

Additional points:
* In all SQL based products, you always define the schema at least ones e.g. through `CREATE TABLE`. This is not something strange in SQL world.
* If we add/keep the implicit mappings in 5.0, we can't remove it later due to backwards compatibility. However, the other way around is possible - don't include it in 5.0, collect feedback and if there's a demand, introduce it later on.

Reasoning summary:
There are major usability issues that we discovered during our testing/hackathon. It caused confusing UX. From that sense, it's questionable whether the implicit mappings benefits overcomes the drawbacks. Since we don't have any data to support either side, we choose the safer bet where we can introduce it later if needed.
