### ISSUE TITLE
Close BufferObjectDataInput in MulticastService when packet version mismatched

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19692]
Probably `finally` block should be moved to the outer `try`

https://sonarcloud.io/project/issues?fileUuids=AW9qkInwkrN6v4yKaOB1&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by Tarankalra** [comment]
Hi @ldziedziul, Can I take this task ?

**Comment by ldziedziul** [comment]
Yes, sure!

**Comment by Tarankalra** [comment]
@ldziedziul As I am new to this project, want to discuss the approach with you first so that there are no repercussions of what I change. I am thinking to close the BufferObjectDataInput just before returning null in case the version is mismatched at this line https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/MulticastService.java#L269. What do you think about this?

**Comment by ldziedziul** [comment]
Not relevant anymore as BufferObjectDataInput is no more Closeable
