### ISSUE TITLE
Log4J CVE-2021-44228  -> CVE-2021-45046

### ISSUE THREAD

**Issue by Sheepux** [hazelcast/hazelcast#20208]
Following the release of 4.2.3 adressing the CVE issue for log4j by updating the lib 2.15.
Can you adress the second CVE requiring to update log4j to 2.16 ? :)
The dependabot already created the MR. I'm creating this ticket to bring awareness on this issue as the first fix is no longer considered as enougth.
MR https://github.com/hazelcast/hazelcast/pull/20184 

Context:
https://logging.apache.org/log4j/2.x/security.html

**Comment by kwart** [comment]
Thank you for filling the issue. We are aware of the second CVE and we plan to upgrade the Log4j version in Hazelcast products. This issue is not so critical as the original CVE-2021-44228 which led to the fast upgrade to 2.15.0. 
Hazelcast findings (for both CVEs) are tracked in the related security advisory:
https://support.hazelcast.com/s/article/Security-Advisory-for-Log4Shell

The [CVE-2021-45046](https://nvd.nist.gov/vuln/detail/CVE-2021-45046) has CVSS base score 3.7 (low).
Our investigations show that Hazelcast's default logging patterns are not vulnerable to the DOS attack.
As customers may use their custom logging configurations we will update the log4j in the next versions.

**Comment by Sheepux** [comment]
FYI, severity on CVE-2021-45046  was increased to 9.0 https://logging.apache.org/log4j/2.x/security.html
details:
https://www.lunasec.io/docs/blog/log4j-zero-day-severity-of-cve-2021-45046-increased/
https://twitter.com/pwntester/status/1471465662975561734

**Comment by kwart** [comment]
Thanks for sharing.
The updates are merged now.

**Comment by kwart** [comment]
Closed by #20184.

**Comment by Sheepux** [comment]
Thanks to the team for the reactivity
