### ISSUE TITLE
[HZ-550] Make the Compact format the default for SQL mappings

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20341]
In order to simplify Compact serialization usage and to make it the default choice, we can make it the default format for mappings.

The following command will not need any OPTIONS:
```
CREATE MAPPING foo_mapping (
  __key INT,
  field1 VARCHAR,
  field2 INT
)
TYPE IMap
```
It will behave as if the user used the following options:
```
OPTIONS (
  'keyFormat'='java',
  'keyJavaClass'='java.lang.Integer',
  'valueFormat'='compact',
  'valueTypeName'='foo_mapping.value' -- <mapping_name>+".value"
)
```

**Comment by AllyKaz** [comment]
From what I can see from the cli and in KvMetaDataResolvers there's currently no default behavior for any keyFormat or valueFomat. So the above fails with a QueryException because of a missing keyFormat option. Are we looking to simply make compact the default format for everything, or to make it contingent on some other factor?

**Comment by k-jamroz** [comment]
Similar thing will be available in `CREATE TABLE`, default for MAPPING could be error-prone if the IMap exists.
