### ISSUE TITLE
SQL returning HeapData object

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#21276]
**Describe the bug**
SELECT returns heap object

**Expected behavior**
SELECT returns row

**To Reproduce**
Run
```
import java.util.Iterator;
import java.util.List;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.HazelcastJsonValue;
import com.hazelcast.sql.SqlRow;

public class Application {
	private static final String MAP_NAME = "m";

	public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.getJetConfig().setEnabled(true);
		config.getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
		config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
		
		HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);

		String mapping = "CREATE MAPPING " + MAP_NAME
				+ " (\"__key\" VARCHAR,"
				+ "  \"width\" INTEGER)"
				+ " TYPE IMap  OPTIONS ("
				+ " 'keyFormat' = 'java', 'keyJavaClass' = 'java.lang.String',"
				+ " 'valueFormat' = 'json-flat' )";
		hazelcastInstance.getSql().execute(mapping);
		for (String key : List.of("one", "two", "three", "four", "five")) {
			hazelcastInstance.getMap(MAP_NAME).put(key, 
					new HazelcastJsonValue("{\"width\":" + key.length() + "}"));
		}
		
		String sql1 = "SELECT __key, width FROM " + MAP_NAME + " ORDER BY width DESC LIMIT 1";
    	String sql2 = "SELECT __key FROM ("
    			+ "SELECT __key, MAX(width) FROM " + MAP_NAME + " GROUP BY __key ORDER BY 2 DESC) LIMIT 1";
    	String sql3 = "SELECT __key FROM ("
    			+ "SELECT __key, MAX(width) FROM " + MAP_NAME + " GROUP BY __key ORDER BY 2 DESC LIMIT 1"
    			+ ")";
		
		for (String sql : List.of(sql1, sql2, sql3)) {
			System.out.println(sql);
			try {
				Iterator<SqlRow> iterator = hazelcastInstance.getSql().execute(sql).iterator();
				while (iterator.hasNext()) {
					System.out.println(iterator.next());
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		
		hazelcastInstance.shutdown();
		System.exit(0);
	}
	
}
```

**Additional context**
`sql2` goes wrong above.
Tried on 5.1.1 and `Hazelcast Platform 5.2-SNAPSHOT (20220420 - 817afaa)`

**Comment by Fly-Style** [comment]
Try to replace 
```
while (iterator.hasNext()) {
    System.out.println(iterator.next());
}
```

with

```
 while (iterator.hasNext()) {
    SqlRow next = iterator.next();
    System.out.print("| ");
    for (int i = 0; i < next.getMetadata().getColumnCount(); ++i) {
        System.out.print(next.getObject(i) + " | ");
    }
    System.out.println();
}
```

It returns 
```
| three | 5 |
```

**Comment by viliam-durina** [comment]
The reason for this is here: https://github.com/hazelcast/hazelcast/blob/5be72554462ed084f0412e2ce15248293d4ee211/hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java#L111

I've had serious issues with `toString` triggering a lazy load in the past: I've had an issue with failed lazy load, but when debugging it, it worked, because displaying the `toString` in the debugger triggered the load while it still was valid. `toString` should be side-effect free. It's for debugging.

**Comment by Placentra** [comment]
Hello I´m using hazelcast for just a couple of days on a NODE.js, however for some reason its behaviour is really weird. The values() method is only returning heap data. Only if I use entrySet() I can actually get the stored objects from the map. How can I get rid of this?

This is how I´m caling it:
await eventsDataHC.values(predicate)

Also no matter what I try, the predicates are not working at all. no matter which one I try.

If i store a regular object {type:22} as a value and then I call for example:
const predicate = Predicates.equal('type', 22);
console.log(await eventsDataHC.values(predicate));

I get nothing back. Only some internal codes in the response. Please help.

**Comment by srknzl** [comment]
@Placentra values() method does not accept a predicate. You have to use valuesWithPredicate. 

Regarding heapData in values(), can you send your complete code, the parts enough to reproduce it? This way we don't know what you store in the IMap. 

Please open an issue in hazelcast-nodejs-client repo if you still have a problem.

**Comment by Placentra** [comment]
Hello srknzl, I think we are on a good track. I just tried the valuesWithPredicates and it actually returned a single result (which is correct), but its in the form of heap data :-D. Following are the details:

1) after fetching eventsData from SQL, I populate the eventsData (regular JS Map object):
![image](https://github.com/hazelcast/hazelcast/assets/119671412/a8d14069-e689-4edd-902a-d3dc9d9d77af)

2) I then populate the hazelcast map eventsDataHC like this:
![image](https://github.com/hazelcast/hazelcast/assets/119671412/e107c9b8-dcd4-46e2-abaf-62e8f538e828)

3) the map is correctly populated, I¨m getting back results when using the get or getAll method.

4) PROBLEM 1 - the value method doesn´t work, it is only returning heap data (in correct quantities, so it works, I can tell):
5) PROBLEM 2 - even the values with predicates returns heap data:

THIS:
![image](https://github.com/hazelcast/hazelcast/assets/119671412/923d8838-1f6d-426e-800a-4d7503e435ba)

PRINTS THIS:
![image](https://github.com/hazelcast/hazelcast/assets/119671412/67ed6a6c-5a2d-4845-be87-52d75c801b31)
![image](https://github.com/hazelcast/hazelcast/assets/119671412/8c7dc6b2-eab6-450c-b49f-45383ef8877e)

AND THE SECOND CONSOLE LOG PRINTS THIS:
![image](https://github.com/hazelcast/hazelcast/assets/119671412/532ea724-cac0-41c1-8d27-19ad1211e29c)

You can see the single result there, which is correct, so at least that is working, I´m happy.

LASTLY PROBLEM 4. Maybe its not a problem and it is supposed to be like this, I´m just asking:
in order to get an array of values from the getAll method, I have to always use this helper function:
This is the map call:
![image](https://github.com/hazelcast/hazelcast/assets/119671412/738df6ae-2691-496f-bcac-b536d0f129c9)

and this is what I always need to do in order to get a clean array with values:
![image](https://github.com/hazelcast/hazelcast/assets/119671412/5a66ca6c-e3bb-4f87-8338-385172b1c64d)
I suppose this won´t be an issue once we get the values() method running, but I just find it strange, that the getAll method is actually returning an array of arrays, instead of just entries.

I thank you for all help sir.
Mathew.

**Comment by Placentra** [comment]
Hello, please srknz, would you please take a quick look at my message? I have written into the hazelcast comunnity, but its been almost a week and no answer :-(

**Comment by srknzl** [comment]
@Placentra Sorry I was busy and I don't check github notifications much these days. Next time, try mentioning me.

**Comment by srknzl** [comment]
@Placentra I advise you t o check the API documentation of hazelcast-node-client and ReadOnlyLazyList in particular. Here you are: https://hazelcast.github.io/hazelcast-nodejs-client/api/5.3.0/docs/classes/core_ReadOnlyLazyList.ReadOnlyLazyList.html

**Comment by Placentra** [comment]
Hi @srknzl, dude I´m really sorry, but I´m really very close to be pissed off. I just spent a week trying to figure this out. Now you point me to a completely useless totaly not understandable documentation. I actually tryid to use my premium GPT and the code it gave me (eventhough it worked) is ridiculously verbose. And procesing ONLY A SINGLE RESULT, the server response is 95 miliseconds. WHAT THE HELL. 

Please, all I need is to get my objects back. Thats all, I HAVE ABSOLUTELY zero clue why is everything so overcomplicated and why no one who writes these docs can speak in human language. Your whole documentation has zero mention about "valuesWithPredicates", I would have never ever figured that out. Also there is absolutely no mention about .getSerializationService(), which I still have no idea if I need or not. Do I use the serialization service inside the readonlylazylist? Or do I need to request it from the client.?

AND BY THE WAY. doesn´t this post-processing completely most of the advantege your system should bring?? I basicaly need to completely overhaul everything I receive in the application layer. WTF? Sory dude, I´m out of patience. PLEASE, PLEASE, PLEASE, help me with this. Give me 5 lines of code, how to create predicate, use it to retrieve values and then do whatever to actually console.log the data.
PLEASE

**Comment by Placentra** [comment]
Nevermind, I got it working, finally. But let me tell you. You guys seriously need to consider complete chang the rhetorics of your docs. I would probably never success without GPT and I´m not some kind of a dummy. Your docs are overwhelming, chaotic and absolutely not user friendly in terms of understandability.

**Comment by srknzl** [comment]
@Placentra I bet you are not even aware of this documentation which is as expected much better than an API documentation: https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/DOCUMENTATION.md

Hope I could help.
