### ISSUE TITLE
com.hazelcast.client.ClusterNameTest.test_clusterName_overClientInstance [API-1390]

### ISSUE THREAD

**Issue by bpoplawski** [hazelcast/hazelcast#21311]
master (commit 5be72554462ed084f0412e2ce15248293d4ee211 )

Failed on Microsoft JDK11: [INSERT_LINK_TO_JENKINS_TEST_RESULT_HERE](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK11/10/consoleFull)

<details><summary>Stacktrace:</summary>

```
com.hazelcast.client.HazelcastClientNotActiveException: Client is not active.
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getClient(HazelcastClientProxy.java:304)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getName(HazelcastClientProxy.java:85)
	at com.hazelcast.client.ClusterNameTest.test_clusterName_overClientInstance(ClusterNameTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_clusterName_overClientConnectedEvent in 0.781 seconds.
01:55:10,199  INFO |test_clusterName_overClientInstance| - [LifecycleService] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
01:55:10,199  WARN |test_clusterName_overClientInstance| - [Node] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Terminating forcefully...
01:55:10,199  INFO |test_clusterName_overClientInstance| - [Node] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
01:55:10,199  INFO |test_clusterName_overClientInstance| - [Node] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down node engine...
01:55:10,201  INFO |test_clusterName_overClientInstance| - [NodeExtension] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
01:55:10,201  INFO |test_clusterName_overClientInstance| - [Node] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
01:55:10,201  INFO |test_clusterName_overClientInstance| - [LifecycleService] Thread-31784 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
```

</details>

**Comment by olukas** [comment]
Failed on RedHatJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK17/11/testReport/com.hazelcast.client/ClusterNameTest/test_clusterName_overClientInstance/

**Comment by olukas** [comment]
Failed on CorrettoJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK11/169/testReport/com.hazelcast.client/ClusterNameTest/test_clusterName_overClientInstance/

**Comment by bpoplawski** [comment]
Failed on master, MacOS, Zulu JDK8 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK8/66/testReport/com.hazelcast.client/ClusterNameTest/test_clusterName_overClientInstance/

**Comment by ufukyilmaz** [comment]
Failed on the PR builder run with the same exception: - http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/11177/testReport/junit/com.hazelcast.client/ClusterNameTest/test_clusterName_overClientInstance/

**Comment by mdumandag** [comment]
This one is also fixed with https://github.com/hazelcast/hazelcast/pull/21718.

Before that PR, we were using the same client name in all tests in this suite. Plus, there was a bug in the test factory class.

One possible execution of code that might lead to such errors is as below:
- We create a client with name `aClient`, put the associated instance future to `HazelcastClient#CLIENTS` map(which is static, so shared between tests). Let's call it client1
- We call shutdown on client1, but not yet remove the instance future from the map, and set it's proxy to null (see `HazelcastClient#shutdown(String)`)
- We start a new client with the same name, say client2, and put the associated instance future to same map as well. This effectively overwrites the previous future in that map for the same client name. This can happen because before the linked PR, we were having no checks on that static map, but doing some checks on the test factory, which is separate per test.
- Now, the call to shutdown client1 continues, we remove its future, and set its proxy to null.
- Then, we we try to getName from the client2, since the proxy is set to null, we receive the error mentioned on the issue.

To fix this problem, we would either need to use random names in the tests, or fix the test factory. We did both in the linked PR, so we can close this issue.
