### ISSUE TITLE
Fix JSON/VARCHAR comparison in SQL [HZ-1706]

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#22671]
The `=` SQL operator works for JSON=JSON, but not for JSON=VARCHAR. This is illogical. Due to b-w compatibility we should implement JSON=VARCHAR comparison. It should work as string comparison, that is comparing char-by-char, not semantically. JSON=JSON also works this way.

This test can be added to `SqlJsonTypeTest` and should pass: 
```java
    @Test
    public void test_jsonComparedAsVarchar() {
        // for the `=` operator, we convert JSON operands to VARCHAR

        assertRowsAnyOrder("SELECT " +
                        // json-json not equal
                        "CAST('{\"f1\":42, \"f2\":43}' AS JSON)=CAST('{\"f2\":43, \"f1\":42}' AS JSON)," +
                        // json-json equal
                        "CAST('{\"f1\":42, \"f2\":43}' AS JSON)=CAST('{\"f1\":42, \"f2\":43}' AS JSON)," +
                        // json-varchar not equal
                        "CAST('{\"f1\":42, \"f2\":43}' AS JSON)='{\"f2\":43, \"f1\":42}'," +
                        "'{\"f1\":42, \"f2\":43}'=CAST('{\"f2\":43, \"f1\":42}' AS JSON)," +
                        // json-varchar equal
                        "CAST('{\"f1\":42, \"f2\":43}' AS JSON)='{\"f1\":42, \"f2\":43}'," +
                        "'{\"f1\":42, \"f2\":43}'=CAST('{\"f1\":42, \"f2\":43}' AS JSON)",
                rows(6, false, true, false, false, true, true));
    }
```

We also need to check the behavior for other comparison operators (`!=`, `>`, `>=`, ...), it should also work as with VARCHARs.

If we introduce JSONB in the future, those values should be compared semantically. If combining JSON or VARCHAR with JSONB, convert to JSONB, which will involve parsing.

**Comment by k-jamroz** [comment]
It seems that it is the easiest to allow JSON->VARCHAR coertion in `HazelcastTypeCoercion` in addition to existing VARCHAR->JSON. This may also impact some other places (operators) which expect VARCHAR - they might start accepting JSON automatically. It seems that this is not the case for string functions (UPPER, SUBSTRING), they are not impacted.

Such implementation will allow also greater/less comparison, which does not make much sense for JSON, but can be defined as string comparison. It is easier to allow it, because to disallow it we would have to implement specific validation or coertion rules.

**Comment by k-jamroz** [comment]
I found that the change impacts row conversion, in particular JSON column in result will be converted to VARCHAR on INSERT/SINK (previously it failed). See `RowAssignmentTypeCoercionTest`
