### ISSUE TITLE
Condition broken

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#2272]
Run it a few times. One of the times it will not complete. Perhaps deadlock. Perhaps a signal gets lost.

    package com.hazelcast.concurrent.lock;

    import com.hazelcast.core.Hazelcast;
    import com.hazelcast.core.HazelcastInstance;
    import com.hazelcast.core.ICondition;
    import com.hazelcast.core.ILock;
    import com.hazelcast.test.HazelcastParallelClassRunner;
    import com.hazelcast.test.HazelcastTestSupport;
    import com.hazelcast.test.annotation.SlowTest;
    import org.junit.Test;
    import org.junit.experimental.categories.Category;
    import org.junit.runner.RunWith;

    @RunWith(HazelcastParallelClassRunner.class) 
    @Category(SlowTest.class)
    public class ConditionStressTest extends HazelcastTestSupport {

    private static volatile Object object;
    public static final int ITERATIONS = 1000000;
    public static final int PRODUCER_COUNT =2;
    public static final int CONSUMER_COUNT =2;

    @Test
    public void test() {
        HazelcastInstance hz = Hazelcast.newHazelcastInstance();
        //Hazelcast.newHazelcastInstance();
        ILock lock = hz.getLock(randomString());
        ICondition condition = lock.newCondition(randomString());

        ConsumerThread[] consumers = new ConsumerThread[CONSUMER_COUNT];
        for(int k=0;k<consumers.length;k++){
            ConsumerThread thread = new ConsumerThread(k, lock, condition);
            thread.start();
            consumers[k]=thread;
        }

        ProducerThread[] producers = new ProducerThread[PRODUCER_COUNT];
        for(int k=0;k<producers.length;k++){
            ProducerThread thread = new ProducerThread(k, lock, condition);
            thread.start();
            producers[k]=thread;
        }

        assertJoinable(600,producers);
        assertJoinable(600,consumers);
    }

    class ProducerThread extends Thread {
       private final ILock lock;
        private final ICondition condition;

        ProducerThread(int id, ILock lock, ICondition condition) {
            super("ProducerThread-" + id);
            this.lock = lock;
            this.condition = condition;
        }

        public void run() {
            try {
                for (int k = 0; k < ITERATIONS; k++) {
                    doRun();

                    if (k % 100 == 0) {
                        System.out.println(getName() + " is at: " + k);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        private void doRun() throws InterruptedException {
            lock.lock();

            try {
                while (object != null) {
                   condition.await();
                }
                object = "";
                condition.signalAll();
            } finally {
                lock.unlock();
            }
        }
    }

    class ConsumerThread extends Thread {
        private final ILock lock;
        private final ICondition condition;

        ConsumerThread(int id, ILock lock, ICondition condition) {
            super("ConsumerThread-" + id);
            this.lock = lock;
            this.condition = condition;
        }

        public void run() {
            try {
                for (int k = 0; k < ITERATIONS; k++) {
                    doRun();
                    if (k % 100 == 0) {
                        System.out.println(getName() + " is at: " + k);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        private void doRun() throws InterruptedException {
            lock.lock();

            try {
                while (object == null) {
                    condition.await();
                }
                object = null;
                condition.signalAll();
            } finally {
                lock.unlock();
            }
        }
    }
    }

**Comment by StanAccy** [comment]
Is this issue still present in the 3.5.3 codebase?  We have a client using 3.5.3 that is using IConditions and Ive seen some odd behavior.  My initial assumption was application level code, but if this is a possibility, I'll widen my analysis.

**Comment by pveentjer** [comment]
@sancar I reran the test and I see the ICondition is still broken. Has the ICondition been refactored and this test been taken into consideration?

**Comment by sancar** [comment]
@pveentjer No one worked on a solution for this as far as I know.

**Comment by jerrinot** [comment]
I did some investigation and here are my findings: 
### Intro
- `await()` method invokes [2 operations](https://github.com/hazelcast/hazelcast/blob/ae4e6e8a8211f695a851c2fe8d9f6f53ad042751/hazelcast/src/main/java/com/hazelcast/concurrent/lock/ConditionImpl.java#L79) : `BeforeAwaitOperation` and `AwaitOperation`
- [`BeforeAwaitOperation`](https://github.com/jerrinot/hazelcast/blob/b27e0cf5783942b6d6f2c4e59e332ca714ad5ea7/hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BeforeAwaitOperation.java#L62-L63) register itself as a waiter and then releases a lock. 
- `AwaitOperation` runs `shouldWait()` to checks if there is a [signal available](https://github.com/jerrinot/hazelcast/blob/b27e0cf5783942b6d6f2c4e59e332ca714ad5ea7/hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/AwaitOperation.java#L78). If so then the `run()`  method consumes the signal and the waiter is removed. 

### Where is the problem
I used the [stress test](https://github.com/hazelcast/hazelcast/issues/2272#issue-31275548) created by @pveentjer 

1. Consumer calls the `condition.await()` -> `BeforeAwaitOperation` executed -> waiter is registered and a lock is released
2. Producer acquires the lock and calls `condition.signalAll()` -> this [creates a single](https://github.com/jerrinot/hazelcast/blob/b27e0cf5783942b6d6f2c4e59e332ca714ad5ea7/hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BaseSignalOperation.java#L57-60) `ConditionKey` because we have a single waiter and this point. The important thing here is that the `ConditionKey` is not linked to the Consumer which registered itself as a waiter in the previous step. Only a `conditionId` and `key` is used to create the `ConditionKey`. `ThreadId` is NOT used here. 
3. Producer releases the lock
4. Producer re-acquires the lock and calls `condition.await()`  -> There is a signal available -> It's [consumed](https://github.com/jerrinot/hazelcast/blob/b27e0cf5783942b6d6f2c4e59e332ca714ad5ea7/hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/AwaitOperation.java#L65-L66) -> the Producer thread is unblocked. The Producer ate its own signal!
5. Producer calls `icondition.await()` again -> this time there is no signal  available (The Consumer already ate it!) -> The `AwaitOperation` is blocked
6. Consumer invokes `AwaitOperation` -> but there is no signal available -> it's blocked
7. Dead-lock


There are 2 possible ways to tackle this problem: 
1. the non-atomic `BeforeAwaitOperation` and `AwaitOperation` are suspicious. I (still) don't have deep-enough understanding of the `ICondition` implementation to be able to tell whether it's needed at all. 
2. We should use `threadId` from [`Waiter`](https://github.com/jerrinot/hazelcast/blob/eef987b9920f3f7b4c506e433b0d067cab9ba93c/hazelcast/src/main/java/com/hazelcast/concurrent/lock/ConditionInfo.java#L97) when creating a [`ConditionKey`](https://github.com/jerrinot/hazelcast/blob/b27e0cf5783942b6d6f2c4e59e332ca714ad5ea7/hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BaseSignalOperation.java#L57) so we only create a signal which can be consumer only by a thread which actually called `await()`

**Comment by jerrinot** [comment]
fixed by #8269
