### ISSUE TITLE
Upgrade dependencies to use jakarta.* namespaces instead of javax.*

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#23515]
See e.g. https://github.com/hazelcast/hazelcast/pull/23182

We cannot upgrade, because new RabbitMQ's version uses Jakarta API. We need to migrate at some point

**Comment by Verdoso** [comment]
Any plan/idea about this?
In our case, we are contemplating migrating some apps so ElasticSearch 8, but in order to use Spring Data ElasticSearch with ElasticSearch 8, you have to migrate to Spring Boot 3, and that means using jakarta classes instead of javax.
So, we have to choose whether to stop the migration to ElasticSearch 8 or drop Hazelcast. Right now I'll probably convince them to wait, but I'm not sure for how long, specially if there are no plans to fix it. 
I believe we are not going to be the only ones with this kind of issues, because right now Spring Boot 3 and Hazelcast is a no-no and features like GraalVM, ElasticSearch 8 etc. and starting to require that.

**Comment by dcokan** [comment]
Is that in scope for `5.4.0` ? I can see #24804 was merged that brings `jakarta.jms`

**Comment by TomaszGaweda** [comment]
Yes, it's in the scope of 5.4.0 :)
