### ISSUE TITLE
Be able to remove item from Map/MultiMap without returning values

### ISSUE THREAD

**Issue by mjgp2** [hazelcast/hazelcast#2719]
It would be optimal for many use cases to have a MultiMap#remove(key,returnValues) operation, and the same for IMap.

**Comment by mdogan** [comment]
`IMap` already has `void delete(key)` method.

**Comment by vmarquez** [comment]
I'd like to give this a shot.  Sounds like I need to add a `delete` method to hazelcast-client-protocol first, then add the changes to the MultiMap proxy/impl/operation in the hazelcast project right?

**Comment by mmedenjak** [comment]
@vmarquez right, just follow an example of how any method was added. You can use `git blame` to get the exact commit and PR and see it in isolation.

**Comment by vmarquez** [comment]
@mmedenjak I have opened up a PR, let me know if that looks OK and then I can open up a PR for the actual delete method in the hazelcast core repo.

**Comment by mmedenjak** [comment]
Looks good. I have added a minor comment. There will be one minor complication on the member side because of rolling upgrades but not that big. Basically, if the cluster version is less than 3.10, you will have to reject the operation since not all members might be running hazelcast 3.10. But we'll address that once you have a PR for the hazelcast module.

**Comment by burakcelebi** [comment]
Already merged.
