### ISSUE TITLE
Hazelcast distributed Queue removal is not working in consuming systems.

### ISSUE THREAD

**Issue by chandrasekarlal** [hazelcast/hazelcast#3165]
Hi Team,

we are using hazelcast distributed queue to share the information between servers. we have put messages from producing(source) system and they have been taken it from the consuming system through item listeners. After the business operations, we are trying to remove the message from queue at consuming systems but the messages are not being removed from the queue, But if we remove it from producing system then it is getting removed. 

we don't know why it couldn't remove the messages from queue when we called it from consuming end,

we have implemented ItemListener interface and overrided itemAdded & itemRemoved methods. please find the code snippet,

Producer system:
puting message in queue,

TestHazelcast.getInstance().getHazelcastInstance().getQueue("sampleQueue").put(testMessage);

Consumer system:
fetching queue from instance,

IQueue<Object> cmv2Queue = TestHazelcast.getInstance().getHazelcastInstance().getQueue("sampleQueue");
boolean removed = cmv2Queue.remove(esbMessage);

but it always returns "false" and not removing the message from queue.

can you please let me know what is wrong?  why it could not remove messages when we are calling remove method from consuming systems? 

Thanks,
Chandra

**Comment by tpsaitwal** [comment]
Hello @gurbuzali ,
What is the solution for this problem now? If I want to remove the queue member.

**Comment by fpiagent** [comment]
Hi, they should at least override the javadoc from `BlockingQueue.remove` where it explicitly says:
```
Removes a single instance of the specified element from this queue,
     * if it is present.  More formally, removes an element {@code e} such
     * that {@code o.equals(e)}, if this queue contains one or more such
     * elements.
```
And it's the one we get when using QueueProxyImpl.

**Comment by jhaeyaert** [comment]
Hello, 
I know this issue is closed since many years now but I'm facing the same issue when trying to remove a simple object from an `IQueue`.
Dinging deeper in Hazelcast I found that, to check object's equality, Hz compares the serialized object against each serialized object in the queue. 

I was expecting it uses the equals methods of the object as stated by the javadoc but no. The problem is that 2 objects perfectly equal in values can have different serialization results. This is the case when your object contains `Map` or `HashSet` (which is internally managed with a `Map`).

I created a simple reproductible example based on the example given (7 years ago 🙂). I just added an `HashSet`:

```java
public static void main(String[] args)  throws Exception  {
        final HazelcastInstance producer = Hazelcast.newHazelcastInstance();
        final HazelcastInstance consumer = Hazelcast.newHazelcastInstance();

        final IQueue<Object> pQueue = producer.getQueue("queue");
        final IQueue<Object> cQueue = consumer.getQueue("queue");
        cQueue.addItemListener(new ItemListener<Object>() {
            @Override
            public void itemAdded(final ItemEvent<Object> itemEvent) {
                final Object item = itemEvent.getItem();
                System.err.println("itemEvent: " + item);
                System.err.println("removed: " + cQueue.remove(item));
            }

            @Override
            public void itemRemoved(final ItemEvent<Object> item) {
            }
        }, true);

        final HashSet<String> set = new HashSet<>();
        set.add("Hello");
        pQueue.put(new EsbMessage("foo", 2, set));
        pQueue.put(new EsbMessage("foo", 2, Collections.singleton("Hello")));

        Thread.sleep(2000);
    }

    static class EsbMessage implements Serializable {
        public String name;
        public int id;
        public Set<String> set;

        EsbMessage() {
        }

        EsbMessage(final String name, final int id, Set<String> set) {
            this.name = name;
            this.id = id;
            this.set = set;
        }
    }
```

Executing the above code will result with the following logs:

```
itemEvent: EsbMessage@1727ccc5
removed: true

itemEvent: EsbMessage@45e4c76e
removed: false
```

As you can see, the first event is well removed from the queue but the second one which is quite the same is not. The only difference is the way the `HashSet` is instantiated: `new HashSet` vs `Collections.singleton`.

The serialization result differs between these 2 objects because the internal `Map.capacity` is not initialized in the same way (16 with `new HashSet`, dynamically calculated during deserialization for `Collections.singleton`).

We detected this problem because we configured the queue with a max size and it ended up being full but I suppose it could cause OOM with unbounded queue.

Do you think there is a bug here (I'm a bit surprised there is not a lot of issues about this behavior) ?
Do you see any way to achieve the queue removal when dealing with objects embedding `Map` ?

Thx
