### ISSUE TITLE
How could be Hazelcast topic guarantee the message received ?

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#3371]
Hi,Hz Team. as from the manual. we've got that there's no guarantee that the event to be fetched when publish or subscribe operation invoked between nodes.and would you mind making sure that such only happened  just under heavy burden system that is overloading the capacity of the event queue size.

as during our experiences that it sometimes induced the node for subscribing could not get the event from the publishing node even not under heavy burden environment. we've traced the o.s info like between linux and solaris or between linux and windows or else between different jdk(like jdk1.8 and jdk1.7) and I could not find the direct reason that the subscribing node could not get the event. 

so is any strange reason the induce the event could not get the event

**Comment by pooja-achievement** [comment]
Hi, 

I need to use Hazelcast Topic for one of my requirement. There are two types of Topics: Basic and Reliable. I am not able to decide whether I should use basic topic or reliable topic as I am not able to understand that what kind of event loss would happen for basic Topic and to rectify that we need to use Reliable topic. Hazelcast manual says below for Reliable Topic,

```
Events are not lost since the Ringbuffer is configured with one synchronous backup by default.
Each Reliable ITopic gets its own Ringbuffer; if a topic has a very fast producer, it will not lead to problems at topics that run at a slower pace.
Since the event system behind a regular ITopic is shared with other data structures, e.g., collection listeners, you can run into isolation problems. This does not happen with the Reliable ITopic.
```

I am not able to understand what synchronous backup would do??

My scenario:

A node stores some config in internal memory. The node receives a request to reload the config from database, so the node would publish the info and all the nodes in the cluster including the one who has published the message would receive the message and all the nodes would reload the config from database.

**I need to decide whether I should use basic Topic or Reliable Topic??**

**Comment by mmedenjak** [comment]
Hi @pooja-achievement !

The biggest difference between basic and reliable topic is the handling of slow listeners. If you have a slow listener, the event queues for basic topic will fill up and events will be dropped. This may cause even fast listeners to lose events if there is a single slow listener.
On the other hand, fast listeners are not affected by slow listeners in the case of reliable topic. If a listener is slow, only it will observe lost events (because the events are being produced faster than they are being consumed). Fast listeners will always get to consume all of the produced events.

The other difference is that reliable topic has a backup of produced events and if there is a instance failure, most (or all) of the events will be present on the backup. In the case of basic topic, there are no backups and an instance loss will lead to losing all events contained on that instance.

I would suggest using reliable topic, unless you have a high volume of events and are ok with losing some events.

**Comment by pooja-achievement** [comment]
Thanks Matko,

I have few more concerns.

In my application, already one Hazelcast instance and Hazelcast client is
running and currently the instance and client are very much, module
specific in terms of configurations. I need to implement something new and
I don't want to disturb existing instance and client. So I am planning to
instantiate new hazelcast instance or client. I am not able to decide that
whether I should go for Hazelcast instance or Hazelcast client ?? I would
do refactoring later and probably whole application would use single
instance or client.

newHazelcastInstance or newHazelcastClient ??

Thanks,
Pooja

**Comment by mmedenjak** [comment]
A hazelcast instance can contain data and cooperate in data processing and as such is more heavy-weight. A client only directs user requests to a hazelcast instance.

**Comment by pooja-achievement** [comment]
---------- Forwarded message ----------
From: *Pooja Pandey* <pooja.achievement@gmail.com>
Date: Friday, July 26, 2019
Subject: JVM is not exiting due to Hazelcast Client's non-daemon threads
To: Hazelcast <hazelcast@googlegroups.com>


Hi,

I have a java application and during the course of action it gets an
Hazelcast client. This hazelcast client causes the creation of a large
number of non-daemon threads (~20). We have registered shutdown hook to
shutdown the client, however at the end of main(), JVM is not exiting due
to these non-daemon threads and since JVM is not exiting the shutdown hook
for client doesn't get called. We don't want to call System.exit()/
HazelcastClient.shutdownAll() from our main(). I wanted to check if there
is any way/setting for Hazelcast client so that it will create daemon
threads instead of non-daemon threads.

Thanks,
Pooja

-- 
You received this message because you are subscribed to the Google Groups
"Hazelcast" group.
To unsubscribe from this group and stop receiving emails from it, send an
email to hazelcast+unsubscribe@googlegroups.com.
To view this discussion on the web visit https://groups.google.com/d/
msgid/hazelcast/7aeee9da-1463-4615-885d-47a70785369c%40googlegroups.com
<https://groups.google.com/d/msgid/hazelcast/7aeee9da-1463-4615-885d-47a70785369c%40googlegroups.com?utm_medium=email&utm_source=footer>
.
