### ISSUE TITLE
Add CDI support for Hazelcast

### ISSUE THREAD

**Issue by astefanutti** [hazelcast/hazelcast#440]
Given that CDI is the Java standard for dependency injection, Hazelcast should offer a CDI extension that is capable of injecting Hazelcast instances in the CDI container based on some sort of CdiConfigBuilder.

Injection of CDI beans in the Hazelcast configuration should be supported as a replacement for class name setters.

**Comment by ipl31** [comment]
Does the above extension work for being able to use @Inject in a class that will get serialized and sent to a Hazelcast executor so the executor if running in Weld/CDI will be able to have it's dependencies provided?

**Comment by rmannibucau** [comment]
Making the Bean implementing PassivationCapable would do

**Comment by noctarius** [comment]
Here's an implementation based on the code provided by tomitribe: https://github.com/noctarius/jcache-cdi

**Comment by rmannibucau** [comment]
@noctarius 2 small comments: 1. for jcache there is already a jcache-cdi integration which avoids to be too programmatic (spoke of it in https://blog-rmannibucau.rhcloud.com/#/post/hazelcast-cdi) 2. the mentionned extension in a previous comment was more powerful since it was mapping hazelcast concepts and not just maps (jcache) and was not bound to a default configuration so it probably requires a bit more work to match hazelcast strength

**Comment by noctarius** [comment]
You like to make it a module and contribute it? :)

**Comment by rmannibucau** [comment]
@noctarius https://github.com/rmannibucau/hazelcast-cdi
