### ISSUE TITLE
[transaction] Transaction Propagation

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#451]
Support for transaction propagation level like:
requires, requires new, etc etc.

Currently there is no support for transaction propagation which makes nesting of transactions problematic.

**Comment by burakcelebi** [comment]
Closed as internal request

**Comment by sbespalov** [comment]
@burakcelebi why is it closed?
In general the question is why Hazelcast don't support "nested" transactions?

The thing is that we really need `PROPAGATION_REQUIRES_NEW` in our Spring managed transactions, but HazelcastTransaction manager doesn't allow to use this propagation because "Hazelcast doesn't support nested transactions".

If I understand correctly "nesteed" means multiply transactions within same thread, why it's not possible?

**Comment by manojgithup** [comment]
Still i am getting this issue in hazelcast 3.9 

java.lang.IllegalStateException: Transaction cannot span multiple threads!
        at com.hazelcast.client.proxy.txn.TransactionProxy.checkThread(TransactionProxy.java:134)
        at com.hazelcast.client.proxy.txn.TransactionProxy.begin(TransactionProxy.java:76)
        at com.hazelcast.client.proxy.txn.TransactionContextProxy.beginTransaction(TransactionContextProxy.java:78)
        at com.reno.imdg.servicesimpl.HZMapServiceImpl.writeOrUpdateProcessMapSpaceEntity(HZMapServiceImpl.java:278)

**Comment by mdogan** [comment]
@sbespalov: Afaik this was closed since it was created by an Hazelcast employee and @burakcelebi created an internal issue to track that. 

Hazelcast doesn't support nested transactions or configurable propagation levels yet.

**Comment by steve-todorov** [comment]
@mdogan are there any plans to have this implemented any time soon?

**Comment by mmedenjak** [comment]
Hi @steve-todorov !
We have no plans to implement it as of yet. If there is much community interest, we shall consider it.
