### ISSUE TITLE
Enhancement: Pluggable discovery mechanism

### ISSUE THREAD

**Issue by bluestix** [hazelcast/hazelcast#4845]
Hi

I added pluggable node discovery in my fork. I needed it so I could use Consul to discover nodes.

I made it configurable in xml and Spring.

I hope you will consider adding it so I don't have to maintain my branch going forward.

You can view the changes in my fork on branch: v.3.4.1_nodeDiscovery

If you are interested I will submit a pull request.

Thanks

 Example:

```
        <join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            <tcp-ip enabled="false">
                <interface>127.0.0.1</interface>
            </tcp-ip>
            <aws enabled="false">
                <access-key>my-access-key</access-key>
                <secret-key>my-secret-key</secret-key>
                <region>us-east-1</region>
            </aws>
			<discovery discoveryClass="com.somecompany.SomeCustomNodeDiscovery" enabled="true">
				<properties>
					<property name="someProperty">someValue</property>
				</properties>
			</discovery>
        </join>
```

**Comment by noctarius** [comment]
Hey @bluestix, 

Thanks for your effort and I kinda like the approach but there is already a Hazelcast Enhancement Proposal for a general discovery spi and I would prefer you to join this HEP rather than working in parallel. You don't need to send a PR yet since it won't be merged because of the HEP and because those work slightly different. 

Please find general information on how the Hazelcast Incubator works here: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals

The HEP for the discovery spi can be found here: https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI

**Comment by mdogan** [comment]
Fixed via https://github.com/hazelcast/hazelcast/pull/5949
