### ISSUE TITLE
Hazelcast Eviction not working with Spring DSL when max-size-policy is USED_HEAP_SIZE. It works fine with max-size-policy as PER_NODE.

### ISSUE THREAD

**Issue by balajikandavel** [hazelcast/hazelcast#4885]
I tried with version 3.4.1 and other lower versions(3.2.x , 3.3.x).
http://stackoverflow.com/questions/29172718 

Cluster size -1
Number of the clients - 1
Version of Java. It is also helpful to mention the JVM parameters - 1.7
Operating system. If it is Linux, kernel version is helpful - Windows 7

Since there are no errors, logs might not be useful. Please let me know if you need more details.

**Comment by ahmetmircik** [comment]
Hi @balajikandavel, 

Is it possible for you to share a simple failing test ?

**Comment by tliron** [comment]
We are experiencing the same issue. We are using the Hazelcast Management Console to test this. To keep things simple, it is a single instance (not a cluster). We confirm in the Management Console that our map has this configuration:

    <max-size policy="USED_HEAP_SIZE">1</max-size>

However, when looking at the Map Memory Data Table, the entry map memory for this map far exceeds 1 mb.

**Comment by ahmetmircik** [comment]
@tliron Did you try it with version 3.5.1?

**Comment by tliron** [comment]
Yes, 3.5.1.

OK, after more testing I think I understand what's going on. The issue is the TTL: if I set a long TTL on the map (for example, 3 hours), then the entries will *not* be immediately evicted even if the max size is reached. Once I set the TTL to something very small (1 second), then USED_HEAP_SIZE worked as I expected.

This makes sense in a way: the contract you have with a IMap is that data you put in there stays there for as long as you say it should.

But, that means that USED_HEAP_SIZE is not (and cannot be) a "hard" limit: it only signifies when eviction *could* happen, while it can't guarantee maximum heap use.

Am I correct in understanding the situation?

If so, we have a problem: we really want a "hard" limit here so that our cache won't grow too much in size. Is there some kind of mechanism in Hazelcast to allow for this? Is there a way to make sure that we don't run out of heap memory?

**Comment by ahmetmircik** [comment]
`USED_HEAP_SIZE `  is a "hard" limit. You should not see much memory than that given limit. You can also set `mapConfig.setMinEvictionCheckMillis(0L)` to zero in order to force eviction in every put operation. It is default value is `100 ms`.

Btw, `TTL` and  `USED_HEAP_SIZE ` are independent things. `TTL` is for expiration but  `USED_HEAP_SIZE ` is for eviction. If you want to put a max heap size limit to IMap, you should use eviction.

If `mapConfig.setMinEvictionCheckMillis(0L)` does not work for you, please provide a simple test code  which reproduces the issue.

**Comment by tliron** [comment]
Thank you so much for your assistance. Yes, setting `mapConfig.setMinEvictionCheckMillis(0L)` completely solved this issue!

The question now is why does a rate of just 100ms completely break this mechanism? Is is supposed to trigger some background thread to do the evictions? Could it be that the background thread is not working for us? How can we debug this?

**Comment by ahmetmircik** [comment]
No background thread exists for eviction. Eviction is done by the thread which puts your entry to the IMap. 100ms is the elapsed time between two subsequent put operations to trigger eviction. Maybe you should add some latency between subsequent put operations when testing...

**Comment by tliron** [comment]
Thank you for the explanation, but that means that there is indeed a bug. Our heap cost keeps going up when the value is at the default 100 ms, but everything works fine when set to 0.

**Comment by ahmetmircik** [comment]
Eviction only occurs at the time of put operation, if you don't put anything there will be no eviction. So, for instance, if you put 1000 items in 100ms period, to trigger eviction you have to put next item, if there is no next item, there will be no eviction.

**Comment by tliron** [comment]
Our application has quite a high throughput, so I guess this means that if all the data is stored in the map in a short time, then nothing will ever be evicted.

Is there is a way to trigger eviction programmatically? We could have a background thread do this once in a while.

**Comment by ahmetmircik** [comment]
Other than setting `mapConfig.setMinEvictionCheckMillis(0L)`, i have no better suggestion atm actually, maybe putting a dummy object periodically also works.

**Comment by tliron** [comment]
Hm, I'm not sure what to do about this issue at the moment. I understand that this behavior is by design, but I think it's confusing and will definitely seem broken to many users. Perhaps you can "fix" this bug by carefully documenting this behavior, while suggesting the workaround.

By the way, what would be the cost of calling `mapConfig.setMinEvictionCheckMillis(0L)` in terms of performance? If the eviction check is heavy, this could be a very bad idea.

**Comment by ahmetmircik** [comment]
Expecting lower effect on performance but it is better to you to test it for your own use case.

For you, is the documentation for `min-eviction-check-millis` [here](http://docs.hazelcast.org/docs/latest/manual/html-single) and following note there not enough?

**Comment by tliron** [comment]
Well, the more I think of this, the more I think something is still broken. It's not just that the eviction happens later, it's that it _never happens at all_ if you keep adding more and more values to the map. We set the `USED_HEAP_SIZE` to 1mb, but because we keep putting more entries in at a high rate, we keep growing to many megabytes in size.

It seems that you are calculating the min-eviction-check as a "window" between the previous put and the current put, but this means that a indeed high-rate of puts will result in eviction never happening.

I think what you intended this feature to do was to allow throttling of eviction checks for better resource use in high-throughput situation. In that case, I have a better solution.

* Call the property `minTimeBetweenEvictions`
* Add a var called `lastEviction` and set it every time eviction happens.
* When you do a put, evict only if this is true: `now - lastEviction > minTimeBetweenEvictions`

To your question, here's the documentation:

> NOTE: When map entries are inserted frequently, the property min-eviction-check-millis should be set to a number lower than the insertion period in order not to let any entry escape from the eviction.

That is a little too short, and does not seem detailed or clear enough for me. What's missing:

* Make it clear that eviction happens _only_ during put operations.
* "not let any entry escape" is unclear to me; actually, eviction might never happen at all if you keep putting entries

Still, please consider my alternative solution to your current design.

Anyway, I think it would anyway be useful to add a new API to trigger programmatic eviction, and provide documentation for use cases and a simple example of setting up eviction with a background thread.

**Comment by ahmetmircik** [comment]
Please check out these methods [cleanUp](https://github.com/hazelcast/hazelcast/blob/24b377020aa3aa78ff0c61e5428c73eb75506e6d/hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java#L217) and [inEvictableTimeWindow](https://github.com/hazelcast/hazelcast/blob/24b377020aa3aa78ff0c61e5428c73eb75506e6d/hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractEvictableRecordStore.java#L265), it seems similar with your design suggestion. 

Btw, will try to add some more clarification in docs.

**Comment by tliron** [comment]
Thanks! That code looks like correct to me, so I guess the intent is correct. But I don't understand how the record store and put operation classes and the map all get linked together. The fact is that the behavior is not as designed, so we do have a bug here.

**Comment by tliron** [comment]
Here is some code that can reproduce the issue for you. It creates a map with 1 mb limit, and keeps filling it up. It sends stats to a locally running Management Center so you can see memory use. The program argument is the delay in millis between insertions.

On my machine, when I set the delay to 20 or below, the map keeps growing in size far beyond 1 mb.

```
import com.hazelcast.config.Config;
import com.hazelcast.config.EvictionPolicy;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MaxSizeConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class Hazelcast4885 {
    public static void main(String argv[]) throws Exception {
        long latency = argv.length > 0 ? Long.parseLong(argv[0]) : 0L;

        MapConfig mapConfig = new MapConfig("mymap");
        mapConfig.setMaxSizeConfig(new MaxSizeConfig(1, MaxSizeConfig.MaxSizePolicy.USED_HEAP_SIZE));
        mapConfig.setStatisticsEnabled(true);
        mapConfig.setEvictionPolicy(EvictionPolicy.LRU);
        mapConfig.setMinEvictionCheckMillis(100L);
        mapConfig.setBackupCount(0);

        Config config = new Config("4885");
        config.addMapConfig(mapConfig);
        config.getManagementCenterConfig().setEnabled(true);
        config.getManagementCenterConfig().setUrl("http://localhost:8080/mancenter");
        HazelcastInstance instance = Hazelcast.getOrCreateHazelcastInstance(config);

        IMap<Long, byte[]> mymap = instance.getMap("mymap");

        long key = 0L;
        while (true) {
            mymap.put(key++, new byte[10000]);
            Thread.sleep(latency);
        }
    }
}
```

**Comment by tliron** [comment]
Have you tried my code? You should be able to see the issue clearly.

**Comment by kuseman** [comment]
We have a similar issue that I think is related to MinEvictionCheckMillis.

We have a setup where all our maps have a near cache enabled and a time to live both on map and och near cache level.

Sometimes the map entries doesn't get evicted based on the TTL which seems very strange to me and I guess has to do with the MinEvictionCheckMillis that we have set to 100 (default).

How does the eviction work under the hood? Is there a clean up thread or does eviction occur only when put?

**Comment by stoerr** [comment]
It is possible that this problem depends on the in-memory-format . I tried: if I set in-memory-format of an IMap to OBJECT, USED_HEAP_SIZE does not work, but if I set it to BINARY, USED_HEAP_SIZE does work. Also, if one uses OBJECT, the JMX value "localHeapCost" is always 0. 

This actually makes sense - it is easy to determine the size of an IMap when it stores as BINARY, but it isn't if it stores as OBJECT, since that would require determining the size of an Java object tree. So I bet Hazelcast doesn't even try to determine the object size.

If it is as I suspect - please document this clearly that the combination of USED_HEAP_SIZE (and probably USED_HEAP_PERCENTAGE) does not work together with in-memory-format=OBJECT. And please log an error message or at least warning, if someone tries this configuration. I've even seen someone trying to set USED_HEAP_SIZE in bytes, actually getting 500TB maximum size, which probably also would warrant a warning in the log.

**Comment by gurbuzali** [comment]
@stoerr thank you for pointing out, I've created a new documentation issue for that case https://github.com/hazelcast/hazelcast/issues/6875

@tliron sorry for late response, I've tried your code and yes it really goes beyond 1 Mb limit.
But as @ahmetmircik pointed out this is the expected behavior if you configure  `minEvictionCheckMillis=100`. 
This configuration means that there will be some time (100ms) between two evictions. and if you put more entry than evicted count in that time period, it is obvious that the maps size will increase.

If you want a strict max-size for your map you should definitely use a lower value (0 maybe) for  `minEvictionCheckMillis`
We already mention this in our documentation 
http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#map-eviction
```
NOTE: When map entries are inserted frequently, the property min-eviction-check-millis should be set to a number lower than the insertion period in order not to let any entry escape from the eviction.
```

**Comment by rehevkor5** [comment]
The note in the documentation is OK, but it doesn't explain what is meant by "insertion period". I had to search for & find this thread in order to understand what it means.
