### ISSUE TITLE
[TEST-FAILURE] ClientMapTest Failures

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4916]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/494/console

**Comment by metanet** [comment]
Related failures (ResponseAlreadySentException) are here: 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/494/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.map.ClientMapTest.txt
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/494/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.map.ClientMapTest-output.txt


Closed since not failed recently.
