### ISSUE TITLE
MapReduceManagedContextTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4921]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/504/consoleFull

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/506/console
in map reduce tests, there are many operation timeouts.

**Comment by bilalyasar** [comment]
seems map reduce has some operation timeout problems
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/487/console

**Comment by metanet** [comment]
Related failures (ResponseAlreadySentException) are here: 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/506/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.mapreduce.aggregation.MinAggregationTest.txt
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/506/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.mapreduce.aggregation.MinAggregationTest-output.txt

Closed since not failed recently.

**Comment by bilalyasar** [comment]
new failure: 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/544/console

**Comment by metanet** [comment]
Closed since not failed for a long time
