### ISSUE TITLE
[TEST-FAILURE] ClientMapLoadAllTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4952]
`test timed out after 60000 milliseconds`

com.hazelcast.client.map.ClientMapLoadAllTest.testGetMap_issue_3031
com.hazelcast.client.map.ClientMapLoadAllTest.testLoadAll_allKeys
com.hazelcast.client.map.ClientMapLoadAllTest.testLoadAll_givenKeys
com.hazelcast.client.map.ClientMapLoadAllTest.com.hazelcast.client.map.ClientMapLoadAllTest

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/498/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/196/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/500/

**Comment by metanet** [comment]
Related failures (ResponseAlreadySentException) are here: 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/500/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.map.ClientMapLoadAllTest.txt
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/500/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.map.ClientMapLoadAllTest-output.txt

Closed since not failed recently.
