### ISSUE TITLE
HazelcastCacheManager should offer a way to access the underlying cache manager

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#4978]
The cache manager may have been created as a part of the lifecyle of a Spring application context so it is desirable to actually shutdown the cache manager that was created as part of it.

Unfortunately, `HazelcastCacheManager` offers no way to access the underlying `HazelcastInstance`. Could you please add a setter (look at other cache manager implementations for reference).

Thanks!

**Comment by mesutcelik** [comment]
@serkan-ozal , 
Can you please have a look? The CacheManager mentioned is JCache Cache Manager as far as i see.

**Comment by snicoll** [comment]
I have actually implemented something on our side to shutdown the cache manager automatically if necessary. The [change is pending review](https://github.com/snicoll/spring-framework/commit/19f684c62225055c5c842d6989b8e37577ee71d4) though.

**Comment by serkan-ozal** [comment]
Hi @snicoll 

There are some ways to set specific `HazelcastInstance` to requested `HazelcastCacheManager`

* You can create your `HazelcastInstance` and can specify it to be used in cache manager with its name as mentinoned here https://github.com/hazelcast/hazelcast/blob/master/hazelcast-documentation/src/JCache-ICache.md#named-instance-scope

* You can create a `CachingProvider` binded to specified `HazelcastInstance` https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cache/impl/HazelcastServerCachingProvider.java#L52 So, requested `HazelcastCacheManager` over this `CachingProvider` will use your custom `HazelcastInstance`.

As a result, I think no reason for adding a new method to our `HazelcastCacheManager` implementations as `void setHazelcastInstance(HazelcastInstance instance)` because `HazelcastInstance` must be specified while creating `HazelcastCacheManager` over its constructor.

Does these solutions handle your case?

Regards.

**Comment by snicoll** [comment]
Sorry, I just realized that I made a typo. I asked to "access" the underlying `HazelcastInstance` so I should have wrote _getter_ and not _setter_. Sorry about that!

To be clear, the use case is that once you have a Spring's `CacheManager` instance, you have no way to access the underlying `HazelcastInstance` it's wrapping so something like the following would work for me

```java
public HazelcastInstance getHazelcastInstance() { ... }
```

**Comment by serkan-ozal** [comment]
@snicoll ok, I will add a getter `public HazelcastInstance getHazelcastInstance()` method and you will able to access underlying instance over `HazelcastCacheManager` interface (means that will be supported by both of `HazelcastClientCacheManager` and `HazelcastServerCacheManager`)

**Comment by noctarius** [comment]
If you know the name of the instance or you just have one you can use Hazelcast class to retrieve it by name or just retrieve the single instance itself.

**Comment by snicoll** [comment]
the use case is that you have Spring's CacheManager and you have no idea what's being configured underneath but for some reason you need to access the cache-library specific API.

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/43092ce22e696c9612a1dd2667f87da59c5418a7
