### ISSUE TITLE
UnsupportedOperationException when invalidating Hibernate L2 Cache

### ISSUE THREAD

**Issue by Michael-S-Smith** [hazelcast/hazelcast#5391]
When any entities are defined as read only in the Hibernate L2 cache, an invalidation of the cache (such as caused by executing a native SQLQuery) leads to the following error:
java.lang.UnsupportedOperationException: Attempting to lock a read-only cache region

This works fine using EHCache as the L2 provider. Is this a bug? It was also reported here some time ago: https://groups.google.com/forum/#!topic/hazelcast/R8E2f9k1qBg

Thanks

**Comment by kobalski** [comment]
Implementation of read only access strategies are same in both EHCache and Hazelcast they both throw exception because when an entity is in read only mode lock method should not be called, this seems to be a bug.  Thanks for reporting issue @Michael-S-Smith .

EHCache Impl : 
http://grepcode.com/file/repository.jboss.org/nexus/content/repositories/releases/org.hibernate/hibernate-ehcache/4.1.0.Final/org/hibernate/cache/ehcache/internal/strategy/ReadOnlyEhcacheEntityRegionAccessStrategy.java?av=f#87

Hazelcast Impl : https://github.com/hazelcast/hazelcast/blob/master/hazelcast-hibernate/hazelcast-hibernate3/src/main/java/com/hazelcast/hibernate/access/ReadOnlyAccessDelegate.java#L52

**Comment by Michael-S-Smith** [comment]
Thanks for the quick reply. Perhaps the difference is further up the chain - a call to 
session.getSessionFactory().getCache().evictAllRegions() does not lead to this exception with read-only entities with EHCache, but in Hazelcast it does.

**Comment by kobalski** [comment]
Closing this one, ReadOnlyAccessDelegate returns null, instead of throwing `java.lang.UnsupportedOperationException`.  https://github.com/hazelcast/hazelcast/blob/master/hazelcast-hibernate/hazelcast-hibernate3/src/main/java/com/hazelcast/hibernate/access/ReadOnlyAccessDelegate.java#L63
