### ISSUE TITLE
Hazelcast hangs for 10 mins on a force shutdown on  a node

### ISSUE THREAD

**Issue by hariprasanth1234** [hazelcast/hazelcast#5423]
Hi all,

I have 3 node cluster 192.168.1.1, 192.168.1.2 and 1.3 where hazelcast runs in all the nodes forming a TCP/IP cluster in hazelcast.

When I soft shutdown my hazelcast on 1.1, Automcatically removed 1.1 and 1.2, 1.3 have joined together as cluster.

When I force shutdown my complete node on 1.1, It takes 10 mins for the hazelcast to remove 1.1 and join 1.2 and 1.3. 

When I try to access any one member at that time, It shows like it has the members as 
      1.1
      1.2 
      1.3  
After 10 mins, When i try to access any node, It shows as 
      1.2 and 1.3 have joined as members.

1. What is the problem in force shutdown on a node?
2. Is there a configuration available to make this work properly in hazelcast ?

Thanks and Regards,
Harry

**Comment by gurbuzali** [comment]
Hi
Can you elaborate on `soft` and `force` shutdown ?
Do you mean with soft : `instance.getLifecycleService().shutdown();` and force: `instance.getLifecycleService().terminate();` ?

**Comment by hariprasanth1234** [comment]
No If I shutdown the entire server 1.1 (Where my hazelcast , tomcat are running), then Hazelcast running in 1.2 and 1.3 is not responding for 10 mins! This is a force down, Making the entire server to force down.

If I kill the 5701 port process running in 1.1 manually using kill command but the server 1.1 is up (Only hazelcast is down in 1.1), then immediately 1.2 and 1.3 removes the 1.1 and makes the cluster 1.2 and 1.3.

**Comment by gurbuzali** [comment]
When you shutdown entire server 1.1, its connections(TCP/IP connection) to other nodes does not closed immediately. And the other two nodes still think that the 1.1 node is still alive. it takes some time to detect(with heart-beat mechanism) and remove the unresponsive(which is dead actually) node.
This is expected behavior, you can play with the heartbeat properties to decrease the wait-time
http://docs.hazelcast.org/docs/3.4/manual/html-single/hazelcast-documentation.html#system-property

For the second case, kill command immediately closes the connections which will notify the other two nodes to remove the dead node from cluster. (btw killing a process is not a soft shutdown, if there is data which are not replicated yet, you may loose data. )

**Comment by hariprasanth1234** [comment]
Gurbuzali, I agree, But why the hazelcast hangs and not sending back the response.

**Comment by gurbuzali** [comment]
Here it is not the hazelcast which is not sending back the response. when you shutdown the entire server you actually terminate the hazelcast on that node but the other nodes are not aware of this because the TCP/IP connection is not terminated correctly.

**Comment by hariprasanth1234** [comment]
okay! Gurbuzali, Thank u so much! I preferred 
                clientConfig.setProperty("hazelcast.max.no.heartbeat.seconds","30");
		clientConfig.setProperty("hazelcast.client.heartbeat.timeout", "60000");

These two tuning parameter, Do you have any other parameters which can be used for tuning?
