### ISSUE TITLE
Improved Near Cache Invalidation 

### ISSUE THREAD

**Issue by fuadm** [hazelcast/hazelcast#5461]
The current near cache invalidation uses one event packet for each update. This implementation creates N * X number of events per second, where N is the number of client or server nodes and X is the number of updates per second. As N increases, the number of events increases linearly. This makes it costly to add a client to the cluster. 

These event packets fills the single connection from server to client, resulting in high latency for other normal operations like put or get. 

An alternative approach is to use something like Nagle's algorithm. Server side needs to be smart enough to batch the invalidation messages. It can use a Set to store all invalidated keys and send the set to the clients every 5 ms or when the size of set reaches say 1000. Both these parameters should be configurable. By using a set, we also guarantee that only one invalidation per key is sent to the client in a given window.

**Comment by Tembrel** [comment]
A refinement of this, assuming one can tolerate occasional spurious invalidation, would be to use a Bloom filter (Guava has a nice [implementation](http://docs.guava-libraries.googlecode.com/git-history/v18.0/javadoc/com/google/common/hash/BloomFilter.html)) instead of a Set. That would allow you to have compact invalidation messages even for very large numbers of invalid keys.

For this to work, invalidation would have to be lazy, i.e., near cache access of a key would involve first testing the key for invalidity in the union of most recently received invalidation messages. And since false positives are possible with Bloom filters, you could indeed get spurious invalidations.

Trade-offs are possible: By increasing the size of the invalidation message (i.e., of the Bloom filter), the frequency of spurious invalidation drops.

A small implementation challenge would be efficiently maintaining (on each node) a union of most recently received invalidation messages from each other node. This data structure would be linear in the number of nodes, but since the Bloom filters are relatively compact, it wouldn't be a big memory hit.

**Comment by serkan-ozal** [comment]
@fuadm Is this current near-cache improvements for near-cache is enough?

**Comment by fuadm** [comment]
Hi Serkan, 

Yes, all the latest improvements are great and they work.

**Comment by fuadm** [comment]
Hi @Tembrel, 

Sorry, I missed your comment. 
I understand the fact that will bloom filters it will be a smaller invalidation message. But receiving the message, shouldn't I call mightContain on BloomFilter for all entries that are stored in Near Cache? I think this will reduce the message size, but will add CPU cost on each node. Is my understanding correct?

**Comment by serkan-ozal** [comment]
ok, thanks @fuadm. Closing this one

**Comment by Tembrel** [comment]
@fuadm - Correct, a small CPU cost is incurred for each near-cache lookup to see if the key has (probably) been invalidated. But it's a tiny cost, since BloomFilter tests are just hashes to a bit vector. 

Some thought would have to put into maintaining the union of BloomFilters from other nodes, but the cost of that maintenance would only be incurred on receipt of new messages, not per near-cache lookup.

The use of BloomFilters would be something to consider __only if__ the size of the invalidation messages ever becomes an issue.

**Comment by fuadm** [comment]
Thanks for the explenation Tim. Serkan did a good job with the batching and currently it only sends the keys. So in theory it should be fine. If this starts to be an issue, an optional bloom filter alternative can be used as you described. We will keep this in mind. Thank you so much for sharing!

**Comment by arjamizo** [comment]
I came here immediately after learning about Hazelcast from a magazine. Is there a possibility of turning them on in HC? Asking google with simple _hazelcast & github & bloom filters_ shows nothing interesting.

**Comment by jerrinot** [comment]
@arjamizo: I am not quire sure what you are trying to ask. Would you like to use Hazelcast? http://hazelcast.org/ has some nice examples - you can try them in under 3 minutes. 

We do not use bloom filters internally if that's what you are asking.
