### ISSUE TITLE
Query or index on map entry

### ISSUE THREAD

**Issue by weejulius** [hazelcast/hazelcast#554]
Hi,

I have a map,the key is long and the value is a map (it is a pojo object typically), I cannot query on the map as there is not suitable accessor, the map does not have get method, if the predicates is possible to be more flexible to be applied in more scenarios.

Thanks

Julius

**Comment by vikas1369** [comment]
Hi @pveentjer If we use custom predicate with hazelcast client, Can I know where does the custom predicate evaluated i.e. client side or cluster side? If it is on cluster side (By that I mean computation to filter the map is done on cluster side and client gets the final result) how does the cluster know about the custom predicate? Wherever it runs Is it same for all versions of hazelcast?

**Comment by mmedenjak** [comment]
@vikas1369 I think it depends on the exact API you're using but in most cases the predicate will be run on the member-side, close to the data and to avoid moving data across the network which will not be returned to the user anyway.

To do that, the predicate bytecode will have to be deployed on the members and the predicate will have to be serializable and deserializable so that the client can inform the member which predicate it will run. There are some out-of-the-box predicates that you can use that don't require this, but if you're using a custom predicate, you'll have to do both (deploy the code and implement one of the supported serialization strategies). BTW you can deploy the code to the member at start-up time (by including it in the classpath/modulepath of the member) or during runtime (by using our user-code-deployment feature).

**Comment by vikas1369** [comment]
Thanks @mmedenjak . I wish to use predicates on the Map.

**Comment by vikas1369** [comment]
@mmedenjak  If I use Custom implementation of com.hazelcast.query.Predicate in that case will the query be executed on cluster?
