### ISSUE TITLE
[transaction] Tx Optimization: merge partition operations

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#5656]
Currently for every item in the transaction, a operation is executed. Instead of sending an operation and executing it one by one, create a merged operation where all operation for that partition merged. So effectively the same number of operations is executed, but only 1 merged operation per partition is executed. This saves a lot of IO overhead (can all be batched) and scheduling overhead.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?

**Comment by mmedenjak** [comment]
There is a `TxnCommitOperation` to bundle all of the commit operations. Do you mean that the prepare phase operations should be bundled as well?

**Comment by dbrimley** [comment]
Closing and putting on hold, will review at later point.

**Comment by mmedenjak** [comment]
@dbrimley in July I moved all of the TX related issues to backlog. The reason is that the state and future of transactions needed to be inspected thoroughly in a dedicated PRD and not on a issue-per-issue basis. I've collected some issues here: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/36208869/Core+Technical+Debt+-+Transactions
