### ISSUE TITLE
Equal distribution of entries

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#5698]
Currently the distribution of IMap entries is quite random and we rely on entries converging over few hundreds of thousands count and show near balanced distribution of data. But for a smaller count, there are higher chances of cluster imbalance. The problem gets more serious in case of few but large objects in cluster, which are only created once and used by IExecutorService or EntryProcessors or MapReduce etc. Use case example:

I have a really big object (100MB) and then I run EntryProcessor on that entry. And I will have only handful of such objects (10 such objects max over a cluster of 10 server nodes), but there will be multiple EntryProcessors for each of them. This way, if I could make sure that such small number of entries are distributed equally over the cluster, I’d be able to achieve equal load for EntryProcessing as opposed to having many such entries ending up in one node and choking that node due to many such EntryProcessors executing. There are some hacks to achieve this but an out-of-the-box functionality will greatly help.

**Comment by pveentjer** [comment]
Don't think we can do a lot here unless there is control on the used keys to access these objects.

**Comment by enesakar** [comment]
Agree with Peter on "Hazelcast isn't made for just a few entries with large values."
Most of use cases are on high number of entries. 
If you have processing scenarios that you want to distribute over members;
IExecutorService.executeOnMember() may fit better.

**Comment by pveentjer** [comment]
And we can generate good keys that are perfectly distributed over partitions. But there are a few problems:
1: perhaps there are less keys than partitions. 
2: you never know where the partition is going to end up at; because partitions can move around.

So I would really reconsider using such big objects.

**Comment by wildnez** [comment]
Even IExecutorService.executeOnMember() may not be most efficient way because one node may end up hosting several large keys, therefore bottlenecking that node while other nodes in the cluster are idol. Reducing partition count drastically would reduce the risk of bottlenecking one node but won't completely prevent it.

**Comment by noctarius** [comment]
Unfortunately I would also agree with Peter and Enes. This doesn't sound to me like a real IMDG use case. Other platforms will have the exact same problem or you go the HDFS way and split the serialized object into chunks and distribute those, however that removed the advantage of data locality on calculation.

For the case you want to have clean distribution you can just generate your own partition keys. What is not recommended (beside special cases for data affinity) in normal operation, I would recommend it in this special case.

**Comment by wildnez** [comment]
I disagree that its not a real IMDG use case, on a contrary, its a near perfect IMDG use case. I store data in cluster once and then I run my business logic in cluster without moving that data across. Only if I had equal distribution of data, I'd have achieved perfect parallel in-memory computing. Otherwise, it implies that having a few million entries is a pre-requisite to run Hazelcast?

**Comment by noctarius** [comment]
Well my gut (but personal) feeling on this is that not everything that is distributed is a use case for an IMDG :)

In that sense I agree with you, it sounds like a perfect fit but obviously this is a very corner case dataset and I would say, this needs to managed manually. It is the same as load balancing, it cannot be handled automatically when using consistent hashing since a normal key distribution will never be perfect. As Peter said, you can create perfectly distributed keys (for one cluster with a fixed size of members) but whenever the number of members changes this perfect distribution will change one way or another.

About a pre-requisite, well at the moment I would say it is not a Hazelcast use case. There are ways to "work around" that in the future but not really at the moment. It doesn't need to be millions of records though but a few thousand on a small number of nodes.

PS: Also not sure if 100MB per object sounds good, imagine the deserialization to do (or are they stored in Object Format?) :)

**Comment by wildnez** [comment]
Objects are only loaded once in a day (load latency is not an issue) in Object format.

**Comment by pveentjer** [comment]
I'm going to close this ticket because it is too generic and if there are a few numbers of keys; equal distribution is hard. @wildnez can you make a more concrete ticket?
