### ISSUE TITLE
 As to ICache, what kind of client side configuration can be done? 

### ISSUE THREAD

**Issue by yjanezou** [hazelcast/hazelcast#5817]
For our use case, we will run hazelcast on a remote cluster, could we configure cache-related settings (e.g, TTL) in client config (.xml) file?

**Comment by serkan-ozal** [comment]
Hi @yjanezou,
Cache configuration can be defined 
- At server, both of programmatically and declaratively (XML)
- At client, only programmatically

**Comment by yjanezou** [comment]
Thanks @serkan-ozal , our use case require as minimum as possible for server/cluster side configuration. We will use hazelcast to replace memcached cache, though not through the memcached client. From client side, we need to access the cache for read and write. Is the cache configuration (expiry policy) could only be configured when the cache is created? if the caching fleet/cluster is alive, the client service should not create the caches every time it is bounced. Could we assume if using getCache() method would create a new cache if it does not exist or return the existing cache?

**Comment by serkan-ozal** [comment]
Hi @yjanezou 

> Is the cache configuration (expiry policy) could only be configured when the cache is created? if the caching fleet/cluster is alive, the client service should not create the caches every time it is bounced. 

Yes, the cache configuration can only be configured when cache is created but you can create cache dynamically. It means no need to define caches at startup as static. However, if you want to change `ExpiryPolicy` dynamically, you can use our `com.hazelcast.cache.ICache` interface (which is sub-type of `javax.cache.Cache`) since Hazelcast cache's are an implementation of `ICache`. In `ICache` interface, there are many additional methods and you can use `V get(K key, ExpiryPolicy expiryPolicy)` and `void put(K key, V value, ExpiryPolicy expiryPolicy)` to specify `ExpiryPolicy` dynamically. But notice that, in this case, `ExpiryPolicy` instances will also be serialized/deserialized and this may cause very little performance overhead.

> Could we assume if using getCache() method would create a new cache if it does not exist or return > the existing cache?
`getCache()` doesn't create new cache, just returns the existing cache (also opens the closed but not destroyed cache)

**Comment by serkan-ozal** [comment]
BTW, @yjanezou Are these answers are enough for you?

**Comment by yjanezou** [comment]
Thank you @serkan-ozal for the detailed answer! one more question, if the client side app uses createCache() upon startup, would repeated creating an existing cache (with client app deployments) cause any issue for the hazelcast cluster?

**Comment by serkan-ozal** [comment]
Not cause any issue. 

If cache has been already created, next calls are just ignored. But if the existing cache is tried to be created from the same `CacheManager` instance multiple times (in your example from same client), an exception is thrown about cache is already exist.

**Comment by yjanezou** [comment]
Thanks @serkan-ozal. it helps.
