### ISSUE TITLE
MapLoader.load(K paramK) get called when we put a nonexistent key to IMap

### ISSUE THREAD

**Issue by NipponSunrise** [hazelcast/hazelcast#5819]
If we have an `IMap` with `MapLoader` assigned to it and we put a nonexistent key with some value, the `IMap.put(K key, V value)` gets call to `MapLoader.load(K paramK)` before it puts the value.

**Expected behavior:** `IMap.put(K key, V value)` does not call `MapLoader.load(K paramK)`
**Hazelcast version:** 3.5

```java
public static void main(String[] args) {

	Config hzConfig = new XmlConfigBuilder().build();

	hzConfig.getMapConfig("testCache")
			.setMapStoreConfig(new MapStoreConfig())
			.getMapStoreConfig().setImplementation(new MapLoader<Long, Object>() {
		
					@Override
					public String load(Long key) {
						System.out.println("Loading key: " + key);
						return "valueFromLoader";
					}
		
		
					@Override
					public Map<Long, Object> loadAll(Collection<Long> keys) {
						return null;
					}
		
		
					@Override
					public Iterable<Long> loadAllKeys() {
						return null;
					}
		
				});

	HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance(hzConfig);
	
	
	IMap<Long, String> testCache = hazelcast.getMap("testCache");
	
	// Prints:
	// > Loading key: 100
	testCache.put(100L, "directlyInjectedValue");

	// Prints:	
	// > directlyInjectedValue
	System.out.println(testCache.get(100L));

}
```

**Comment by gurbuzali** [comment]
This is the expected behavior. In order to return the old value, hazelcast loads the value from store before putting the new one. In your case it is a nonexistent key and it will return null but hazelcast cannot know it without calling `load`.

You can use `IMap.set` method to get rid off store loading, since it does not return anything no loading is required.
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/core/IMap.java#L578
