### ISSUE TITLE
Filter Based Web Session Replication, HZ session_id is not shown in tomcat manager due to a specific implementation

### ISSUE THREAD

**Issue by StepanMelnik** [hazelcast/hazelcast#5870]
hazelcast-all-3.5.2-SNAPSHOT version has a specific implementation to update a session id with HA prefix.

So, "<%= session.getId() %>" will return a session id like HZ0169EFFEC6FA4A76BB7061A241FA628D.

When we open tomcat manager/html/sessions, we cannot find a session with HZ prefix, because tomcat ManagerBase does not know anything about hazelcast session wrapper.

In this case not easy to understand what session is used by a client, what data is in the session.
Also not easy to monitor the created session, etc.

**Comment by mesutcelik** [comment]
Hi @StepanMelnik ,

The id prefixed by `HZ` is distributed session id in order to unify your session clusterwide. As your deployment includes more than one Tomcat instance, jsessionid per tomcat instance does not give any idea about your session. You should better check hazelcast cluster with the session id prefixed by `HZ` and monitor your session through Hazelcast Cluster.

please feel free to reopen the issue if things are still unclear.
