### ISSUE TITLE
On the fly configuration of DistributedObjects

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#592]
As a user I would like to be able to do on the fly creation of e.g. a Map (also all the other structures).

MapConfig mapConfig = new MapConfig()
mapConfig.set....
IMap map = hz.getMap(mapConfig)

Sometimes it isn't possible to provide the configuration up front. With this mechanism one can define new configurations on the fly.

In a multi node setup, the configuration also needs to be distributed to all the nodes so that each node has the same configuration.

**Comment by FlavioF** [comment]
+1

**Comment by zeitos** [comment]
+1

**Comment by pveentjer** [comment]
+1

**Comment by donovankim** [comment]
+1

**Comment by magiccrafter** [comment]
+1

**Comment by bitsofinfo** [comment]
+1

**Comment by bitsofinfo** [comment]
Please add functionality similar to the discovery strategy SPI for the WAN configuration...

**Comment by abourdon** [comment]
Hi,

Sorry to re-up this issue but I'm facing a related need and I would like to know if there is a way to do it.

I would like to dynamically set an **existing** configuration.

For instance, based on the @pveentjer's sample, I would like to write something like:

```java
public static void main(String[] argv) throws Exception {
        HazelcastInstance hz = Hazelcast.newHazelcastInstance();

        hz.getConfig().addMapConfig(new MapConfig().setName("fly:peter").setTimeToLiveSeconds(1));
        IMap map = hz.getMap("fly:peter");
        map.put("foo", "bar");

        System.out.println("get:" + map.get("foo"));
        Thread.sleep(10000);
        System.out.println("get:" + map.get("foo"));

        // Setting the existing configuration
        hz.getConfig().getMapConfig("fly:peter").setTimeToLiveSeconds(100);
        map.put("foo", "bar");

        System.out.println("get:" + map.get("foo"));
        Thread.sleep(10000);
        System.out.println("get:" + map.get("foo"));

        System.out.println("Done");
    }
```

And be able to see the following output:

```
get:bar
get:null
get:bar
get:bar
Done
```

But re-configuration seems to be not applied to the map because real output is the following:

```
get:bar
get:null
get:bar
get:null
Done
```

Is there a way to dynamically set an existing configuration and apply changes to related objects?

Regards,
Aurélien

**Comment by jerrinot** [comment]
@abourdon: dynamic reconfiguration is not supported. Configuration should not be modified after it has been used to create Hazelcast instance. See https://github.com/jerrinot/hazelcast/blob/994f37532f2087fb3a37674b4754d564eb21d4ad/hazelcast/src/main/java/com/hazelcast/config/Config.java#L46-L46

The usual workaround is to use pattern matching in your configuration.

**Comment by abourdon** [comment]
Hi @jerrinot,

Thanks for your quickly reply!

Ok so what would be the best practice to set configuration of a shared object at runtime? Because pattern matching is great but I can't know statically what will be values that will be set in configuration (because defined at runtime).

Maybe I have to destroy shared object and create a new one by triggering every nodes that handle it?

Thanks,
Aurélien

**Comment by jerrinot** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/10757

**Comment by jerrinot** [comment]
@abourdon: Hazelcast 3.9 allows to add new data structure configs at runtime. Early Access version should be released very soon

**Comment by abourdon** [comment]
Nice job! Thanks a lot!
