### ISSUE TITLE
Hazelcast Client -- overrides <connection-attempt-limit> with 1!

### ISSUE THREAD

**Issue by danfink** [hazelcast/hazelcast#6470]
HZ does not honor the <network><connection-attempt-timeout> setting.  Instead, it overrides it with "1".

With HZ 3.5.2, we have a Hazelcast client initialized with the usual com.hazelcast.web.WebFilter.  The <network> section of the hazelcast-client.properties file looks like:

    <network>
        <cluster-members>
            <address>127.0.0.1</address>
        </cluster-members>
        <smart-routing>true</smart-routing>
        <redo-operation>true</redo-operation>
    
          <connection-attempt-period>20000</connection-attempt-period>
          <connection-timeout>30000</connection-timeout>
          <connection-attempt-limit>60</connection-attempt-limit>
    </network>

When it runs, what I found is that internally HZ is setting connection-attempt-limit to 1.  I debugged and found that it happens in HazelcastClientLoader.createClientInstance():

      clientConfig.getNetworkConfig().setConnectionAttemptLimit(1);

Why is it doing this?  It is overriding a value that is set in the config file with "1" -- Why?

I have been trying to configure it for an effective retry policy and I noticed messages like this;

[2015-10-14 06:54:54,131] - WARN  - impl.ClusterListenerSupport  - Unable to get alive cluster connection, try in 18590 ms later, attempt 1 of 1.

again and again if it couldn't connect.  I could have expected the messages to be "...atempt 1 of 60", "...attempt 2 of 60", etc

I noticed that the set to 1 was only added in the last commit: "Web filter enhancements and bug fixes" 760e9933002a69b43a578f92eabf2c017079e414

For the original thread, please see https://groups.google.com/forum/#!topic/hazelcast/5fPeBLuNi-w

**Comment by mustafaiman** [comment]
A retry policy is already implemented in `ClusteredSessionService`. A thread constantly checks if connection exists regularly in 5 seconds intervals. If connection is lost, it automatically retries. See https://github.com/hazelcast/hazelcast/blob/master/hazelcast-wm/src/main/java/com/hazelcast/web/ClusteredSessionService.java#L108 . If this is what you are trying to do, it is already implemented. Otherwise can you please elaborate what you would like to do?

**Comment by danfink** [comment]
I don't understand how ClusteredSessionService is related to this bug.  

If this really does solve this bug, can you provide an example of how I should configure the hazelcast client?  And what about the property, connection-attempt-limit, which is in the documentation but is overridden by hazelcast internally?

**Comment by mesutcelik** [comment]
Hi @danfink ,

Can you please send us your webfilter configuration? Are you using sticky or non-sticky sessions?

**Comment by danfink** [comment]
Sure, glad to :)  As you can see, it is not configured for sticky sessions.  Here is the configuration:

<filter>
    <filter-name>hazelcast-filter</filter-name>
    <filter-class>com.hazelcast.web.WebFilter</filter-class>
    <init-param>
        <param-name>map-name</param-name>
        <param-value>frontendSessions</param-value>
    </init-param>
    <init-param>
        <param-name>session-ttl-seconds</param-name>
        <param-value>0</param-value>
    </init-param>
    <init-param>
        <param-name>sticky-session</param-name>
        <param-value>false</param-value>
    </init-param>
    <init-param>
        <param-name>cookie-name</param-name>
        <param-value>hazelcast.sessionId</param-value>
    </init-param>
    <init-param>
        <param-name>cookie-domain</param-name>
        <param-value>my-domain.com</param-value>
    </init-param>
    <init-param>
        <param-name>cookie-secure</param-name>
        <param-value>false</param-value>
    </init-param>
    <init-param>
        <param-name>cookie-http-only</param-name>
        <param-value>false</param-value>
    </init-param>
    <init-param>
        <param-name>debug</param-name>
        <param-value>true</param-value>
    </init-param>
    
    <init-param>
        <param-name>instance-name</param-name>
        <param-value>default</param-value>
    </init-param>
    <init-param>
        <param-name>use-client</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <param-name>client-config-location</param-name>
        <param-value>/WEB-INF/hazelcast-client.properties</param-value>
    </init-param>
    <init-param>
        <param-name>shutdown-on-destroy</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <param-name>deferred-write</param-name>
        <param-value>true</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>hazelcast-filter</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>FORWARD</dispatcher>
    <dispatcher>INCLUDE</dispatcher>
    <dispatcher>REQUEST</dispatcher>
</filter-mapping>

<listener>
    <listener-class>com.hazelcast.web.SessionListener</listener-class>
</listener>

**Comment by mesutcelik** [comment]
I think `ClusteredSessionService` is supposed to handle client retry in case of `sticky-sessions`. Client/Server Topology with sticky sessions fall back to local mode if client can't reach to the server. Limiting `connection-attempt-limit` to 1 is because we want to keep retry mechanism short and sync the data when server connection is available.

Having said that, your case is non-sticky configuration so normally you are free to define your connection retry settings. AFAIS, `ClusteredSessionService` should be disabled in case of non-sticky configuration. Let us check the issue and hopefully fix it in 3.6 release. Unfortunately, that is not a strict promise as we are very busy with so many other things and very close to the 3.6 release.

**Comment by danfink** [comment]
cool -- this makes sense. thank you
