### ISSUE TITLE
AbstractEntryProcessor should take into account that entry.getValue() can be null for backup processor

### ISSUE THREAD

**Issue by wimdeblauwe** [hazelcast/hazelcast#6578]
This issue is related to #6162 

The class `AbstractEntryProcessor` should adhere to the guidelines set forth in the [Javadoc of EntryBackupProcessor](https://github.com/hazelcast/hazelcast/blob/v3.5.3/hazelcast/src/main/java/com/hazelcast/map/EntryBackupProcessor.java#L25-L30) and take into account that `entry.getValue()` might return `null` in the backup processor, although it was not null in the primary processor.

**Comment by enesakar** [comment]
There are 2 solutions but both have flaws  :
1- We can catch NPE in backup of AbstractProcessor and ignore it. But then we might ignore real NPE cases.
2- We can test if entry value is null; then skip backup processor if value is null. But someone can write an EntryProcessor which has a defined action when value does not exist (null).

So only solution seems to me update docs (both reference manual and javadocs) and want users to handle null values themselves if they will use abstract entry processor.

Something like that:
`Note that there is a possibility which an AbstractEntryProcessor can see
that a key exists but its backup processor may not find it due to an unsent backup of a previous operation (e.g. a previous put). In those situations, Hazelcast internally/eventually will sync those owner and backup partitions so you will not lose any data.
Because AbstractEntryProcessor uses the same processor in both owner and backup, you should take this case into account when coding AbstractEntryProcessor.
`
