### ISSUE TITLE
[TEST-FAILURE] HazelcastOSGiScriptEngineTest FAILURES

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6657]
**bindingsGetAndSetSuccessfully**
**putAndGetSuccessfully**
**putAndGetOverBindingsSuccessfully**
**putAndGetContextSuccessfully**

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/245/#showFailuresLink

**Comment by serkan-ozal** [comment]
We need to use newer versions of JRuby for example (`1.7.22`) because we use `1.7.6` version and it doesn't support Java 9.
https://github.com/jruby/jruby/blob/1.7.6/core/src/main/java/org/jruby/RubyInstanceConfig.java#L1835
but `1.7.22` does https://github.com/jruby/jruby/blob/1.7.22/core/src/main/java/org/jruby/RubyInstanceConfig.java#L1855

**Comment by serkan-ozal** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/b9109d86df3008077ce26aac62f800f10056974a 
See https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/246
