### ISSUE TITLE
MapStoreEvictionTest.testLoadsLessThanMaxSize_whenEvictionEnabledAndReloaded

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6772]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.mapstore.MapStoreEvictionTest.testLoadsLessThanMaxSize_whenEvictionEnabledAndReloaded(MapStoreEvictionTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6/com.hazelcast$hazelcast/7/testReport/junit/com.hazelcast.map.mapstore/MapStoreEvictionTest/testLoadsLessThanMaxSize_whenEvictionEnabledAndReloaded/

**Comment by cangencer** [comment]
new failure: 

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/17070/testReport/junit/com.hazelcast.map.mapstore/MapStoreEvictionTest/testLoadsLessThanMaxSize_whenEvictionEnabledAndReloaded/

**Comment by jerrinot** [comment]
I believe this is a fragile test. it failed because a key iterator has not be closed. however the test [assertion](https://github.com/jerrinot/hazelcast/blob/af191cac115a9c4e5556f3162c6278b4cfda1e43/hazelcast/src/test/java/com/hazelcast/map/mapstore/MapStoreEvictionTest.java#L93) seems to be racy. 

as the iterator is [closed](https://github.com/jerrinot/hazelcast/blob/2a7f2ba20ca3345fb12d2d586a97e784feed5f5e/hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java#L279) *after* the notifications about end of loading [is sent](https://github.com/jerrinot/hazelcast/blob/2a7f2ba20ca3345fb12d2d586a97e784feed5f5e/hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java#L276).
