### ISSUE TITLE
IMap#localKeySet(Predicate) returns data owned by all cluster members when index enabled

### ISSUE THREAD

**Issue by kkolyan** [hazelcast/hazelcast#6840]
Hazelcast 3.5.2, 2 cluster members, 0-2 clients, java 1.8.0_40 (Hotspot), windows 7. Unit test to reproduce: https://github.com/kkolyan/hz-index-issue

**Comment by pveentjer** [comment]
@kkolyan thanks! This will be very helpful to resolve the problem.

**Comment by pveentjer** [comment]
I had a closer look at your test and the following line doesn't make sense to me:

'''
assertEquals(mapValuesSizesToString(foundByPredicateByMember), 1, foundByPredicateByMember.size());
'''

You have a 2 node cluster, so the size of foundByPredicateByMember will be 2. But the expected value is 1. So imho it is a bug in your test.

**Comment by pveentjer** [comment]
I have been playing a bit more with the test and I definitely see something strange.

When I print the size of the results when no index is used:
```
mapsize:2000
node1.map.local.size:1001
node2.map.local.size:999
node1.predicate.size:51
node2.predicate.size:49
equals: false
```
This is to be expected. The sizes of the results on both nodes is not equals 51 and the other one 49.

When I print the size of the results when index is used:
```
mapsize:2000
node1.map.local.size:1051
node2.map.local.size:949
node1.predicate.size:100
node2.predicate.size:100
equals: true
```

Here I do see a problem because the size of the results is now 100+100 so twice as big.

It certainly seems that when indexes are used, all results are returned.

**Comment by kkolyan** [comment]
> You have a 2 node cluster, so the size of foundByPredicateByMember will be 2. But the expected value is 1. So imho it is a bug in your test.

whe are calling localKeySet. As I understand it should return data owner only by 1 member (local), so expectiong 1 is correct.

**Comment by pveentjer** [comment]
I have confirmed the bug. 

What we see is that in case of backups, than all the primary data + the backup data is find in the index.

So
in a 1 node cluster, 100% of items are found
In a 2 node cluster, 100% of item are found (50% of primary and 50% by backup) instead of 50%
In a 3 node cluster 67% of items are found (33% of primary and 33% of backup) instead of 33%
In a 4 node cluster 50% of items are found (25 primary and 25% of backup) instead of 25%

When a configure  4 node cluster with 3 backups, 100% of the items are found instead of 25 due to the 3 backups.

**Comment by kkolyan** [comment]
Thanks for explanation!

**Comment by pveentjer** [comment]
Another observation: when I inject the same data using the IMap.put instead of relying on a MapLoader, there are no problems. So it appears that the MapLoader triggers the insertion of backup data into the index.

**Comment by kkolyan** [comment]
Interesting. It explains why original issue doesn't affect some parts of our application.

**Comment by serkan-ozal** [comment]
this issue occurs at master branch also. I am on it
