### ISSUE TITLE
(3.5.3) Hazelcast is intolerant to 127.0.0.1 address in tcpip members list

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [hazelcast/hazelcast#6906]
Faced this issue recently:
We have a 4-node cluster, members list is [n1,n2,n3,n4]
Added new node to the cluster with members [n1,127.0.0.1]
all nodes started to fail with following repeating messages efficiently killing our appication:

```
INFO: [n1]:5801 [cluster-name] [3.5.3] Connecting to /127.0.0.1:5801, timeout: 0, bind-any: true
Nov 24, 2015 1:58:55 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [n1]:5801 [cluster-name] [3.5.3] Established socket connection between /127.0.0.1:38361
Nov 24, 2015 1:58:55 PM com.hazelcast.nio.tcp.SocketAcceptor
INFO: [n1]:5801 [cluster-name] [3.5.3] Accepting socket connection from /127.0.0.1:38361
Nov 24, 2015 1:58:55 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [n1]:5801 [cluster-name] [3.5.3] Established socket connection between /127.0.0.1:5801
Nov 24, 2015 1:58:55 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [n1]:5801 [cluster-name] [3.5.3] Wrong bind request from Address[n1]:5801! This node is not requested endpoint: Address[127.0.0.1]:5801
Nov 24, 2015 1:58:55 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [n1]:5801 [cluster-name] [3.5.3] Connection [/127.0.0.1:38361] lost. Reason: Socket explicitly closed
```

**Comment by lichtin** [comment]
I can second that. A 127.0.0.1 address in the members list will confuse the join.

**Comment by gurbuzali** [comment]
I can confirm that `127.0.0.1` in the members list will cause problems while joining and leaving the cluster. While starting up the node hazelcast picks the matching IP address for its own. For example machine has two network interfaces which are `192.168.12` and `10.0.0.1`, if you put `10.0.0.1` to the member list, node will identify itself whit that IP.

For above case, joining node identifies itself with `127.0.0.1`, which is problematic because other nodes will try to open connection to themselves. We'll fix this by not letting the node to join to the cluster at all for 3.9. 

For now we can say that do not have `127.0.0.1` in your member list if it is not just for simple testing on your local. We'll modify the documentation to reflect this condition.

Thank you for the issue

**Comment by devozerov** [comment]
Hi colleagues. I looked at the proposed PR (#16109) and have a question - what actual behavior do we expect after the fix? On the one hand, having the loopback on the list is a problem for production deployments. On the other, it might be very handy for local testing, e.g. when we define two nodes on the loopback interface on different ports, and they discover each other smoothly. 
if we are going to restrict the loopback at all, how would we recommend for users to perform local testing with several nodes?

**Comment by mmedenjak** [comment]
Agree with @devozerov and @tkountis . True, we might "improve" the situation by imposing some restrictions, but there's no one-size-fits-all solution. Allowing loopback to prototype and develop is great but I believe that in all other staging/test/production scenarios you'll want to specifically define not only correct hostnames but also correct ports for all cluster members. If this is a configuration burden, you can also use a discovery strategy to discover the member list at runtime. Not defining the exact hosts and port numbers in real deployment scenarios not only leaves room for ambiguities but also poses security issues.

**Comment by tkountis** [comment]
Closing, works as expected.
