### ISSUE TITLE
Create SPI for WAN replication discovery/configuration

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#6925]
Feature request: There should be a WAN replication discovery/SPI configuration module that permits people to configure this on the fly (like the discovery strategy SPI)

**Comment by sushilkumarchaudhary** [comment]
@bitsofinfo What is the status of the issue. Which verison this feature is available?

**Comment by bitsofinfo** [comment]
Status = nothing, backlog, see above

**Comment by mmedenjak** [comment]
WAN replication with discovery SPI has been a part of the enterprise version of hazelcast since 3.8. Please take a look: http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#defining-wan-replication-using-discovery-spi

If there is more to this issue, feel free to reopen or create a new issue.
