### ISSUE TITLE
WriteBehindMapStore + OBJECT in-memory maps cause EntryProcessors to serialize objects

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast#7040]
The issue is on line 103 of WriteBehindMapStore.java (Hazelcast 3.5.4):

        // we will be in this `if` only in case of an entry modification via entry-processor.
        // otherwise this extra serialization of value should not be happen.
        if (InMemoryFormat.OBJECT.equals(inMemoryFormat)) {
            value = toData(value);
        }

This causes *all* EntryProcessor runs that call entry.setValue() to serialize the object, leading to lower performance, similar to that of BINARY in-memory format.

Any particular reason for this serialization? This renders OBJECT in-memory format not viable when using write-behind with Hazelcast.

**Comment by ahmetmircik** [comment]
Hi @fschuh, 

Write-behind can be used to persist all states of an entry.

If in-memory-format is OBJECT, there is a possibility that a previous state of an entry can be overwritten by a subsequent write operation while both are waiting in the write-behind-queue because they are referencing to the same entry value. To prevent this, we are taking a snapshot by converting value to binary/data, otherwise we can lost a state.

**Comment by fschuh** [comment]
I see.
But in coalescing mode, only the last state should be persisted, correct?
And if the WriteBehindMapStore persist code runs on the same partition thread, there should be no dangers of having the object changed while the persistence is taking place.

The behavior you suggest makes sense if coalescing is disabled, but not when it's enabled.

**Comment by ahmetmircik** [comment]
you are right, will fix it.

**Comment by fschuh** [comment]
Great :)
Thanks for the quick reaction to the issue.
