### ISSUE TITLE
Performing action after server starts

### ISSUE THREAD

**Issue by travikk** [hazelcast/hazelcast#7457]
Hello,

Assume a scenario, where a hazelcast client is started and awaits hazelcast server to start up, in order to perform executeOnEntries on a specific map.
In order to do so I used MembershipListener combined with InitialMembershipListener to accomodate for scenario where server starts first.

Unfortunately, performing executeOnEntries on a map does not have any effect at this point, i.e. entry processor is not called. I assume this is due to the call being made too early.

There should be a way to listen on a READY event, when the server instance is ready to accept inquiries.

**Comment by sancar** [comment]
@travikk 
`HazelcastInstance client = HazelcastClient.newHazelcastClient(); `
waits for server to start and ready. In case server is not ready, `HazelcastNotActiveException` is thrown and handled internally so that users are blocked until server is ready. 

If you do a simply following
```
HazelcastInstance client = HazelcastClient.newHazelcastClient(); 
IMap map = client.getMap("m") ;
map.executeOnEntries()
```

Either first line will throw exception saying it can not connect to cluster, or `executeOnEntries` will successfully run because in the second line, it makes sure that client is connected to a ready cluster. 

>>> Unfortunately, performing executeOnEntries on a map does not have any effect at this point, i.e. entry processor is not called. I assume this is due to the call being made too early.

Not sure how do you see that `executeOnEntries` does not any effect. When it does not work, it throws an exception. The exception will say why it did not work.

**Comment by sancar** [comment]
@travikk Closing the issue since it is too old. Feel free to ask any related question here, or in google group https://groups.google.com/forum/#!forum/hazelcast
