### ISSUE TITLE
OSGi bundle install failure in 3.6.1

### ISSUE THREAD

**Issue by skellogg** [hazelcast/hazelcast#7772]
in Karaf, bundle:install...
Error executing command: Can't install feature cosc-base/0.0.0:
Could not start bundle mvn:com.hazelcast/hazelcast/3.6.1 in feature(s) cosc-base-0.0.1-SNAPSHOT, cosc-api-0.0.1-SNAPSHOT: Unresolved constraint in bundle com.hazelcast [114]: Unable to resolve 114.0: missing requirement [114.0] osgi.wiring.package; (osgi.wiring.package=com.hazelcast.client.impl.protocol.codec)

**Comment by serkan-ozal** [comment]
This should have been fixed by this PR https://github.com/hazelcast/hazelcast/pull/7630
So this issue will be fixed at 3.6.2+ and 3.7 releases

**Comment by skellogg** [comment]
I failed to mention, it worked fine in 3.6.0, but failed in 3.6.1

**Comment by skellogg** [comment]
didn't mean to close, sorry.

**Comment by serkan-ozal** [comment]
Hi @skellogg 

Yes, there is no issue at **3.6.0**. Because the issue has been occured since **3.6.1** after `hazelcast-client-protocol` depedency has been added. 

With **3.6.2** it will be OK since there will be no import package statement for `com.hazelcast.client.impl.protocol.codec` with this PR #7630.
