### ISSUE TITLE
Creating index with wrong key-attribute definition does not throw an error

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#7832]
When creating indexes on keys you can define wrong specs without an error being thrown.

Correct:
```
map.addIndex("__key#login");
```

Wrong:
```
map.addIndex("__key.login");
``` 

Anyhow the latter does neither throw an exception, nor is it automatically corrected. The index is created but empty and will never be used. This results in extremely poor performance of queries without any visible reason (as a full table scan is executed).

**Comment by jerrinot** [comment]
I'm thinking about it and it's tricky to throw an exception. As it could be a legitimate field name. 
Perhaps we could print a hint? WDYT?

**Comment by vbekiaris** [comment]
@noctarius should we go ahead with printing a hint? what do you think?

**Comment by tombujok** [comment]
As stated `__key.login` may be a valid nested path thus we can't throw an exception in this case.
I'll add a warning in the log if a path with `__key` prefix is used without a `#` after it.

**Comment by noctarius** [comment]
I guess a warning while parsing it is perfectly fine. At least you point people into the right direction :)

**Comment by noctarius** [comment]
PS: wouldn't it be the same issue when querying? I mean that way we shadow the possibly existing `__key' value: https://github.com/hazelcast/hazelcast/blob/d0336a3b51893688e0d8116ec5c94d428a252e39/hazelcast/src/main/java/com/hazelcast/query/QueryConstants.java#L27

**Comment by tombujok** [comment]
There's two ways of adding an index:

- IMap.addIndex
- MapIndexConfig

It's easy to add a Log entry in the first case, but impossible in the other case, since we don't have a logger instance. Adding post-creation config validation seems like an overkill for this simple task.

I'm moving the issue to backlog milestone to track it for future (either big traction or logging-system simplification).
