### ISSUE TITLE
outbound port range not working

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast#7895]
Based on this SO, it appears there are issues staying within outbound port ranges.

http://stackoverflow.com/questions/36148585/hazelcast-uses-ephemeral-port-for-outbound-traffic-in-spite-of-configured-specif

**Comment by nilskp** [comment]
Somewhat related: #6350

**Comment by noctarius** [comment]
I think this request is similar too http://stackoverflow.com/questions/36364997/connection-issue-with-hazelcast-on-amazon-aws

**Comment by jerrinot** [comment]
@vbekiaris: it appears it was a configuration error after all. is this correct?

**Comment by vbekiaris** [comment]
Yes, at least this one: http://stackoverflow.com/questions/36364997/connection-issue-with-hazelcast-on-amazon-aws was due to "0" being used as part of the range; whenever 0 is included in outbound-ports (as part of range or CSV), hazelcast interprets this as "use ephemeral ports".
Still investigating the original SO question that initiated this issue.

**Comment by vbekiaris** [comment]
There has been no update from the original SO question that initiated this issue. If there is no further evidence of an issue, should we close this issue?

**Comment by jerrinot** [comment]
Everything seems to work fine on our side. 
I'm closing this as there the original author on SO is unresponsive.
