### ISSUE TITLE
Allow Hazelcast instance to be set in Lifecycle listeners

### ISSUE THREAD

**Issue by iaptekar** [hazelcast/hazelcast#7917]
It would be useful to be able to get a Hazelcast instance set in a LifecycleListener, preferably using the HazelcastInstanceAware interface

**Comment by seanschen** [comment]
Hi, is this still an issue? I can take a stab at it, but what is the use case for setting a Hazelcast instance set in a LifecycleListener?

**Comment by dbrimley** [comment]
I too would be interested in the use case for this, so we can think this over some more.

A major concern would be the thread that is executing the `LifecycleListener`, I'd need to look into that.

This issue is 3 years old now, so possible @iaptekar has lost interest in this request.

I'll leave this issue open for seven days and then close it if I hear no response.

**Comment by Holmistr** [comment]
@dbrimley @iaptekar @seanschen Any news here? It got a bit outdated :trollface:

**Comment by dbrimley** [comment]
It seems dead, I'm going to close it.
