### ISSUE TITLE
Unexpected memory consumption/memory leak?

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#8478]
HZ 3.6/3.7-EA.
I have a following cache configuration:
```
<hz:map name="xdm-element" in-memory-format="BINARY" async-backup-count="1" 
	backup-count="0" read-backup-data="false" cache-deserialized-values="INDEX-ONLY">
	<hz:indexes>
		<hz:index attribute="pathId" ordered="true"/>
	</hz:indexes>
</hz:map>
```
With this config I see all cache entries are kept in memory twice: in binary form as byte[] and in Object form. As I see from heap dump, they're referenced from `CachedDataRecordWithStats.cachedValue` and `CachedQueryEntry.valueObject` Hazelcast structures. If I set `cache-deserialized-values="NEVER"` then the Object instances are not stored. Is it a correct behaviour? My understanding was that with `INDEX-ONLY` setting only the indexed value will be stored (int, in my case), not the whole Object structure.

Please have a look.
Thanks, Denis.

**Comment by tombujok** [comment]
@dsukhoroslov That's a correct behaviour - it's like a tunnable trade-off between always cache de-serialised values, never cache them or cache them only if any indexes defined. (It's not very intuitive though, I have to admit. It's due to the fact that there's a legacy setting playing a role here). 

`INDEX_ONLY` means that the deserialised value will be cached if there is at least one indexes defined for this map. It's due to the fact that if there's a index defined the object will be deserialised anyway, thus we may use the cached value while querying. Plz, see here:
https://github.com/tombujok/hazelcast/blob/227d93278e55aeb2ca8077a9f60b4cd51640f0af/hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java#L310-L311

Hope it helps!
