### ISSUE TITLE
Bulk Get with 100 keys fails

### ISSUE THREAD

**Issue by wolframite** [hazelcast/hazelcast#8535]
A real memcached instance can fetch more than 150 keys at the same time, hazelcast fails at that because the capacity in the `com.hazelcast.nio.ascii.TextReadHandler` is set too low (currently 500).

If this is raised to e.g. 5000, it's possible to fetch 100 keys with a key length of 32 byte. I wrote a unit test, to reproduce the problem: https://github.com/zalora/hazelcast/commit/1c2d4fe14930782d33647cffdd2a0f575b36022c

Is it ok, if I raise the buffer size to 5000 and create a pull request for it? I already signed the contributor agreement form: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by noctarius** [comment]
Hey Wolfram,

Glad to see you're still working with Hazelcast. Unfortunately you still have to use the memcached API since the PHP is not ready ;-)

As long as you signed the CLA already you're good to send a PR including the fix and a unittest to proof the fix.

**Comment by Lunatic666** [comment]
Oh, I'm not only working with Hazelcast, we're currently rolling it out at work as a replacement for Memcached. That's why I want to make Hazelcast more Memcached compatible. Unfortunately the PHP client has to wait until we're done with the rollout. 

I have some more changes in the pipeline, but I'd like to discuss them first and ask if there are better ways to achieve the goal. I'll send the PR and will mention the issue here...

**Comment by LoneRifle** [comment]
@Lunatic666 I will be happy to help out with implementing the changes you may be proposing. @noctarius should be able to provide you with my contact details, or get hold of me on gitter.

**Comment by noctarius** [comment]
Love the community spirit :) Please guys, go ahead!

**Comment by Lunatic666** [comment]
@LoneRifle Thanks for the offer! I'll catch up with you on Gitter

**Comment by sancar** [comment]
merged to https://github.com/hazelcast/hazelcast/issues/9355
