### ISSUE TITLE
Add size(Predicate) to determine the size of predicate results

### ISSUE THREAD

**Issue by adasari** [hazelcast/hazelcast#8555]
IMAP::Values(Predicate).szie() would return the collection for the predicate and get the size. Tracking the collection for the predicate is undesired to determine the size.

Can you add IMap::size(Predicate) which only returns size and does not care collection for the predicate?

Thanks.

**Comment by tombujok** [comment]
Thanks, looks legit. Probably `IMap.count(Predicate)` would be a better name.

**Comment by tombujok** [comment]
Since 3.8 you can use map.aggregate(Aggregators.count());

**Comment by mzuberbhatuk** [comment]
Hello @tombujok 
Is this feature accomplished? I checked 3.11 version but couldn't see any method like IMap.count(Predicate). Please let me know.

Thank You
Zuber

**Comment by taburet** [comment]
@mzuberbhatuk you may use `IMap.aggregate(Aggregators.count(), predicate)` to accomplish this. As of  3.10 it won't materialize result sets if indexes are not used for a predicate evaluation, so counting is cheap; for indexed queries result sets are still materialized as of 3.11.

**Comment by mzuberbhatuk** [comment]
Thank you @taburet for quick reply. 
Right now I am using version 3.7.3 and EntryProcessor to count the result. I have two concerns as below if you could address please.
1. If I upgrade the hazelcast to 3.11, would it cause any issue?
2. The use of aggregate is efficient and faster then EntryProcessor?

**Comment by taburet** [comment]
1. We are preserving backward API compatibility, so it should not cause any issues, but I still highly recommend to test the new version in a separate isolated environment before deploying to production. 

2. I guess you are using a solution like https://stackoverflow.com/a/38474504, aggregations should be faster since a final result is directly computed by Hazelcast cluster in a more efficient way. Even if you would use indexes to speed up the predicate evaluation, it still should be faster, but might be more memory hungry.

**Comment by mzuberbhatuk** [comment]
@taburet, 
#1, agreed with you. We will first check on QA.
#2, your guess is correct. I will convert it to aggregations.

Thank you for your quick support. Highly appreciated. :)
