### ISSUE TITLE
Reliable topic subscriber's don't recipes all Msg's from publisher. 3.8-SNAPSHOT

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8980]
Default behaviour for reliable topic  `topic.publish(val);`
`public static final TopicOverloadPolicy DEFAULT_TOPIC_OVERLOAD_POLICY = BLOCK;`

1 publisher on 1 client using 1 thread  (Msg size byte[1] )
4 subscribers on 4 clients,  1 per client

`topicA-published=378281 != topicA-subscriber-0=376108`

subscribers pause for 60 second after publisher ends, to catch last msg's

this issues, is replicated with out cluster manipulations, however failure is intermittent, but not rare.
fails 1 in 3 runs approx. 

This nightly build https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/12/console
suffers from the same issue,  however the scenario contains cluster shutdown and restart.
and fails more frequently.

**Comment by pveentjer** [comment]
I don't know if it is critical since it isn't something which disturbs the whole system.

**Comment by vbekiaris** [comment]
@Danny-Hazelcast can you please link to the test code? Is this still failing in 3.8? I cannot reproduce it in 3.8.

**Comment by Danny-Hazelcast** [comment]
@vbekiaris to day we have had 1 passing run and 1 failing run using 3.8-RC1

https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/

https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/54/consoleFull
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/55/consoleFull

the config for the test is 
https://github.com/Danny-Hazelcast/hzCmd-bench/tree/zeta/lab/hz/shutdown/topic

from 1 client we publish to a topic 
https://github.com/Danny-Hazelcast/hzCmd-bench/blob/zeta/lab/hz/shutdown/topic/pub

the publisher, publishes to a topic, and counts every successful call to 

`topic.publish(val);`

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/b70f07a0be55b5f8de939ef6fd74c34774c98e07/src/main/java/hz/topic/Publisher.java


the subscriber's  on all clients,  
https://github.com/Danny-Hazelcast/hzCmd-bench/blob/zeta/lab/hz/shutdown/topic/sub

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/b70f07a0be55b5f8de939ef6fd74c34774c98e07/src/main/java/hz/topic/Subscriber.java

counts the number of events recived.

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/b70f07a0be55b5f8de939ef6fd74c34774c98e07/src/main/java/hz/topic/MsgCounter.java


all subscribers pause for 60 seconds at the end to hover up any left over events,
or so i hope.


then we run validate from one member 
https://github.com/Danny-Hazelcast/hzCmd-bench/blob/zeta/lab/hz/shutdown/topic/validate

and check the counts on subscribers  match the count on the publisher
https://github.com/Danny-Hazelcast/hzCmd-bench/blob/9a1e7d490a9aaf642f4e3ca16e5fa8ade456ed7b/src/main/java/hz/topic/PubSubAssert.java

**Comment by vbekiaris** [comment]
The configuration of the `ReliableTopic` and associated `Ringbuffer` in the test inherit the defaults, here are the interesting config options:
```
ReliableTopic: overflowPolicy -> BLOCK
Ringbuffer: timeToLiveSeconds -> 0
```
The above configuration combination behaves as if overflow policy was `DISCARD_OLDEST`: due to the absence of ttl [remainingCapacity()](https://github.com/hazelcast/hazelcast/blob/0c7a30a4ff7b775f38eb30cdfb5845ea6704aa45/hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java#L204-L204) is always reported to be the ringbuffer's `capacity`, so new items will be always added to the ringbuffer, resulting in oldest items being discarded from the ringbuffer -> some listeners may lose messages. I suggest we update the test configuration to enable ttl (eg 60 seconds) and observe its behavior.

Apart from that, the specific configuration combination (`BLOCK` & `ttl=0`) does not behave as expected; would it make sense to stick to the `BLOCK` behavior even when ttl is 0? In this case, once the ringbuffer is filled, then every subsequent `topic.publish` would block. What do you think @pveentjer ?

**Comment by Danny-Hazelcast** [comment]
with the new xml config i had a passing and failing run

https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/57/consoleFull

`HzMember1HZ validate hz.topic.PubSubAssert threadId=0 global.AssertionException: topicA-published=390001 != topicA-subscriber-0=386889 `

http://54.87.52.100/~jenkins/workspace/shutdown-topic/3.8-SNAPSHOT/2017_02_03-13_18_14/config-hz/hazelcast.xml

```
<reliable-topic name="topic*">
<topic-overload-policy>BLOCK</topic-overload-policy>
<statistics-enabled>false</statistics-enabled>
</reliable-topic>
<ringbuffer name="topic*">
<time-to-live-seconds>60</time-to-live-seconds>
</ringbuffer>
```

**Comment by vbekiaris** [comment]
In a separately developed member bounce test I wasn't able to reproduce the issue, unless there was not enough `time-to-live` / `capacity` for consumers to catch up, however in this case the message listener is cancelled with a corresponding log entry. In failed runs, only expected exceptions are logged (eg connection setup/teardown as members bounce).

I think the issue may be due to the Hazelcast cluster being shutdown immediately after `Member1` was just restarted by the `hz-cluster-shutdown` member bouncing script --> subscribers may not have enough time to establish connection and retrieve messages from just-started member. This is excerpt from the test execution script:
```bash
hz run sub &
hz run pub &
hz-cluster-shutdown
# last commands were hz embeddedRestart Member1, hz check 
hz stop
wait
hz run validate
```

Introducing some wait time (eg `sleep 60`) before `hz stop` will allow `Member1` time to deliver messages to subscribers. Also, it looks like the publisher task may stop after subscribers are stopped --> messages may be published after a subscriber was stopped and the test will fail.

**Comment by Danny-Hazelcast** [comment]
@vbekiaris  this hz-cluster-shutdown script
https://github.com/hazelcast/hzCmd-bench/blob/zeta/bin/hz-cluster-shutdown

we wait 30 seconds after each cluster shutdown,  before shutdown down the next member

**Comment by Danny-Hazelcast** [comment]
or you mean hear we should to a bit more sleeping https://github.com/hazelcast/hzCmd-bench/blob/zeta/bin/hz-cluster-shutdown#L28

**Comment by vbekiaris** [comment]
yes, that's what I mean, the last iteration's member restart will then do a `hz check` and immediately `hz stop` (in `go` script), so I was thinking about some sleep before `hz stop`.

**Comment by Danny-Hazelcast** [comment]
@vbekiaris 

the publisher will stop after it sends its last msg
https://github.com/hazelcast/hzCmd-bench/blob/b70f07a0be55b5f8de939ef6fd74c34774c98e07/src/main/java/hz/topic/Publisher.java

and the subscriber will wait for 60 seconds after the stop in the post phase
to hoover up the last in coming msgs events.
https://github.com/hazelcast/hzCmd-bench/blob/b70f07a0be55b5f8de939ef6fd74c34774c98e07/src/main/java/hz/topic/Subscriber.java#L22

so i think i have all ready allowed for the situation you are describing

**Comment by mmedenjak** [comment]
@Danny-Hazelcast can you enable the validation and run again?

**Comment by Danny-Hazelcast** [comment]
re running https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/

**Comment by Danny-Hazelcast** [comment]
we still have the same fail mode, we are missing one msg.
we published 1 more msg than we recived. 

`fail HzMember1HZ validate hzcmd.topic.PubSubAssert threadId=0 global.AssertionException: topicA-published=110001 != topicA-subscriber-2=110000 `

**Comment by mmedenjak** [comment]
The TTL has been set to 60 seconds:
```
    <reliable-topic name="topic*">
        <topic-overload-policy>BLOCK</topic-overload-policy>
        <statistics-enabled>false</statistics-enabled>
    </reliable-topic>

    <ringbuffer name="topic*">
        <time-to-live-seconds>60</time-to-live-seconds>
    </ringbuffer>
```

After setting to zero, the test doesn't seem to fail. I am still unsure why this is happening.

**Comment by Danny-Hazelcast** [comment]
from  https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-topic/  which has multiple passed runs.
i found that all the passing run were using only one client and one thread to publish to the 1 topic, while member nodes were shutdown and restarted
then i ran the test publishing from all clients while the members are shutdown and restarted,  and i had a failing and passing run (edited)
I also found the same behaviour in the rolling upgrade version of the test, when i publish to the topic with just one client then i get a pass
but when publishing from multi clients, we get the same issue.
i see that the stable version of the test is ok when publishing from multi clients.
I am now using
 ```<reliable-topic name="topic*" >
        <topic-overload-policy>BLOCK</topic-overload-policy>
        <statistics-enabled>false</statistics-enabled>
    </reliable-topic>

    <ringbuffer name="topic*">
        <time-to-live-seconds>0</time-to-live-seconds>
    </ringbuffer>```

**Comment by Danny-Hazelcast** [comment]
In a stable version of my topic test i see this logged.
`WARNING: [10.0.0.137]:5701 [HZ] [3.11-SNAPSHOT] Terminating MessageListener:hzcmd.topic.MsgCounter@4460d7c2 on topic: topicA0. Reason: The listener was too slow or the retention period of the message has been violated. head: 335207 sequence:335202` 
I am using
 ```
<reliable-topic name="topic*" >
        <topic-overload-policy>BLOCK</topic-overload-policy>
        <statistics-enabled>false</statistics-enabled>
    </reliable-topic>

    <ringbuffer name="topic*">
        <time-to-live-seconds>0</time-to-live-seconds>
    </ringbuffer>
```
i assume that `<time-to-live-seconds>0</time-to-live-seconds>` means that. retention can not been violated.
and that `<topic-overload-policy>BLOCK</topic-overload-policy>`  mean's that topic can not overflow / loose msgs.


in the above failing test, i am using 2 threads to publish msg's to the topic.
I see that only subscriber `MessageListener` running on a member  is not receiving `Terminating MessageListener` warning.
I see that this member has the correct number of published and received messaged. (edited)
maybe this is the member that owns the topic `topicA0` ?
when i re-run the test using 1 thread to publish msg's to the topic, the test passes (correct number of messages published and received).

**Comment by mmedenjak** [comment]
When `time-to-live-seconds==0`, the oldest items are always overwritten and the `<topic-overload-policy>BLOCK</topic-overload-policy>` will be ignored. The policies only come into effect when TTL is greater than zero. Otherwise it would never unblock as once the ringbuffer is full, no events would ever get expired.

**Comment by Danny-Hazelcast** [comment]
setting <time-to-live-seconds>0</time-to-live-seconds> resulted in Terminating MessageListener
and so large number of event of "missing"

setting <time-to-live-seconds>60</time-to-live-seconds>, sometimes resulted in 1 or 2 event missing,  because i was waiting for 60 sendson to collect the last events.
giving 0 seconds, to collect the last events.

setting <time-to-live-seconds>45</time-to-live-seconds> and waiting 60 seconds.
gives 15 seconds to collect the last events.

looks like the test is passing much more reliably
