### ISSUE TITLE
DurableExecutorService exceptions

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#9051]
If `DurableExecutorService.retrieveResult(long)` is run from a client for a task that doesn't exist, two exceptions appear on 3.7.1.

In the server logs `StaleTaskIdException`. This shouldn't be logged to the server if re-thrown to the client.

On the client, `ExecutionException`. This should be a `StaleTaskIdException`

**Comment by jerrinot** [comment]
@gurbuzali: are you working on this?

**Comment by mmedenjak** [comment]
The observed behaviours are default for all (or at least more than the one listed) service methods. The wrapping with `ExecutionException` is what you get for all methods that return a `Future`. This is due to the fact that all invocations are wrapped `AbstractInvocationFuture#resolveAndThrowIfException`. On the other hand, methods that return a result with blocking do not wrap because of the exception handling (e.g. `com.hazelcast.client.proxy.ClientRingbufferProxy#invoke`).
And the additional logging is because all operation failures are logged on the instance. 

I propose to keep the current situation since it is a big change to change all future returning methods and as I can see `ExecutionExceptions` are expected - http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#dealing-with-exceptions.

**Comment by jerrinot** [comment]
@mmedenjak: is there some sort of `unpeel`-ing in some cases?

**Comment by mmedenjak** [comment]
We do have `ExceptionUtil#peel(java.lang.Throwable)` which is used in case of authentication or processing failure on the member side. The client side future wraps the exception during `AbstractInvocationFuture.get`.

I have tried with some `IAtomicLong` and `Ringbuffer` asnyc operations, they all exhibit the described behaviour and wrap in an `ExecutionException` on `Future.get`

**Comment by jerrinot** [comment]
in other words: Client violates a contract of `DurableExecutorService` and other data structures. Is this correct? cc @asimarslan

**Comment by Donnerbart** [comment]
I think @pveentjer ran into some troubles with that already, when unifying code between member and client. I don't remember though if he just mimicked the existing behavior (two different exceptions) or if he already changed this for some methods.

**Comment by mdogan** [comment]
`DurableExecutorService.retrieveResult(long)` returns a future and due to `Future` contract, it can only throw one of `InterruptedException`, `ExecutionException`, `TimeoutException`.
So on both member and client, `StaleTaskIdException` can't be thrown, if I'm not missing anything.

**Comment by mdogan** [comment]
And as far as I see, `DurableExecutorService.retrieveResult(long)` doesn't mention anything about `StaleTaskIdException`.

**Comment by mmedenjak** [comment]
Seems right, both member and client invocations which return a future wrap in `ExecutionException`. I don't think there is a reason to change it then.

**Comment by jerrinot** [comment]
The exception is working as expected (per contract of `Future`(s))
