### ISSUE TITLE
IMap entry eviction issue

### ISSUE THREAD

**Issue by pramodterdale** [hazelcast/hazelcast#9095]
I am using IMap to store huge amount of data and each key has specified time-to-live, but some of the keys are not getting evicted at all even after it passed the time to live value. These keys stays forever, so when i check the map size progarmatically it shows there are entries in the map, same is shown in mancenter but when i try to get the list of keys or values nothing comes back. One more observation is that i have backup enabled with count 1, but for these entries there is no backup as well. I have below properties in hazelcast.xml

```
<partition-group enabled="true"/>
<map name="default">
  <time-to-live-seconds>0</time-to-live-seconds>
  <eviction-policy>NONE</eviction-policy>
</map>
```

Code to add messages into the map

```
     msgMap.put(msgId, value, 30, TimeUnit.SECONDS);
```

I have registered the EntryListener for eviction and doing the final activity on evicted entries, most of the entries are getting evicted as expected but some entries are never getting evicted. The final processed enrties are less than total input entries and missing count exactly matches with the map entry size at the end. What could be wrong, why are not all the messages are getting evicted. Am i missing somthing? Attaching the mancenter screenshot

```
   IMap<Long, String> msgMap = getMap("1070810_RM_map");
  System.out.println("MapSize:" + msgMap.size() + " :msgMap:" + msgMap + " :entrySet:" +   msgMap.entrySet());
```

The output is

```
    MapSize:433 :msgMap:1070810_EM_map :entrySet:[]
```

![image](https://cloud.githubusercontent.com/assets/5994348/19295131/7421fdee-9000-11e6-95a1-bcc9e8c9fc73.png)

**Comment by ahmetmircik** [comment]
Hi @pramodterdale, what was your version? Can you test it with latest version 3.7.2?

**Comment by pramodterdale** [comment]
I am able to reproduce the issue on version 3.7 as well as 3.7.2, below screenshot is from 3.7.2 and last one i provided was from 3.7

![hazelcast1](https://cloud.githubusercontent.com/assets/5994348/19537227/32dd24ee-961d-11e6-8fde-d1683177796c.JPG)

**Comment by ahmetmircik** [comment]
Hi @pramodterdale,

First of all, let me clarify some terms. In hazelcast parlance,  expiration and eviction are two different things. Eviction is needed to free memory according to size based policies like map-size or memory-size etc. Expiration is needed to determine life-span of an entry. If your goal is freeing memory you should configure eviction.

In your case, there is no eviction defined since it is NONE -->`<eviction-policy>NONE</eviction-policy>`. But you are using expiration. Hazelcast Map removes expired entries gradually with a background sweeper task. Map size can return those _expired but not yet removed entries_ during that sweep cycle but you can not reach them for ex. via `imap#get`, eventually all expireds will be removed from map. To accelerate this expiration process please see my comments [here](https://github.com/hazelcast/hazelcast/issues/8894#issuecomment-247859168) and see
[this](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/eviction/ExpirationManager.java#L49) for a detailed explanation about those system properties.

Btw, i did a test with your given configuration, all entries were swept eventually. Seems no problem.

**Comment by ahmetmircik** [comment]
any update?

**Comment by pramodterdale** [comment]
The above mentioned settings are working fine but still there is a delay, one more thing i noticed is the sweeper task/thread is slow in processing, is there any way to increase number of sweeper tasks/threads, if yes what is the property that i can use..?

**Comment by ahmetmircik** [comment]
> one more thing i noticed is the sweeper task/thread is slow in processing

why do you think it is slow?

**Comment by jerrinot** [comment]
Hi,

as explained by Ahmet expired entries are not accessible as specified in the expiration interval, however physically they might be removed later. this is working as designed.
