### ISSUE TITLE
(3.7.1) IExecutorService:: Every 101th request is executed synchronously

### ISSUE THREAD

**Issue by manishonline** [hazelcast/hazelcast#9117]
Is there a particular reason why every 101th request submitted to hazelcast IExecutorService is executed synchronously?

I am getting this issue in hazelcast version 3.7.1

It seems to be done on purpose as the following code block in ExecutorServiceProxy suggests 
`boolean sync = this.checkSync();`

checkSync implementation is 

```java
private boolean checkSync() {
        boolean sync = false;
        long last = this.lastSubmitTime;
        long now = Clock.currentTimeMillis();
        if(last + 10L < now) {
            CONSECUTIVE_SUBMITS.set(this, 0);
        } else if(CONSECUTIVE_SUBMITS.incrementAndGet(this) % 100 == 0) {
            sync = true;
        }
    this.lastSubmitTime = now;
    return sync;
}
```

I am not sure of the reasoning behind, but this is massively affecting the throughput. Any way this sync check can be done away with or increase the limit from 100 to say 500 or 1000?

**Comment by manishonline** [comment]
@pveentjer @mesutcelik Dear hazelcast team, Can the issue be acknowledged please? Or else if there is any workaround it will be appreciated. Thanks.

**Comment by jerrinot** [comment]
hello @manishonline: it's done on purpose. the motivation is to provide a basic back-pressure facility. Can you describe your use-case a little bit? 

I can imagine 2 rather simpler improvements here:
1. a simple property to make the threshold configurable
2. instead of having every `n-th` invocation sync we could track number of in-flight executions and block only when it's over a threshold.

**Comment by manishonline** [comment]
@jerrinot 
I am using IExecutorService to distribute computation requests, which generally complete within 100ms. We have  2 computation orchestrator nodes which are firing computation requests while 8 nodes initiated with thread pools for size 200 each serving these compute requests.
Max jobs that orchestrator has been able to submit is around 1200 per second. Even if I add one more orchestrator node, the individual throughput falls to 600 per second while total remains more or less constant.
There will be compute request in future which may take several seconds to complete. If the blocking request happens to one of these, throughput will fall drastically as 101th is going to wait for several seconds.

**Comment by tombujok** [comment]
@tkountis what do we want to do about it?

**Comment by oobles** [comment]
Been observing this issue too.  We perform high speed processing and use our own back pressure mechanism.  We send a lot of small requests and regularly hit a sync'd request.  As this is at the back of the queue on the server, the server needs to clear before returning.  Seen 10+ seconds before the call returns.  

This was very unexpected since we're expecting a Future in response instead of waiting.  A few suggestions.  1.  Expose the sync option so we can choose to have back pressure or not.  2.  Put this in a system property so we can turn it off.

Would be great if someone could confirm if back pressure is also applied to 
   public <T> void submitToKeyOwner(Callable<T> task, Object key, ExecutionCallback<T> callback)

My reading of the code says that if you pass in an ExecutionCallback there's no backpressure applied.  Would building a ExecutionCallbackFuture be a valid work around in current versions?

**Comment by oobles** [comment]
Based on some testing it looks like the submitToKeyOwner that takes an ExecutionCallback does not perform any back pressure checks.  For anyone else with this issue, we wrote the following CallbackFuture class as a way to return a Future.   We only check isDone() rather than call get() so this class is not fully tested.  Use at own risk. :)

We did also notice some InvocationFailure exceptions (id not found) being recorded in Hazelcast when running at high speed.  Looks like Hazelcast will drops the message on the client if it gets too many requests.  Probably the reason the back pressure was added in the first place. 


```
    private static final class CallbackFuture<E> implements Future<E>, ExecutionCallback<E> {

        boolean isDone = false;
        Throwable t = null;
        E e = null;

        @Override
        public boolean cancel(final boolean mayInterruptIfRunning) {

            return false;
        }

        @Override
        public boolean isCancelled() {

            return false;
        }

        @Override
        public boolean isDone() {

            return isDone;
        }

        @Override
        public E get() throws InterruptedException, ExecutionException {

            return e;
        }

        @Override
        public E get(final long timeout, final TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException {
            if (!isDone) {
                synchronized (this) {
                    if (!isDone) {
                        wait(unit.toMillis(timeout));
                        if (!isDone) {
                            throw new TimeoutException();
                        }
                    }
                }
            }

            if (t != null) {
                throw new ExecutionException(t);
            }

            return e;
        }

        @Override
        public void onResponse(final E response) {
            e = response;
            isDone = true;
            synchronized(this) {
                notify();
            }
        }

        @Override
        public void onFailure(final Throwable t) {
            this.t = t;
            isDone = true;
        }

    }

```
