### ISSUE TITLE
AtomicLongAdvancedTest.testAtomicLongFailure

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9202]
```
java.lang.AssertionError: expected:<101> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testAtomicLongFailure(AtomicLongAdvancedTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/5952/testReport/junit/com.hazelcast.concurrent.atomiclong/AtomicLongAdvancedTest/testAtomicLongFailure/

**Comment by mmedenjak** [comment]
Seems as if due to higher load : 
> processors=16, physical.memory.total=4.0G, physical.memory.free=0, swap.space.total=4.0G, swap.space.free=3.9G, heap.memory.used=804.3M, heap.memory.free=161.4M, heap.memory.total=965.7M, heap.memory.max=965.7M, heap.memory.used/total=83.29%, heap.memory.used/max=83.29%, minor.gc.count=2642, minor.gc.time=104659ms, major.gc.count=53, major.gc.time=45547ms, load.process=0.00%, load.system=0.00%, load.systemAverage=2005.00%, thread.count=395, thread.peakCount=3237, cluster.timeDiff=-2185, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=13, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
there were large pauses in the test, the MonitorInvocationsTask and BroadcastOperationHeartbeatsTask were delayed, there were large cluster clock diffs and a node failed to shutdown in 120 seconds. This caused it to send a shutdown message before completing migrations and the cluster. The cluster then completely lost some partitions, including the one for the atomic long.

**Comment by mmedenjak** [comment]
Also, probably because of the high load and slow tests this is what happened:

1. [127.0.0.1]:16493 is STARTED
2. [127.0.0.1]:16494 is STARTING
3. Planning migrations for partitionId=0. Current replicas: [[127.0.0.1]:16493, null, null, null, null, null, null], New replicas: [[127.0.0.1]:16494, [127.0.0.1]:16493, null, null, null, null, null]
4. [127.0.0.1]:16494 is STARTED
5. Planning migrations for partitionId=33. Current replicas: [[127.0.0.1]:16493, null, null, null, null, null, null], New replicas: [[127.0.0.1]:16494, [127.0.0.1]:16493, null, null, null, null, null]
6. [127.0.0.1]:16493 is SHUTTING_DOWN
7. Planning migrations for partitionId=0. Current replicas: [null, null, null, null, null, null, null], New replicas: [[127.0.0.1]:16494, null, null, null, null, null, null]

So the migrations for the 16494 continue after it has declared that it STARTED. The node 16493 and the migration looks like it never got the initial migrations. This is probably why later on it loses these partitions completely.
