### ISSUE TITLE
Map stats are disappeared after member restart

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#9590]
see https://groups.google.com/d/msgid/hazelcast/5be14630-9d9b-4cb5-a250-a24a9c1ccb57%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by emrahkocaman** [comment]
@sancar I think this is a similar problem solved with https://github.com/hazelcast/hazelcast/pull/9443.
Imagine that member is restarted, clients reconnects it when it's available but uses the old proxy so no new proxy is created on member side after reconnection.
WDYT?

**Comment by sancar** [comment]
@emrahkocaman Yes, you are right. This is exactly why it is not working.  Client only creates proxy on server when client.getMap called  Operations called on map like map.put/get does not create proxy on node. Similarly for example PutOperation also does not create proxy.  A new joined member gets old proxies via PostJoinOperation. So this issue only happens when there is single node and it is restarted.

I am not sure what should be the solution. May be all operations coming from client should create the related proxy on the server.

**Comment by sancar** [comment]
Ok. I remembered why map.put does not create proxy on the server when done from client
Following code prints 1 0 0 both on node and client. I guess we don't want to break this behaviour.

        IMap<Object, Object> a = instance.getMap("a");
        System.out.print(instance.getDistributedObjects().size());
        a.destroy();
        System.out.print(instance.getDistributedObjects().size());
        a.put(1, 1);
        System.out.print(instance.getDistributedObjects().size());

**Comment by ahmetmircik** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/9630
