### ISSUE TITLE
connection exception logged after client disconnects in ClientListenerSupport

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#9709]
The class has the following method:

```
    public void connectionRemoved(Connection connection) {
        if (connection.getEndPoint().equals(ownerConnectionAddress)) {
            if (client.getLifecycleService().isRunning()) {
                fireConnectionEvent(LifecycleEvent.LifecycleState.CLIENT_DISCONNECTED);

                clusterExecutor.execute(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            connectToCluster();
                        } catch (Exception e) {
                            logger.warning("Could not re-connect to cluster shutting down the client", e);
                            client.getLifecycleService().shutdown();
                        }
                    }
                });
            }
        }
    }
```
what the reason to log error stack in the exception catch section? It is expected that client will not able to reconnect, right? Is it possible to change it to:
```
                            logger.info("Could not re-connect to cluster shutting down the client");
```
, just to prevent unnecessary error logs on the client side?

Thanks, Denis.

**Comment by sancar** [comment]
If client is shutdown by user  with `clientInstance.shutdown()` then this code path will never run. And it will never be logged.

When client itself could not connect and give up, it should be a warning, because it is not intentional. The cluster that expected to be there is gone. 

Although I agree with stacktrace is not giving extra inside, exception message has information about tried addresses. So we can convert to following to get rid of stacktrace , but I think warning should stay.

       logger.warning("Could not re-connect to cluster shutting down the client " + e.getMessage() );

**Comment by dsukhoroslov** [comment]
Ok, I agree
