### ISSUE TITLE
MapLoader: keys set modification in loadAll creates duplicates

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#9717]
new feature request: provide the ability to modify the keys while loading values

Reproducer

```

public Map<PersonKey, Person> loadAll(Collection<PersonKey> keys) {
		System.out.println("loadAll :"+keys);
		Map<PersonKey,Person> tempMap = new ConcurrentHashMap<>();
		for (PersonKey key : keys) {
			Person person = personDAO.getPerson(key.getId());
			System.out.println(person);
			tempMap.put(KeyUtil.getKey(person), person);
		}
		return tempMap;
	}
```

https://github.com/gAmUssA/HZCacheDuplicateKeys/blob/master/hz-cache-test/src/main/java/com/anil/hzcachetest/loader/PersonLoader.java#L44

**Comment by tombujok** [comment]
Just thought about it and it's against our design principle, since the values are distributed to nodes based on the key value. If the key value changed while the values are loaded on the "proper" node changing the key may mean that the hashing algorithm may result in a different node from the one where the values are actually loaded.
So it looks like a "won't fix" to me. // CC @jerrinot

**Comment by jerrinot** [comment]
I agree with @tombujok - his reasoning makes complete sense.
