### ISSUE TITLE
[near-cache] Spring Support for NearCache pre-loader

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#9771]
Currently there is no Spring support for Near-Cache preloader. At least I don't see anything in the XSD.

**Comment by Donnerbart** [comment]
Stupid question: is Spring just used to create HZ members? Because the Near Cache preloader is just implemented in HZ clients (IMap and JCache). If so this issue could be closed :)

But I also wanted to implement the preloader for the member maps, which should just be two lines of code per proxy + add a unified test configuration class + config stuff (which is the most regarding the code changes). WDYT?

**Comment by jerrinot** [comment]
@Donnerbart there is a Spring support even for clients: https://github.com/jerrinot/hazelcast/blob/5156c1b3fc5103a56b76251a4773703850c1080c/hazelcast-spring/src/test/resources/com/hazelcast/spring/node-client-applicationContext-hazelcast.xml#L61

**Comment by Donnerbart** [comment]
The issue has been addressed and is waiting for another reviewer (hint): https://github.com/hazelcast/hazelcast/pull/10945
