### ISSUE TITLE
RingBuffer documentation seems incomplete

### ISSUE THREAD

**Issue by mufumbo** [hazelcast/hazelcast#9810]
We're trying to implement RingBuffer to improve performance in a multi continent cluster. We were using queues and had to migrate to list and now trying RingBuffer. 

On RingBuffer documentation we always see this pattern:

```
     * <code>
     * Ringbuffer<String> ringbuffer = hz.getRingbuffer("rb");
     * long seq = ringbuffer.headSequence();
     * while(true){
     * String item = ringbuffer.readOne(seq);
     * seq++;
     * ... process item
     * }
     * </code>
```

I think this code is wrong because seq will always be increased till max long size. There's not one place where the RingBuffer will wrap back to position zero? It's not easy to understand how this works. Does RingBuffer SEQ is always an auto incremental long or it goes back to zero when it's bigger than the size of the RingBuffer?

It's also very confusing because headSequence is always zero even after multiple calls to readManyAsync. Only tailSequence changes after we add elements, but that's not what we want.

We're very confused, can you guys advise how to use RingBuffer in a distributed system? Our use case is that we want only one of the servers to be listening for items to be processed, and then process them or distribute the traffic.  If that server dies, then we have another server picking up a distributed lock and listening for this RingBuffer (so we will probably will need a distributed Map with the last ringbuffer sequence)

thanks!

**Comment by tkountis** [comment]
Hey @mufumbo. I would suggest giving the data structure a try and trace the flow to learn how it works, the majority of your questions are details on the implementation of **any** ring buffer, and you will find plenty of resources on that online. I will attempt to answer some of your questions here.

> I think this code is wrong because seq will always be increased till max long size.

The sequence is not increasing out of control, since the `readOne` operation waits until an item is available read from the ringbuffer. Also to better understand the `LONG` bounds, imagine that even if you add 1M elements per second in this ringbuffer, you will most likely need a few **hundred  thousand years** until you get to that Long.MAX_VALUE

> Does RingBuffer SEQ is always an auto incremental long or it goes back to zero when it's bigger than the size of the RingBuffer?

A ring buffer has head and tail sequences, which together act as the _rolling_ boundaries of the ring. Adding an item increments the `tail` by one, and once the different of `tail` with the `capacity` of your ring is equal to the `head` we increment the head. The concept might appear confusing, but its  easier to understand by stepping through the code.

> It's also very confusing because headSequence is always zero even after multiple calls to readManyAsync. Only tailSequence changes after we add elements, but that's not what we want.

In Hazelcast's implementation `head` is not increment by the read operation, but rather with the write operation, when that reaches the capacity.

> We're very confused, can you guys advise how to use RingBuffer in a distributed system? Our use case is that we want only one of the servers to be listening for items to be processed, and then process them or distribute the traffic. If that server dies, then we have another server picking up a distributed lock and listening for this RingBuffer (so we will probably will need a distributed Map with the last ringbuffer sequence)

Where is your consumer code running ? Will it be a member or a client ?
If you want to have a durable sequence, to access again in an event of a failure, then I would suggest using an `IAtomicLong`. 

Hope this helps.

Feel free to re-open if you still think that something is wrong or even consider [Gitter](https://gitter.im/hazelcast/hazelcast) for any concerns or questions.
